### ISSUE TITLE
[Bug]: the chainId is different from the one in the wallet.

### ISSUE THREAD

**Issue by AliceW-03** [MetaMask/metamask-sdk#1112]
### SDK

Web

### Provide environment information

telegram desktop version 5.6.3 x64

### MetaMask SDK Version

0.30.1

### MetaMask Mobile app Version

7.33.0

### How are you deploying your application? (if relevant)

telegram webapp

### Describe the Bug

When I connect metamask in my telegram webapp, switch chains, and then reload the page, the chainId is different from the one in the wallet.
I noticed that you store a .MMSDK_cached_chainId in the cache to persist the login. After switching chains, this field retains the old chainId. When the page is reloaded, the retrieved chainId becomes the old value, even though the wallet has already switched to the new chain.

### Expected Behavior

The chainId retrieved after reloading the page should match the one in the wallet.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://metamask-cache-chain-id.vercel.app/

### To Reproduce

I deployed a reproduction in my test [bot.](https://t.me/WYFTEST_bot) You can enter the bot and type /metamask.

1. connect wallet
2. switch chain
3. reload in the top right corner.

**Comment by christopherferreira9** [comment]
Hi @AliceW-03 !  I wasn't able to reproduce this issue, can you check if the correct steps were followed?

https://github.com/user-attachments/assets/be0504eb-0d86-497e-a94b-88c33e1e9764
