### ISSUE TITLE
[ReactNative, ios] When re-connect is repeated, there is a problem that does not connect normally (MetaMask SDK Version: v0.2.3)

### ISSUE THREAD

**Issue by reese-1eco** [MetaMask/metamask-sdk#112]
**Describe the bug**
- When re-connected, it does not connect normally.
    - case1, after calling terminate()
    - case2, after closing reactNativeDemo app

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the recatNativeDemo app.
2. Click the 'connect' button.
3. Connect a Metamask account and switch to recatNativeDemo.
4. Display the connect info on recatNativeDemo.
5. Click the terminate button.
6. Retry from step 2 (clicking the 'connect' button) onwards -> -> Success or Failure (no specific error message is displayed).

**Expected behaviour**
I expect it to connect successfully to metamask after calling "terminate()" or after re-running "recatNativeDemo".

**Screenshots**
Attach "reconnect-failed.mp4" including the test process.
- [reconnect-failed.mp4](https://github.com/MetaMask/metamask-sdk/assets/102128366/6ab8bd80-02ad-473b-91af-086c84dda578)

**Provide environment information**
- Platform : React-Native
- MetaMask SDK Version: v0.2.3
- MetaMask Mobile Version: v6.3.0(1095)
- Browser (if relevant): Chrome 113.0.5672.92 (arm64)

**Additional context**
- No problem connecting web app(examples/create-react-app) and chrome extension metamask(v10.29.0)
- When using metamask-sdk(v0.2.3) and metamask-mobile(v6.3.0(1095)), there is no session information in wellectConnect sessions even if the connection is successful
- In case of connection problem, if you close metamask-mobile and try to connect, it connects normally, i.e. the first one always succeeds
- The source used in the above video is shared at https://github.com/reese-1eco/metamask-sdk-reactNativeDemo.

**Comment by reese-1eco** [comment]
**Further explanation of the operation of the video attached above (reconnect-failed.mp4):**

1. First connet: success
2. -> terminate -> second connect: success
3. -> terminate -> 3rd connect: Failed (not connected even after waiting)
4. -> End of metamask -> 4th connect: Success
5. -> terminate -> 5th connect: failure (not connected even after waiting)

**Comment by abretonc7s** [comment]
Hi @reese-1eco ,

Thanks for providing the details. We may have an issue with current metamask wallet version where reconnection problem can occur after termination. 
A wallet update is incoming but may take a few more days to be available in stores.

**Comment by andreahaku** [comment]
@reese-1eco did the latest versions of MM mobile wallet and SDK fixed it? If so we can close the issue.
Thanks for reporting.

**Comment by reese-1eco** [comment]
@andreahaku, 

Thank you for your support.
After the version upgrade, the issue situation has changed, so I will organize it and register it as a new issue.

**Comment by christopherferreira9** [comment]
Thank you for reporting !
