### ISSUE TITLE
[ReactNative, ios] Issues occurred in the use of Contract's ABI (MetaMask SDK: v0.2.3, MetaMask Mobile: v6.3.0)

### ISSUE THREAD

**Issue by reese-1eco** [MetaMask/metamask-sdk#113]
**Describe the bug**
- Information cannot be retrieved normally when the readonly api of the contract is executed.
    - ex) basic api - contract.name(), contract.symbol(), contract.decimals(),,, 
- The test source is basically a function that reads the contract information, and the web app and mobile app were compared and tested with the same code.
    - base source of web app: /examples/create-react-app
    - base source of mobile app: examples/reactNativeDemo
- The modified source to test the contract function is as follows.
    - app source: https://github.com/reese-1eco/metamask-sdk-reactNativeDemo
    - web source: https://github.com/reese-1eco/metamask-sdk-reactNativeDemo/blob/main/refer-examples-CRA-web-app/create-react-app.tgz  

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the recatNativeDemo app.
2. Click the 'connect' button.
3. Connect a Metamask account and switch to recatNativeDemo.
4. Display the connect info on recatNativeDemo.
5. Click the "try to get contraint info" Click
6. check call function with debugging tools 

**Expected behaviour**
expect to be able to read information normally and use contract abi.

**Screenshots**
- test to read contract information  
    - ![use-contract-web-app, react](https://github.com/MetaMask/metamask-sdk/assets/102128366/a77519bd-da4c-4570-8082-c30644e3e9d2)
    - ![use-contract-mobile-app, react native](https://github.com/MetaMask/metamask-sdk/assets/102128366/55a00684-e0bf-46c4-9d9b-593205c6302e)

**Provide environment information**
- Platform : React-Native
- MetaMask SDK Version: v0.2.3
- MetaMask Mobile Version: v6.3.0(1095)
- Browser (if relevant): Chrome 113.0.5672.92 (arm64)

**Additional context**

**Comment by reese-1eco** [comment]
** test contract information**
- main net BNB
- https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52
- 0xB8c77482e45F1F44dE1745F52C74426C631bDD52

Is there anything else I can do to fix the problem? If it is possible to give a guide, I will try to solve it.

**Comment by reese-1eco** [comment]
It appears to be an issue related to #108

**Comment by abretonc7s** [comment]
The issue seems to be linked to using ethers. You should still be able to use web3 library to access the contract until we find a fix for ethersjs.

**Comment by andreahaku** [comment]
we are still investigating this and trying to find a solution.
In any case please update to the latest version of the SDK (v0.4.0 should be released later today).
Thanks for reporting.

**Comment by reese-1eco** [comment]
Thank you for providing information. I will check after installing sdk version 0.4.0.

**Comment by reese-1eco** [comment]
@abretonc7s 
What is the best way to use smart contract's api with metamask-sdk version 0.5.3? Would it be better to use web3.js over ethers.js?

**Comment by abretonc7s** [comment]
We are still working on integrating new hooks to handle smart contracts but in the meantime using web3 is probably the best way for now.

**Comment by reese-1eco** [comment]
@abretonc7s 
thank you I will also try to use web3.js. Is there a recommended web3.js version or example? Please share if possible. I'm currently developing a dapp for mobile with react native.

**Comment by abretonc7s** [comment]
Please see this example
```ts
    const account = await sdk?.connect();
    console.log('account', account);
    let web3 = new Web3(sdk?.getProvider() as any);
    const accounts = await web3.eth.requestAccounts();
    console.log('accounts', accounts);

    await web3.eth.personal.sign(
      web3.utils.utf8ToHex('this is a test'),
      accounts[0],
      undefined as any,
    );
  };
```

Closing the issue for now, feel free to open another one if you need additional support.
