### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by RyanHosseini** [MetaMask/metamask-sdk#115]
**Describe the bug**
I just came across MetaMask SDK and then tried to install and use it in my React DApp, but after the initialization of MetaMask SDK (in a separate React hook), it gives me this error! I even defined  `process` in `.env` file and did other stuff and solutions but it didn't solve the problem,

I don't know what's wrong with it.

**To Reproduce**
Steps to reproduce the behaviour:
1. If it's necessary, Go to [my DApp repository](https://github.com/ryanhosseini/spectre-decentralized-exchange) which is available on GitHub profile.
2. then, Check out the `src/hooks/useMetaMask.tsx`
3. You can see if there is any mistake I've made or it perhaps is an issue!

**Expected behaviour**
It must not throw this kind of error!

**Screenshots**
![Screenshot from 2023-05-17 12-10-18](https://github.com/MetaMask/metamask-sdk/assets/51256681/af999625-d8d6-40e4-9ef7-3745b9f62d5f)

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): React 18.2.0 | TypeScript
- Node.js Version: v18.16.0
- NPM version:  v9.6.6
- MetaMask SDK Version: 1.0.0 (Latest)
- Browser (if relevant): Brave - Version 1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit)

**Comment by RyanHosseini** [comment]
I installed `process` and imported it again, but it didn't help! Can someone just please help me?

**Comment by RyanHosseini** [comment]
Thanks for taking the time @abretonc7s, Yes, That's right, I installed `@metamask/sdk` first and after getting these kinds of errors, I removed it from the repo entirely and preferred to stay with MetaMask Provider API,
and I also implemented MetaMask SDK the same as https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/create-react-app,

**But it didn't work!** maybe it's just because I"m on **Vite + TypeScript**, not **CRA**, I don't know exactly.
and I'm also sorry, I must've created another branch and then linked it here.

and I also followed the MetaMask.io docs about using MetaMask SDK, but it's about the initialization of the package, It doesn't even initialize when you wanna use it.

I created a `metamask/sdk` branch for my DApp, which you can see [here](https://github.com/ryanhosseini/spectre-decentralized-exchange/tree/metamask/sdk), if you navigate to `src/hooks/useMetaMask.tsx`, you can now see that I just imported & implemented the package so simply as docs.metamask.io taught but I'm still getting these kinds of errors.

It'd be my pleasure if you do me a favor and check it out whenever you had time.

Thank you so much for your help @abretonc7s

**Comment by deeeed** [comment]
Hi @RyanHosseini ,

You were right, I checked your branch and there is an issue because of vite.
One way to fix it is to use the following vite config:
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  define: {
    // By default, Vite doesn't include shims for NodeJS/
    // necessary for segment analytics lib to work
    global: {},
  },
  resolve: {
    alias: {
      process: "process/browser",
      buffer: "buffer",
      crypto: "crypto-browserify",
      stream: "stream-browserify",
      assert: "assert",
      http: "stream-http",
      https: "https-browserify",
      os: "os-browserify",
      url: "url",
      util: "util",
    },
  },
  server: {
    port: 3000,
  },
});
```

Cheers

**Comment by RyanHosseini** [comment]
> Hi @RyanHosseini ,
> 
> You were right, I checked your branch and there is an issue because of vite which doesn't seem to handle the polyfills correctly.
> 
> One way to fix it is to use the following vite config:
> ```
> import { defineConfig } from "vite";
> import react from "@vitejs/plugin-react";
> import tsconfigPaths from "vite-tsconfig-paths";
> 
> export default defineConfig({
>   plugins: [react(), tsconfigPaths()],
>   define: {
>     // By default, Vite doesn't include shims for NodeJS/
>     // necessary for segment analytics lib to work
>     global: {},
>   },
>   resolve: {
>     alias: {
>       process: "process/browser",
>       buffer: "buffer",
>       crypto: "crypto-browserify",
>       stream: "stream-browserify",
>       assert: "assert",
>       http: "stream-http",
>       https: "https-browserify",
>       os: "os-browserify",
>       url: "url",
>       util: "util",
>     },
>   },
>   server: {
>     port: 3000,
>   },
> });
> ```
> 
> Cheers


Hi @deeeed, Thank you so much for taking the time and help me,

Yes, you're absolutely right, the problem is because of node polyfills and Vite, 

But unfortunately, I guess there must be something wrong with my project that it didn't work, I even installed vite polyfills plugin and it did actually somewhat solve the error, but there were still some other kinds of errors, 

And eventually, I gave it up! 

It seems like, I have to stick with MetaMask Injected Provider API 'till Vite does something about it in the future,


Again, Thank you so much for your help, really appreciate it 🙏🏻🙌🏻

**Comment by woko-hari** [comment]
> Hi @RyanHosseini ,
> 
> You were right, I checked your branch and there is an issue because of vite which doesn't seem to handle the polyfills correctly.
> 
> One way to fix it is to use the following vite config:
> 
> ```
> import { defineConfig } from "vite";
> import react from "@vitejs/plugin-react";
> import tsconfigPaths from "vite-tsconfig-paths";
> 
> export default defineConfig({
>   plugins: [react(), tsconfigPaths()],
>   define: {
>     // By default, Vite doesn't include shims for NodeJS/
>     // necessary for segment analytics lib to work
>     global: {},
>   },
>   resolve: {
>     alias: {
>       process: "process/browser",
>       buffer: "buffer",
>       crypto: "crypto-browserify",
>       stream: "stream-browserify",
>       assert: "assert",
>       http: "stream-http",
>       https: "https-browserify",
>       os: "os-browserify",
>       url: "url",
>       util: "util",
>     },
>   },
>   server: {
>     port: 3000,
>   },
> });
> ```
> 
> Cheers

Hi @deeeed, Thanks u help,but I try this vite config will throw other error, like:
![image](https://github.com/MetaMask/metamask-sdk/assets/114126093/9a9ab153-d300-45e8-b282-302938744709)
![image](https://github.com/MetaMask/metamask-sdk/assets/114126093/3810e727-65d3-4bd0-b98a-3c5e526f77e4)

Pls how can i fix it?

**Comment by abretonc7s** [comment]
Hi could you tfy the latest 0.3.0 version?

**Comment by woko-hari** [comment]
> Hi could you tfy the latest 0.3.0 version?

Yes, I try now, but I found some problem in 0.3.0 version
1. The packages types pointing to the wrong dts file, so I can't get the types
2. Only the first connection will interact successfully, and the subsequent connections will not respond. I don't konw this is my problem?
