### ISSUE TITLE
WalletConnect V2 Reported Issues

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#119]
**Issue 1:** 
Cannot establish a session between [native Kotlin Dapp](https://appdistribution.firebase.dev/i/2b254c3073d2e514) and MM via deep-link
https://images.zenhubusercontent.com/468319547/25ed3164-1015-4d07-b191-52aa1624c49e/metamast__1_.mp4

**Issue 2:** Android Only
Noticed that on Rainbow, Trust, and Metamask - wallets are not setting the `redirect` field. This should be set to a URI that can be used for deep-linking directly to your wallet (ex: `metamask:// `or `rainbow://`).
Otherwise, when sending the user to the wallet for an action, the best we can do is show the system app chooser - this is extremely poor UX because the user could accidentally select the wrong wallet (ex: they connected Metamask, but chose to launch Rainbow by accident.)

**Issue 3:** 
Opensea: Sending `eth_sendTransaction `requests to MM Android from a Kotlin Dapp does not seem to be working
getting ` java.lang.Throwable: JsonRpcInteractor: Received unknown object type`
Native Kotlin test app for WCv2:
https://appdistribution.firebase.dev/i/2b254c3073d2e514

MM is sending back:
{"id":1684337712156700,"jsonrpc":"2.0","error":{"line":3691,"column":1786,"sourceURL":"index.android.bundle"}}
which is not valid JsonRpc format

**Other Issues:** Tested on Opensea app

Test Cases and results for WalletConnect V2 
https://docs.google.com/document/d/1Ugx5w4beLw99ghX4-ccjFHEDbjJ0AyB-XPfWcGCghsg/edit#

**Comment by andreahaku** [comment]
those will be fixed with the release of 7.3.0
