### ISSUE TITLE
[JS] - SDK React Kit

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#12]
### Description
We are creating React Kit which will contain libraries and UI designs for developers to integrate and use JS SDK easier. 

### Task/Expected Behavior
- Add wagmi library to the React Kit
- Add ethers.js library to the React Kit
- Add UI designs to the React Kit. - https://www.figma.com/file/piME5CaTYUz07Gc7Ye7c22/Deeplinking--SDK?node-id=0%3A1&t=TmfRvbS967COX40L-0

Deadline - 30th March

**Comment by andreahaku** [comment]
done and available on npm:
https://github.com/MetaMask/metamask-sdk/tree/main/packages/sdk-react
