### ISSUE TITLE
MetaMask SDK with pure JavaScript is not work

### ISSUE THREAD

**Issue by Park6102** [MetaMask/metamask-sdk#121]
■My Code(test.html)
<script src="https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/cdn/metamask-sdk.js"></script>
<script>
    const MMSDK = new MetaMaskSDK()
</script>

■Error Message
Uncaught TypeError: MetaMaskSDK is not a constructor

**Comment by abretonc7s** [comment]
Please make sure to use latest sdk version (0.2.4) and initialize with:
```ts
  const MMSDK = new MetaMaskSDK.MetaMaskSDK({
    forceInjectProvider: typeof window.ethereum === 'undefined',
    dappMetadata: {
      name: "Pure JS example",
      url: window.location.host,
    }
  });
```
