### ISSUE TITLE
android run release

### ISSUE THREAD

**Issue by tingmumu** [MetaMask/metamask-sdk#126]
**Describe the bug**
When I'm in debug condition, I can run，But when I run release, expo says something wrong

**To Reproduce**
Steps to reproduce the behaviour:
1. run 'npx react-native run-android --mode=release'
2. run android studio
3. Startup simulator Pixel_3a_APl_33_arm64-v8a
4. The startup screen is shown below

**Expected behaviour**

**Screenshots**
![image](https://github.com/MetaMask/metamask-sdk/assets/15106073/8c0e08c1-db16-447f-86f8-5c5e34c15140)

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity):React-Native
- MetaMask SDK Version:0.2.4
- MetaMask Mobile Version:android 13
- Browser (if relevant):

**Additional context**

**Comment by andreahaku** [comment]
@tingmumu did you solve by updating the SDK version? if so we can close it. Thanks for reporting

**Comment by christopherferreira9** [comment]
I'll be closing this one, feel free to open a new issue if you encounter issues.
Thank you for reporting.
