### ISSUE TITLE
try catch doesn't work when connect wallet

### ISSUE THREAD

**Issue by shin101004** [MetaMask/metamask-sdk#127]
**Describe the bug**
If i reject connect wallet, it doesnt know in my dapp

try-catch doesnt work properly.

**To Reproduce**
1. Press Connect button in dapp
2. Press no button on metamask
3. my dapp doesnt know connection rejected.

**Expected behaviour**
Dapp catch error

**Screenshots**

![스크린샷 2023-05-24 오후 7 52 14](https://github.com/MetaMask/metamask-sdk/assets/61345090/de3c2fa4-ad08-4fad-99eb-a4d9fe55337d)
![스크린샷 2023-05-24 오후 7 52 32](https://github.com/MetaMask/metamask-sdk/assets/61345090/18cc5156-df20-432b-86bd-cbd6440b7b1e)

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): React-Native
- MetaMask SDK Version: 0.2.0 ~ 0.3.0
- MetaMask Mobile Version: 0.6.3 (IOS)
- Browser (if relevant):

**Additional context**

**Comment by abretonc7s** [comment]
Which version of the sdk are you using?

**Comment by shin101004** [comment]
from version 0.2.0 to version 0.3.0.

Sometimes, app crash happen.

**Comment by shin101004** [comment]
@abretonc7s is this error closed?

**Comment by abretonc7s** [comment]
The issue should be fixed with latest sdk and wallet, could you please confirm so I can close the ticket?

**Comment by shin101004** [comment]
Thank you ! i will be confirm until 26,Jun

**Comment by shin101004** [comment]
@abretonc7s I tested it, but it was the same as before.

**Comment by andreahaku** [comment]
this is fixed with v0.4.0 that's going to be published later today. Thanks for reporting.
