### ISSUE TITLE
[react-native] MetaMask often opens without the connect pop-up

### ISSUE THREAD

**Issue by svenlombaert** [MetaMask/metamask-sdk#140]
**Describe the bug**
We're migrating from using WalletConnect to connect with MetaMask to directly use the matamask-sdk because WalletConnect was pretty unreliable and didn't always bring users back to our app.

We're experiencing a worse UX with this package though. We have three cases that pop-up now:
1. MetaMask app opens with no pop-up
2. MetaMask app opens but the popover with 'Connecting to MetaMask..' stays there indefinitely
3. After the above-pop-up is gone, no 'Connect' pop-up is shown.

**To Reproduce**
Steps to reproduce the behaviour:

It's not always easy to reproduce. Sometimes it happens 5 times in a row, sometimes it's not happening for 20 times. Seems worse on Android than iOS, but iOS definitely also very inconsistent

This is a snippet of our implementation. We have a MetaMask button in our app and this is the press handler:

```typescript
  const MMSDK = new MetaMaskSDK({
    openDeeplink: (link: string) => {
      Linking.openURL(link); // Use React Native Linking method or another way of opening deeplinks.
    },
    timer: BackgroundTimer, // To keep the dapp alive once it goes to background.
    dappMetadata: {
      name: 'Delta', // The name of your dapp.
      url: WEBSITE_LINK, // The URL of your website.
    },
  });

  const onMetaMaskConnectPress = async () => {
    let accounts: string[];
    try {
      const ethereum = MMSDK.getProvider();

      accounts = await ethereum.request({
        method: 'eth_requestAccounts',
      });
    } catch (e) {
      ErrorHandler.catch(e);
      showError();
      return;
    }

    if (accounts.length === 0 || accounts[0] === undefined) {
      // TODO: different error handling
      showError();
      return;
    }

    listItemOnClick({
      type: 'ETH',
      friendlyName: 'MetaMask',
      suggestedWalletAddress: accounts[0],
      isBeta: false,
      walletOrigin: WalletOrigin.MetaMask,
      hasNftSupport: true,
    });
  };
```

**Expected behaviour**
MetaMask always successfully opens with the 'Connect' pop-up shown

**Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): React-native
- MetaMask SDK Version: 0.3.0
- MetaMask Mobile Version: v6.3.0 (1095)

**Additional context**
Also seems that with the WalletConnect implementation, we never had the 'Connecting to MetaMask...' step.

**Comment by chornesays** [comment]
We're also attempting to move from WalletConnect v1 to MetaMask SDK and running into the same issue....specifically:
>MetaMask app opens but the popover with 'Connecting to MetaMask..' stays there indefinitely

However it's 100% failure rate for us.

Platform: React-native (iOS)
MetaMask SDK Version: 0.3.2
MetaMask Mobile Version: v7.0.1

@abretonc7s is this being worked on or is there a workaround? Metamask users can no longer use our app with the walletconnect v1 shutdown.

**Comment by andreahaku** [comment]
The are some improvements already available with the latest version of MM mobile app and SDK. But more will come with the  publishing of the next version of MM mobile (7.3.0).
Thanks for reporting and please report the remaining issues you find after upgrading to the latest versions of the MM mobile app and SDK.

**Comment by vkushnirtheprosperity** [comment]
I am using SDK v0.4.1 and am getting similar problems

**Comment by abretonc7s** [comment]
Hi @vkushnirtheprosperity , 
Please try to enable session persistence: { storage: enabled: true } in the sdk options.
Connecting to Metamask is not part of WalletConnect, this is specific to the SDK.
A lot of issues are pending wallet update (v6.3) that has been delayed in the app store but has finally been approved recently. 

Please see here a demo of the current RN example with 0.4.1
https://github.com/MetaMask/metamask-sdk/assets/107169956/f43240c7-74f8-4e4f-b9fd-b5b12660c60a

**Comment by christopherferreira9** [comment]
Hi @svenlombaert ! We are working a lot of stability issues on the Mobile side that hopefully will get included in the next MetaMask Mobile Wallet v7.4.0 that should be published at the end of the month.
We'll let you know once it has been published.

**Comment by andreahaku** [comment]
@svenlombaert @vkushnirtheprosperity any update on that? were you able to make it work properly? Thanks

**Comment by christopherferreira9** [comment]
Hi @svenlombaert, @vkushnirtheprosperity. We will be closing this issue assuming the issue has been solved. Please feel free to open a new issue if the problem persists.
Thank you for reporting!

**Comment by Asad-ullah2n** [comment]
> Please try to enable session persistence: { storage: enabled: true } in the sdk options.

can u share this code pleasw
