### ISSUE TITLE
[CRASH] Android ARMv7 signal 11 

### ISSUE THREAD

**Issue by MattRHIRL** [MetaMask/metamask-sdk#142]
**Introduction**
This is in relation to the [official MetaMask asset on the Unity Asset Store](https://assetstore.unity.com/packages/decentralization/infrastructure/metamask-246786#description). I submitted a ticket to MetaMask directly and I was told to post this issue to this specific repo. 

**Describe the bug**
On only Android ARMv7 processors (32-bit architecture), we get a signal 11 (SIGSEGV) null-pointer dereference in the MetaMask Unity SDK (Unity Asset Store), faulting inside of the `MetaMaskWallet.cs:Connect()` function; with the last shown Debug appearing from `MetaMaskWallet.cs:696`. The app immediately crashes (from the segmentation fault). It works/does not crash on ARM64 (64-bit processors) for Android and all iOS devices tested. No adjustments to the core SDK have been made. 

**Device(s) affected**

Galaxy A13 5G - Android version 12 | ARMv7
Galaxy A10e - Android version 11 | ARMv7

**Log**
[com.integralrealitylabs.experiences-logcat (1).txt](https://github.com/MetaMask/metamask-sdk/files/11682513/com.integralrealitylabs.experiences-logcat.1.txt)

**Screenshots + Environment**
![Rendering_Identification (1)](https://github.com/MetaMask/metamask-sdk/assets/96259549/556ec965-fd76-44eb-b1ae-b93d02c3b2f5)
![Configuration_Compilation (1)](https://github.com/MetaMask/metamask-sdk/assets/96259549/a9372f81-b26a-45ed-a611-43550e4a4169)
![Optimization_Legacy (1)](https://github.com/MetaMask/metamask-sdk/assets/96259549/fcd6ef89-5aa4-47f4-88e9-8409d8c22fec)

**Comment by christopherferreira9** [comment]
Hi @MattRHIRL ! 
Can you try setting the IL2CPP Code Generation in Build Settings to "Faster (smaller) builds" instead of "Faster runtime"?
Let us know if it helps

**Comment by andreahaku** [comment]
@MattRHIRL does changing the build setting solve your issue? if so we'll close this. Thanks

**Comment by christopherferreira9** [comment]
I'll be closing this one, feel free to open a new issue if you encounter more issues.
Thank you for reporting.
