### ISSUE TITLE
Method eth_call should require redirect to the Metamask Mobile app

### ISSUE THREAD

**Issue by dms120** [MetaMask/metamask-sdk#150]
**Describe the bug**
After the connection is established and `connectionStatus`is `linked` i am not able to get responses from a call to a smart contract without manually entering on the MM mobile application and returning to my application.

**To Reproduce**
Steps to reproduce the behaviour:
1. Initialize the SDK and successfully establish connection
2. Initialize a Smart Contract and try to call a method
3. `RCPMS::_write method eth_call doesn't need redirect.` is logged and no value is returned

**Expected behaviour**
I should be able to have a response from the eth_call. If the only way to accomplish this is by redirecting the user to the MM app, the redirect should occur.

**Screenshots**

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): NextJS
- MetaMask SDK Version: 0.3.2
- MetaMask Mobile Version: 7.0.1
- Browser (if relevant): Chrome Android

**Comment by abigail-0111** [comment]
same problem.. have any ideas?

**Comment by abigail-0111** [comment]
i got 'RCPMS::_write method eth_getBalance doesn't need redirect.', so i switch to metamask mobile and switch back to my dapp, got balance value, it seem work?

**Comment by andreahaku** [comment]
We are aware of the issue and we are working on finding a solution that doesn't break the UX by calling the MM mobile app on every RPC call.

One option may be having an Infura key that the MM SDK can use to query the network for all the requests that don't necessarily need the MM mobile app to be awakened.

**Comment by dms120** [comment]
> We are aware of the issue and we are working on finding a solution that doesn't break the UX by calling the MM mobile app on every RPC call.
> 
> One option may be having an Infura key that the MM SDK can use to query the network for all the requests that don't necessarily need the MM mobile app to be awakened.

That would be ideal because otherwise, i'm thinking in using a default RPC url to make these requests.

**Comment by christopherferreira9** [comment]
Hi all! This has been address in the latest Wagmi connectors (2.12.22)
