### ISSUE TITLE
[JS] Modal Styles Conflict

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-sdk#152]
When the SDK is installed in a web application the styles appear to have been overridden rendering the text in some places of the modal and buttons to be unreadable.

**To Reproduce**
I have created a ViteJS React+TypeScript application. It uses a global CSS style and CSS modules. The project can be seen in the `vite-linea-sdk` branch here: [Web Directory of Onchain SVG Tickets](https://github.com/MetaMask/onchain-svg-nft-tickets/tree/vite-linea-sdk).

I have been able to set the text back to a color that is visible using:
```css
:root {
  color: #000;
}
```

Of course this requires me to be more specific in my own styles to ensure the SDK modal gets the default value I have set for root and then my components that need a lighter color had to be updated.

**Expected Behavior**
The expected behavior would be that the modal styles would be scoped and/or contain classes and id's that will not conflict with any app it is being used within. If the modal had id's or styles at the least I could target them in my current issue and create a specific override for those elements but that is not an optimal work around either.

**Screenshots**
<img width="535" alt="Screenshot 2023-06-21 at 12 11 30 PM" src="https://github.com/MetaMask/metamask-sdk/assets/4899480/bb572ab3-9f82-42d0-a282-8e19e1731b1b">
<img width="521" alt="Screenshot 2023-06-21 at 12 08 19 PM" src="https://github.com/MetaMask/metamask-sdk/assets/4899480/72a192f5-b68b-4bcd-afba-e1b00408483c">
<img width="538" alt="Screenshot 2023-06-21 at 10 15 51 AM" src="https://github.com/MetaMask/metamask-sdk/assets/4899480/982cea84-5d5a-42e7-b1a5-c4c72cfd56b8">

**Environment Info**
- Platform Web
- MetaMask SDK Version: 0.3.2
- MetaMask Mobile Version:  v7.0.1 (1126)
- Browser: 10.32.0-flask.0

**Additional Context**
I do know that the team is aware of this issue and working on a fix, I wanted to provide my experience and related code.

**Comment by andreahaku** [comment]
this is fixed from version 0.4.0 that should be published later today. thanks for reporting
