### ISSUE TITLE
SDK Communication layer having atob issues on WebGL

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-sdk#154]
When using WebGL with a MetaMask Wallet that has `@metamask/communication-layer` > 0.3.0 there's an error popping up when connecting preventing you from having the connect dialog.

**To Reproduce**
Steps to reproduce the behaviour:
1. To to a WebGL Dapp on your desktop browser or mobile browser
2. Tap connect
3. See error

**Expected behaviour**
You're presented with the connect dialog without having to dismiss the `atob` error

**Screenshots**
https://github.com/MetaMask/metamask-sdk/assets/104831203/22911339-3402-4ddd-a8d4-017e31047c45

** Provide environment information**
- Unity SDK@1.1.2
- Communication Layer 0.3.0

**Additional context**
- Doesn't happen on Communication Layer 0.2.2 & 0.2.4

**Comment by GunLengend** [comment]
Same problem, waiting for the fix.

**Comment by OmarVector** [comment]
Yup, I've reported the same bug, I've informed that it was fixed and pushed in the next release, however, testing 7.2 on android which is released yesterday the bug still produceable .

**Comment by christopherferreira9** [comment]
This is was fixed in a mobile wallet release a few versions ago. Closing now.
