### ISSUE TITLE
Metamask sdk mobile connection with pure javascript

### ISSUE THREAD

**Issue by mesutdede** [MetaMask/metamask-sdk#156]
I am using metamask sdk with pure javascript in Electron project. I connect by clicking the connect button and opening the qr code with the call ethereum.request({method: 'eth_requestAccounts'}) and scanning it with mobile metamask. But when I refresh the page I lose this connection. How can I get it to stay connected unless the user disconnects?

**Comment by mesutdede** [comment]
I'm sharing the github repo below where the code sample I'm trying to implement is located.You can find the relevant code here. (src/index.js)

https://github.com/mesutdede/electron-metamask-test

**Comment by abretonc7s** [comment]
Hi @mesutdede , if you use electron you can refer to our example folder for nodejs.
https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/nodejs

To enable session persistence, you can add a setting:
```
  storage: {
    enabled: true,
  },
```
```

const options = {
  shouldShimWeb3: false,
  storage: {
    enabled: true,
  },
  dappMetadata: {
    name: 'NodeJS example',
  },
  modals: {
    install: ({ link }) => {
      // console.debug(`open link ${link}`);
      qrcode.generate(link, { small: true }, (qr) => console.log(qr));
    },
    otp: () => {
      return {
        updateOTPValue: (otpValue) => {
          if (otpValue !== '') {
            console.debug(
              `[CUSTOMIZE TEXT] Choose the following value on your metamask mobile wallet: ${otpValue}`,
            );
          }
        },
      };
    },
  },
};

const sdk = new MetaMaskSDK(options);
```

**Comment by mesutdede** [comment]
Hi @abretonc7s,
Thanks for reply.
The code sample you shared allows me to keep the connection. However, a popup message appears on page transitions asking if I want to continue the connection. I want it to stay connected unless the user disconnects.

**Comment by abretonc7s** [comment]
For security reason and prevent the connection to be hijacked, the connection needs to be revalited with an OTP before allowing rpc calls.
You should try to manage your app like a react as a single page to avoid the reloads.

**Comment by mesutdede** [comment]
I converted the application to a single page structure. However, there is one problem. After a while after connecting with the Metamask mobile wallet, the page automatically refreshes and a pop-up window appears with a disconnect button.
