### ISSUE TITLE
[DOCS] [UNITY] Create Contract and NFT API Library Document

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#164]

**Comment by andreahaku** [comment]
This is the documentation developed by @ecp4224 

[Contract Interaction Docs.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZytrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ee6fd5473f09a436486e9d3121116a5d6e56533/Contract%20Interaction%20Docs.zip)

**Comment by michaellu88** [comment]
i can't download the file, File permission Denied
