### ISSUE TITLE
[JS] Add new events to JS SDK

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#171]
### sdk_connect_request_failed
This event should be triggered when the “connect request” procedure has been started, but failed.
The error / reason for the failure should be recorded.
There should be two separate events for the MM mobile app and dapp so that if one party fails to join the room we can monitor it through our data. 
### sdk_connection_failed
This event should be triggered when the attempt to establish a connection fails. This can be either due to the user rejecting the connection, or some other reason.
The returned / resulting error should be recorded.
There should be two separate events for the MM mobile app and dapp so that if one party fails to join the room we can monitor it through our data. 
### sdk_connection_accepted / sdk_connection_rejected
Accepting/rejecting connection - authorising the connection
This event should be triggered based on the user's response to the connect modal.

**Comment by abretonc7s** [comment]
Done
