### ISSUE TITLE
Wrong path for the types in package.json of "@metamask/sdk"

### ISSUE THREAD

**Issue by Sap333** [MetaMask/metamask-sdk#172]
When you install "@metamask/sdk" the "package.json" of the module in "node_modules" contains the next string:
> "types": "dist/browser/es/src/index.d.ts".<br>

But there is no such path in the module's directory tree! The right one seems to be "dist/browser/es/**sdk**/src/index.d.ts".<br>
The type system seems to be totally broken because of this.

**Comment by thatssosanya** [comment]
apparently I picked the worst time to try the sdk lol. just wasted a bunch of time adding types locally. god bless you @Sap333 

![image](https://github.com/MetaMask/metamask-sdk/assets/28807741/f8d5bb78-4ae6-4afc-a096-b45903f95e71)

**Comment by andreahaku** [comment]
This is now fixed with version 0.4.0 that is going to be published today. Thanks for reporting

**Comment by DSapielkin** [comment]
<img width="526" alt="Снимок экрана 2023-07-19 в 09 26 31" src="https://github.com/MetaMask/metamask-sdk/assets/131247379/5dc026d2-760b-439e-8457-556be8d2d068">

**Comment by DSapielkin** [comment]
I use "@metamask/sdk": "^0.5.0",

```
Could not find a declaration file for module '@metamask/sdk'
Try `npm i --save-dev @types/metamask__sdk` if it exists or add a new declaration (.d.ts) file containing `declare module '@metamask/sdk';`
```
