### ISSUE TITLE
Unity3d metamask sdk occur crash on ios system less than 16.0

### ISSUE THREAD

**Issue by chengshan-zhou** [MetaMask/metamask-sdk#181]
1. Create one empty unity3d 2021.3.16 project
2. Import metamask unity3d sdk (version:1.1.2, 2023/5/31)
3. export ios project, build
4. It works well on iOS devices which system is greater than 16.0, but  it will occur crash on other systems

the crash log:
Symbol not found: (_$s10Foundation10URLRequestV15timeoutIntervalSdvs)

**Comment by oshimo-dev** [comment]
@christopherferreira9 
I got the same issue with our product.

Is the metamask development team working to resolve this issue?
If so, do you have an estimate of when it will be resolved?
Looking forward to your reply.

Our crash log is below.
```
Symbol not found: _$s10Foundation10URLRequestV15timeoutIntervalSdvs
  Referenced from: /private/var/containers/Bundle/Application/*****/*****.app/Frameworks/MetaMask_iOS.framework/MetaMask_iOS (which was built for iOS 16.2)
  Expected in: /System/Library/Frameworks/Foundation.framework/Foundation
```

Unity Editor: 2021.3.24f

**Comment by christopherferreira9** [comment]
Hi @oshimo-dev , we're sorry for the delay but we're haven't manage to debug this yet. We'll get back to you as soon as we have more information.

**Comment by oshimo-dev** [comment]
@christopherferreira9 
Hi, How is the debug situation?

**Comment by oshimo-dev** [comment]
@christopherferreira9
Hey, How is the debug situation? I'm waiting for your reply.

**Comment by fareedTahir131** [comment]
I am also facing this issue for many days, I don't when you guys will resolve this issue. I need to implement this as soon as possible for the client app.

**Comment by oshimo-dev** [comment]
Let me try. Thank you.
