### ISSUE TITLE
Metamask sdk refresh page automatically problem

### ISSUE THREAD

**Issue by mesutdede** [MetaMask/metamask-sdk#190]
I converted the application to a single page structure. However, there is one problem. After a while after connecting with the Metamask mobile wallet, the page automatically refreshes and a pop-up window appears with a disconnect button.

**Comment by christopherferreira9** [comment]
Hi @mesutdede ! Can you share with us the SDKOptions you're using? Also, can you provide some more information like the technology and SDK version you're using or some repo we can look at?
This seems related to having one session already going. If you click disconnect and scan again does it still happen?

**Comment by mesutdede** [comment]
Hi @christopherferreira9 

sdk version 0.3.2

Yes, after a while after disconnecting and reconnecting, the page automatically refreshes and a pop-up window appears with a disconnect button.

`const options = {
    shouldShimWeb3: false,
    dappMetadata: {
        name: "DatsProject Dapp",
        url: window.location.host,
    },
    storage: {
        enabled: true,
    },
    logging: {
        sdk: false,
    }
};

const MMSDK = new MetaMaskSDK.MetaMaskSDK(options);
const ethereum = MMSDK.getProvider();

async function onConnect() {

    const accounts = await ethereum.request({
        method: "eth_requestAccounts",
        params: []
    });

    selectedAccount = accounts[0];

    ethersProvider = new ethers.providers.Web3Provider(window.ethereum, 56);
    signer = ethersProvider.getSigner();


    ethereum.on("chainChanged", function(networkId) {
        //window.location.reload();
    });

    ethereum.on("accountsChanged", (account) => {
        window.location.reload();
    });

    ethereum.on("disconnect", ()=>{
        onDisconnect();
    })
}`

**Comment by christopherferreira9** [comment]
As soon as you connect your wallet an `accountsChanged` is fired so by having the following listener:
```
ethereum.on("accountsChanged", (account) => {
    window.location.reload();
});
```
you're breaking the connection and forcing a new one to happen. Since there was a previous connection there it'll try to resume that same connection.

**Comment by mesutdede** [comment]
Hi @christopherferreira9 

I canceled the accountchanged event but the problem persists.

**Comment by abretonc7s** [comment]
Please update your code to latest sdk version and try to follow the example from 
https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/create-react-app

**Comment by mesutdede** [comment]
Hi @abretonc7s 
Thanks for reply.
We use electron and pure javascript in our project. Do you have a solution suggestion for this?

**Comment by andreahaku** [comment]
we are about to release an example electron application.
You can have a look at the PR with it [here](https://github.com/MetaMask/metamask-sdk/pull/192)

Hope this helps you solve it.

**Comment by christopherferreira9** [comment]
Hi @mesutdede . We will be closing this issue assuming the issue has been solved. Please feel free to open a new issue if the problem persists.
Thank you for reporting!
