### ISSUE TITLE
Unable to connect to wallet on Android and ios

### ISSUE THREAD

**Issue by brownSocial** [MetaMask/metamask-sdk#195]
**Describe the bug**
Use the latest metamask sdk to connect. In the Google browser of Android mobile phones, you can jump to metamask, but it is always connected and cannot be connected. It has always been like this
**To Reproduce**
Steps to reproduce the behaviour:
1. Use Android Google Chrome to visit the web
2. connect metamask

**Expected behaviour**
Connect to metamask
**Screenshots**
![image](https://github.com/MetaMask/metamask-sdk/assets/138547489/9c701005-96da-4b95-8081-75e92d1bad3e)

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity):
- MetaMask SDK Version:^0.4.2
- MetaMask Mobile Version:v7.1.0
- Browser (if relevant):

**Additional context**
The code is as follows
     const mmsdk = new MetaMaskSDK({
          dappMetadata: {
            url: window.location.href,
            name: 'Airdrop',
          },
        });
        provider = mmsdk.getProvider();
        if(!provider){
          return;
        }
        const accounts = await provider.request({
          method: 'eth_requestAccounts',
          params: [],
        });
        console.log('MetaMask connect success account:', accounts);

**Comment by OmarVector** [comment]
I have the same problem , when you testing your website during development, it turn out when you have too many season for the same site this issue happen a lot.

Best way to minimize that is go to settings and session and kill all sessions related to your website . then refresh and login again.

I'm pretty sure there be something to fix that but this is the work around that helped me

**Comment by christopherferreira9** [comment]
Hi @OmarVector !
Yesterday we've released a new version of the sdk v0.5.0. Can you please give that a go and can you also try it without the VPN to see if it solves the issue?

**Comment by OmarVector** [comment]
> Hi @OmarVector ! Yesterday we've released a new version of the sdk v0.5.0. Can you please give that a go and can you also try it without the VPN to see if it solves the issue?

Hi Crhis:))

I'm using unity SDK atm not the native SDK , so not sure if there any updates available atm.

From my side, thanks for raising up the flag for VPN, I'm using VPN all the time, I will consider that too when this happen again.

**Comment by christopherferreira9** [comment]
Hi @OmarVector . Can you please open a ticket with the relevant information about the issue you're experiencing?

**Comment by christopherferreira9** [comment]
Hi @brownSocial !
Yesterday we've released a new version of the sdk v0.5.0. Can you please give that a go and can you also try it without the VPN to see if it solves the issue?

**Comment by OmarVector** [comment]
> Hi @OmarVector . Can you please open a ticket with the relevant information about the issue you're experiencing?

Its exactly like this issue, the only different it happen randomly and using Unity SDK instead. so I believe its something could be related to native plugin.

**Comment by abretonc7s** [comment]
Hi @OmarVector , could you provide an example repo so we can check the code?
Or directly show the code in the thread please.

**Comment by andreahaku** [comment]
@brownSocial @OmarVector please update to the latest version of the MM SDK. For Unity we are about to release an updated version very soon.

Also please check that no VPN is used during the connection as it may cause issues with the communication layer that is based on Socket.io.

We are also aware of some random performance issue on the connection due to high loads on our servers and we are about to fix them with a performance/stability update of the servers.

**Comment by christopherferreira9** [comment]
Hi @brownSocial , @OmarVector . We will be closing this issue assuming the issue has been solved. Please feel free to open a new issue if the problem persists.
Thank you for reporting!

**Comment by Dejavu0709** [comment]
> @brownSocial @OmarVector please update to the latest version of the MM SDK. For Unity we are about to release an updated version very soon.
> 
> Also please check that no VPN is used during the connection as it may cause issues with the communication layer that is based on Socket.io.
> 
> We are also aware of some random performance issue on the connection due to high loads on our servers and we are about to fix them with a performance/stability update of the servers.

Hi，We meet the same issue，but if without the vpn，the user in China how to connect to the metamask？Is this means Chinese user can not use the metamask sdk because they must use vpn。。。
