### ISSUE TITLE
How to get OPEN LINK url

### ISSUE THREAD

**Issue by BondPiyapan** [MetaMask/metamask-sdk#202]
I'm need to get the value of OPEN LINK url to show the result to open webview for Mobile app (Flutter) that we developed to connect with node js and send value via deeplink.

My Code : 
`export async function getWalletLinkURL() {
  const MMSDK = new MetaMaskSDK();

  const ethereum = MMSDK.getProvider();

  const accounts = await ethereum.request({
    method: 'eth_requestAccounts',
    params: [{
      eth_accounts: {},
    }],
  });
}`

Image console.log url need 

<img width="710" alt="Screenshot 2566-07-11 at 14 23 12" src="https://github.com/MetaMask/metamask-sdk/assets/32051406/70c81b58-754a-4530-92a3-8efeca3a625d">

Thank you.

**Comment by abretonc7s** [comment]
Another way to do it is to customize the modals:
```ts
const options: MetaMaskSDKOptions = {
  shouldShimWeb3: false,
  dappMetadata: {
    name: 'NodeJS example',
    base64Icon: '000'
  },
  // Optional: customize modal text
  modals: {
    install: ({ link }) => {
      qrcode.generate(link, { small: true }, (qr) => console.log(qr));
      return {
        onClose() {
          // nothing to do.
        },
      };
    },
    otp: () => {
      return {
        updateOTPValue: (otpValue) => {
          if (otpValue !== '') {
            console.debug(
              `[CUSTOMIZE TEXT] Choose the following value on your metamask mobile wallet: ${otpValue}`,
            );
          }
        },
      };
    },
  },
};
```
This example is extracted from the nodejs example but you can do the same with html.
We will update the documentation soon with examples.

**Comment by abretonc7s** [comment]
Actually for your use case, the best would be to use `sdk.getUniversalLink()`

**Comment by BondPiyapan** [comment]
> Hi @BondPiyapan ! You can do so in the `MetaMaskSDKOptions` like we do in the ReactNative example:
> 
> ```
> const sdk = new MetaMaskSDK({
>   openDeeplink: (link: string) => {
>     if (canOpenLink) {
>       Linking.openURL(link);
>     }
>   },
>   timer: BackgroundTimer,
>   dappMetadata: {
>     url: 'ReactNativeTS',
>     name: 'ReactNativeTS',
>   },
> });
> ```
> 
> In the `openDeeplink` you can specify how you want links to be handled for the SDK. Feel free to check the reference [here](https://github.com/MetaMask/metamask-sdk/blob/main/packages/examples/reactNativeDemo/App.tsx). Thanks for reporting!

Thank you @christopherferreira9 you save my life.
