### ISSUE TITLE
[SOCKET] Separate MM app and dapp SDK events

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#203]
### **sdk_connect_request_started**
This event is triggered when both the dapp and MM have joined the socket.io room, but before they don’t exchange any data.
There should be two separate events for the MM mobile app and dapp so that if one party fails to join the room we can monitor it through our data. 
**sdk_connect_request_started_metamask**
**sdk_connect_request_started_dapp**
### sdk_connection_established
This event is triggered when the SDK connection has been established, and session keys have been exchanged. 
What happens when one party fails to exchange keys? How can we log these errors and monitor them? 
### sdk_disconnected
This event is triggered if / when an established SDK connection ends. The reason for the disconnection is NOT recorded yet.
What happens when one party fails to exchange keys? How can we log these errors and monitor them?

**Comment by abretonc7s** [comment]
Done with 0.5.0
