### ISSUE TITLE
When calling eth_requestAccounts the promise will never be resolved (v0.5.0)

### ISSUE THREAD

**Issue by dms120** [MetaMask/metamask-sdk#214]
Let's take a look at the create-react-example:

```
window.ethereum
      .request({
        method: "eth_requestAccounts",
        params: [],
      })
      .then((accounts) => {
        if(accounts) {
          console.debug(`connect:: accounts result`);
          setAccount((accounts as string[])[0]);
          setConnected(true);
        }
      })
      .catch((e) => console.log("request accounts ERR", e));
```
The text `connect:: accounts result` will never be logged because the promise is not being resolved.
The example is only working because now it's listening to the `onProviderEvent` to set the accounts and the connected flag.

```
const onProviderEvent = (accounts) => {
      console.debug(`onProviderEvent`, accounts);
      if (accounts?.[0]?.startsWith('0x')) {
        setAccount(accounts?.[0]);
        setConnected(true);
      } else {
        setAccount(undefined);
        setConnected(false);
      }
    }
```

I believe this regression was introduced on this [PR](https://github.com/MetaMask/metamask-sdk/pull/146/files) because the `connectWithExtensionProvider()` doesn't return anything.

Hope this helps find the problem.

**Comment by dms120** [comment]
Forgot to add the this just happens while connecting with the extension. Connecting with mobile works perfectly.

**Comment by abretonc7s** [comment]
Good catch, thanks. A fix will be on the way very soon.

**Comment by abretonc7s** [comment]
@dms120 please give a try to 0.5.2. It should be fixed.

**Comment by dms120** [comment]
@abretonc7s yes, it fixes this issue. Thanks for the quick fix.

But somehow i still have regressions using the 0.5.2. It's related to messages sign using libraries like web3. I can't understand exactly why but its something related to the provider object.

```
let web3 = new Web3(MMSDK.getProvider());
const accounts = await web3.eth.requestAccounts();
await web3.eth.personal.sign(
    web3.utils.utf8ToHex('this is a test'),
    accounts[0],
  );
```
The message will fail with `Error connecting: MetaMask is not connected/installed, please call eth_requestAccounts to connect first.`

But if i re-initialize the web3 object before the sign it will work, and the behavior is the same if I use window.ethereum directly. This code was working pre 0.5.x

```
let web3 = new Web3(MMSDK.getProvider());
const accounts = await web3.eth.requestAccounts();

// Adding this
web3 = new Web3(MMSDK.getProvider());

await web3.eth.personal.sign(
    web3.utils.utf8ToHex('this is a test'),
    accounts[0],
  );
```

Do you want me to open another issue?

**Comment by andreahaku** [comment]
Yes @dms120, please open a new issue with this. Thanks a lot!

**Comment by netzulo** [comment]
can we reopen this ? i got the same message
got the 1st image when im expecting after clicking my "connect" got same behaviour than the second image

```
Error: MetaMask is not connected/installed, please call eth_requestAccounts to connect first.
```
step 2 fails because im not doing the right steps to update as "sdk" component from metamask.

![image](https://github.com/MetaMask/metamask-sdk/assets/11871932/06657995-1479-4a9b-b8f7-e1b7caa085b4)
![image](https://github.com/MetaMask/metamask-sdk/assets/11871932/7d52e5e3-2cfd-45c7-a56b-00dadb0f7037)
