### ISSUE TITLE
Regression on v0.5 while using with web3 library

### ISSUE THREAD

**Issue by dms120** [MetaMask/metamask-sdk#219]
The following code stop working on 0.5.x. It's related to messages sign using libraries like web3. I can't understand exactly why but it's something related to the provider object.

```
let web3 = new Web3(MMSDK.getProvider());
const accounts = await web3.eth.requestAccounts();
await web3.eth.personal.sign(
    web3.utils.utf8ToHex('this is a test'),
    accounts[0],
  );
```

The message will fail with Error connecting: `MetaMask is not connected/installed, please call eth_requestAccounts to connect first.`

But if i re-initialize the web3 object before the sign it will work, and the behavior is the same if I use `window.ethereum` directly. This code was working pre 0.5.x

```
let web3 = new Web3(MMSDK.getProvider());
const accounts = await web3.eth.requestAccounts();

// Adding this
web3 = new Web3(MMSDK.getProvider());

await web3.eth.personal.sign(
    web3.utils.utf8ToHex('this is a test'),
    accounts[0],
  );
```

**Comment by abretonc7s** [comment]
Hi @dms120 , could you please check that the sdk is initialized first?
One way is to first connect using the sdk then init the web3 provider.
```
const accounts = await MMSDK.connect()
web3 = new Web3(MMSDK.getProvider());
```

**Comment by dms120** [comment]
Hi @abretonc7s, the Metamask SDK it's initialized, at least MMSDK.isInitialized() returns true. Also, I'm not able to reproduce this if I use `extensionOnly:true`

**Comment by dms120** [comment]
I was able to reproduce it on the NextJS example.

On the SDKContainer change the connect to this. Clear the cache first to make sure the SDK modal appears. The idea is to try to sign right after connecting. 

```
const connect = async () => {
    if (!window.ethereum) {
      throw new Error(`invalid ethereum provider`);
    }
    let web3 = new Web3(sdk?.getProvider() as any);
    const accounts = await web3.eth.requestAccounts();
    console.log('accounts', accounts);
    // Uncomment to make it work
    // web3 = new Web3(sdk?.getProvider() as any);
    await web3.eth.personal.sign(
      web3.utils.utf8ToHex('this is a test'),
      accounts[0],
      undefined as any,
    );
  };
```

**Comment by abretonc7s** [comment]
The issue is that the default provider is the mobile provider which is used to instantiate web3, then the modal opens and the user selects the extension provider.
Since you initialised web3 before calling connect, web3 doesn't detect there was a change of provider.
2 solutions:
- call await sdk.connect() first 
- re-initialize web3 after the first eth.requestAccounts()
```
const connect = async () => {
    if (!window.ethereum) {
      throw new Error(`invalid ethereum provider`);
    }
   await sdk?.connect();
    let web3 = new Web3(sdk?.getProvider() as any);
    const accounts = await web3.eth.requestAccounts();
    console.log('accounts', accounts);
    await web3.eth.personal.sign(
      web3.utils.utf8ToHex('this is a test'),
      accounts[0],
      undefined as any,
    );
  };
```

```
const connect = async () => {
    if (!window.ethereum) {
      throw new Error(`invalid ethereum provider`);
    }
    let web3 = new Web3(sdk?.getProvider() as any);
    const accounts = await web3.eth.requestAccounts();
    console.log('accounts', accounts);
    web3 = new Web3(sdk?.getProvider() as any);
    await web3.eth.personal.sign(
      web3.utils.utf8ToHex('this is a test'),
      accounts[0],
      undefined as any,
    );
  };
```
Hope this help!
