### ISSUE TITLE
sdk.getProvider() fails if called immediately after initialization

### ISSUE THREAD

**Issue by mumingpo** [MetaMask/metamask-sdk#224]
**Describe the bug**
sdk.getProvider() fails if called immediately after initialization.

**To Reproduce**
Steps to reproduce the behaviour:
1. clone https://github.com/mumingpo/keccit-web/tree/292df30368a559321b44c84aeb9296a7b1b38b22
2. in `/hooks/useProvider.ts`, modify MAX_RETRY to 0 (or just do the normal flow without the useEffect hook)
3. yarn run dev, navigate to localhost:3000, drag over some random file to fill the file hash, and start the normal sdk onboarding flow with the MetaMask button.

**Expected behaviour**
1. (minor) MetaMaskSDK should not be initialized in Next.js server-side-prerendering.
2. Either sdk.getProvider() should be able to return immediately after sdk's initialization, or it should be an async function.

**Screenshots**
![screenshot](https://github.com/MetaMask/metamask-sdk/assets/25801035/a5c0e345-c4cd-4279-b7bf-4b8d51d85ef9)

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): Web
- MetaMask SDK Version: 0.5.2
- MetaMask Mobile Version:
- Browser (if relevant):

**Additional context**

**Comment by abretonc7s** [comment]
Thank you for reporting the issue, we have a fix to prevent that issue on the way. In the meantime you can call `await sdk.init()` first, then do any calls.

For nextjs, we also provide sdk-react hooks and the examples are being updated

**Comment by mumingpo** [comment]
Thanks, that should do.
