### ISSUE TITLE
request('eth_requestAccounts') promise hangs after clicking "Connect With MetaMask Extension"

### ISSUE THREAD

**Issue by mumingpo** [MetaMask/metamask-sdk#225]
**Describe the bug**
request('eth_requestAccounts') promise hangs after clicking "Connect With MetaMask Extension"

**To Reproduce**
Steps to reproduce the behaviour:
1. clone https://github.com/mumingpo/keccit-web/tree/292df30368a559321b44c84aeb9296a7b1b38b22
2. `yarn run dev` and go to localhost:3000
3. drag a random file over to generate data hash
4. begin sdk flow by clicking "submit with metamask"
5. click connect with metamask extension

**Expected behaviour**
1. Extension should prompt for connection, and the wallet will be connected with normal authentication flow, OR
2. a proper Error should be thrown.

**Actual behavior**
Promise hangs.

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): Web
- MetaMask SDK Version: 0.5.2
- MetaMask extension Version: 10.33.1
- Browser (if relevant): Chrome/114.0.5735.199

**Additional context**

**Comment by mumingpo** [comment]
bug does not appear in production (www.keccit.com)

might be related an insecure context? (http vs https)

still really hard to develop having to push to production everytime to see result.

**Comment by abretonc7s** [comment]
Could you please check with the latest sdk version?
We have added some check to prevent that issue.

**Comment by abretonc7s** [comment]
If you r using nextjs, you can probably try to use this example as reference https://github.com/MetaMask/metamask-sdk/blob/main/packages/devnext/src/pages/index.tsx

**Comment by christopherferreira9** [comment]
Hi @mumingpo . We will be closing this issue assuming the issue has been solved. Please feel free to open a new issue if the problem persists.
Thank you for reporting!
