### ISSUE TITLE
[Improvement] Have an event to know when user closes the modal without connecting

### ISSUE THREAD

**Issue by dms120** [MetaMask/metamask-sdk#251]
During the SDK integration, I realized that having an event to track if the user closes the SDK initial modal without proceeding with the connection would be helpful.

Is it doable? Thanks.

**Comment by christopherferreira9** [comment]
Hi @dms120 ! It is doable and we'll have it as a new feature soon. Thank you for reporting!

**Comment by dms120** [comment]
Nice to hear it @christopherferreira9, thanks!

**Comment by christopherferreira9** [comment]
Hi! This is now treated as a connection rejected event.
