### ISSUE TITLE
Not a bug - but when will the metamask-react-native-sdk be released?

### ISSUE THREAD

**Issue by bearsworth** [MetaMask/metamask-sdk#255]
When I look over some of the comments and see the struggles, I know there will be a toll to pay for the hours invested in getting the library to work. 

I keep reading that the documentation is outdated, but my question is simply is there a timeline for this still? I remember reading it was May of this year, but as with any project things happen. 

Would appreciate any update tbh. 

Also for the current example do we still need to install all the additional packages with nodeify or the running example does not require this?

**Comment by bearsworth** [comment]
While I wish it was updated - I realize it was not as hard as expected. Pretty much ignore documentation and install @metamask/sdk. Then to node specific modules to work in react-native follow along:

If you use projects with RN > 0.71 such as 0.72 add --legacy-peer-deps to npm installs.

Use this command for the packages:
npm i -S @react-native-async-storage/async-storage@^1.18.1 ethers@5.7.2 node-libs-react-native@^1.2.1 react-native-background-timer@^2.4.1 react-native-randombytes@^3.6.1 react-native-url-polyfill@^1.3.0

Next go to ios folder and pod install all files.

Go to your metro config and add these to the config to make crypto and other node modules work:

```
const config = {
  resolver: {
    extraNodeModules: require('node-libs-react-native'),
  },
};
```
Add this to the very top of your index.js file before anything or the root of the app:
import 'node-libs-react-native/globals';
import 'react-native-url-polyfill/auto';

Make sure to restart metro and rebuild / start for testing.

**Comment by abretonc7s** [comment]
Hi @bearsworth ,

We are working on a native ui library but unfortunately it won't prevent the issues inherent to react native that requires to use node-libs-react-native.
We will also work on a plugin to automate the process with expo.
In the meantime, we are in the process of refactoring our documentation to make it easier for people to onboard on each platform.

**Comment by bearsworth** [comment]
> Hi @bearsworth ,
> 
> We are working on a native ui library but unfortunately it won't prevent the issues inherent to react native that requires to use node-libs-react-native. We will also work on a plugin to automate the process with expo. In the meantime, we are in the process of refactoring our documentation to make it easier for people to onboard on each platform.

Sounds good. Can't wait to see this with seamless expo install. I know I'd be one of the first to instantly start using it - so please hurry ;). 

I have used the Coinbase Wallet Mobile sdk and it works for the most part as they use expo modules  for integration. 

The only issue really is that right now I think there is some errors with sendTransaction to which I think its mostly they are blocking dev environments.

If you do go to make the expo, please allow developers to be able to sendTransactions and sign transactions on testnets.

Thank you again.

**Comment by abretonc7s** [comment]
Closing for now, please feel free to open another issue if needed.

**Comment by gajojr** [comment]
> While I wish it was updated - I realize it was not as hard as expected. Pretty much ignore documentation and install @metamask/sdk. Then to node specific modules to work in react-native follow along:
> 
> If you use projects with RN > 0.71 such as 0.72 add --legacy-peer-deps to npm installs.
> 
> Use this command for the packages: npm i -S @react-native-async-storage/async-storage@^1.18.1 ethers@5.7.2 node-libs-react-native@^1.2.1 react-native-background-timer@^2.4.1 react-native-randombytes@^3.6.1 react-native-url-polyfill@^1.3.0
> 
> Next go to ios folder and pod install all files.
> 
> Go to your metro config and add these to the config to make crypto and other node modules work:
> 
> ```
> const config = {
>   resolver: {
>     extraNodeModules: require('node-libs-react-native'),
>   },
> };
> ```
> 
> Add this to the very top of your index.js file before anything or the root of the app: import 'node-libs-react-native/globals'; import 'react-native-url-polyfill/auto';
> 
> Make sure to restart metro and rebuild / start for testing.

Does this work with expo?

**Comment by bearsworth** [comment]
> > While I wish it was updated - I realize it was not as hard as expected. Pretty much ignore documentation and install @metamask/sdk. Then to node specific modules to work in react-native follow along:
> > If you use projects with RN > 0.71 such as 0.72 add --legacy-peer-deps to npm installs.
> > Use this command for the packages: npm i -S @react-native-async-storage/async-storage@^1.18.1 ethers@5.7.2 node-libs-react-native@^1.2.1 react-native-background-timer@^2.4.1 react-native-randombytes@^3.6.1 react-native-url-polyfill@^1.3.0
> > Next go to ios folder and pod install all files.
> > Go to your metro config and add these to the config to make crypto and other node modules work:
> > ```
> > const config = {
> >   resolver: {
> >     extraNodeModules: require('node-libs-react-native'),
> >   },
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Add this to the very top of your index.js file before anything or the root of the app: import 'node-libs-react-native/globals'; import 'react-native-url-polyfill/auto';
> > Make sure to restart metro and rebuild / start for testing.
> 
> Does this work with expo?

Yeah, I'm using it for my expo project now. I don't remember but I think this or the Coinbase one you have to do a demo build and can't use expo go.

**Comment by gajojr** [comment]
> > > While I wish it was updated - I realize it was not as hard as expected. Pretty much ignore documentation and install @metamask/sdk. Then to node specific modules to work in react-native follow along:
> > > If you use projects with RN > 0.71 such as 0.72 add --legacy-peer-deps to npm installs.
> > > Use this command for the packages: npm i -S @react-native-async-storage/async-storage@^1.18.1 ethers@5.7.2 node-libs-react-native@^1.2.1 react-native-background-timer@^2.4.1 react-native-randombytes@^3.6.1 react-native-url-polyfill@^1.3.0
> > > Next go to ios folder and pod install all files.
> > > Go to your metro config and add these to the config to make crypto and other node modules work:
> > > ```
> > > const config = {
> > >   resolver: {
> > >     extraNodeModules: require('node-libs-react-native'),
> > >   },
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Add this to the very top of your index.js file before anything or the root of the app: import 'node-libs-react-native/globals'; import 'react-native-url-polyfill/auto';
> > > Make sure to restart metro and rebuild / start for testing.
> > 
> > 
> > Does this work with expo?
> 
> Yeah, I'm using it for my expo project now. I don't remember but I think this or the Coinbase one you have to do a demo build and can't use expo go.

It works, I even made a tutorial for people that have issue with this:
[Youtube](https://youtu.be/p7c92qrMBT4?si=kqFsLk_4lr2ovkMj)
