### ISSUE TITLE
How to handle user canceling connect after scanning QR code? Scanning again does not work

### ISSUE THREAD

**Issue by dms120** [MetaMask/metamask-sdk#257]
What's the expected behavior if user do not accept connect with QR code? A "Terminated" event is sent and a modal is shown.

![image](https://github.com/MetaMask/metamask-sdk/assets/12746391/4cb342aa-6042-4db1-af68-c3100777fbeb)

The first question is, should the modal be shown?
Then, how can we proceed? Scanning the QR code will not do anything, closing the modal and connecting again doesn't seem to help.

Thanks guys

**Comment by christopherferreira9** [comment]
Modal now closes when the connection is rejected.
