### ISSUE TITLE
QR code connect doest not work after terminate first time with extensionOnly: true

### ISSUE THREAD

**Issue by dms120** [MetaMask/metamask-sdk#259]
To reproduce, use the NextJS example and define `extensionOnly: true`

1. Go to a browser without Metamask extension and connect with QR code. 
2. It works
3. Terminate
4. Try to connect again with QR code
5. QR code appears but scanning it does nothing

This is the configuration we will use on VillageDAO, we give preference to extension.
Thanks guys.

**Comment by dms120** [comment]
Hi @christopherferreira9, since i was able to reproduce this using the NextJS example of the SDK I assumed this is not a configuration issue, so I didn't solve it.

**Comment by abretonc7s** [comment]
This should be solve with latest sdk version 0.6.0. The termination didnt completey clear the connection so it would have previously require a page reload on nextjs.

**Comment by christopherferreira9** [comment]
@abretonc7s this issue still persists. It seems that the QR code in the modal keeps the initial channel-id
cc: @omridan159

**Comment by andreahaku** [comment]
@dms120 can you please test it with 0.6.2 as this version should fix the issue. Please let us know so we can close this issue. Thanks a lot

**Comment by dms120** [comment]
The issue looks to be fixed on 0.6.2. Thanks guys!
