### ISSUE TITLE
Eth request accounts sometimes throws -> Message ignored because invalid key exchange status

### ISSUE THREAD

**Issue by bearsworth** [MetaMask/metamask-sdk#262]
**Describe the bug**
When metamask connection status goes to disconnected, you are prompted to use eth_requestAccounts again.

When you do eth_requestAccounts request after disconnection, it redirects to the Metamask Mobile Wallet and you are sent an error that says 

"Message ignored because invalid key exchange status BLt4PBvgg....key"

Followed by the app not forwarding back to your mobile app (in this case a react-native app). 

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the reactNativeDemo
2. When metamask is disconnnected, reconnect. 
3. See the error.

**Expected behaviour**

The mobile sdk should not hang and redirect back with an error rather than stay on the mobile wallet app.

**Screenshots**

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): React Native
- MetaMask SDK Version: 0.5.6
- MetaMask Mobile Version: latest?
- Browser (if relevant): n/a

**Additional context**

**Comment by dalmendray** [comment]
@bearsworth did you close this because you found a solution? I'm experiencing the same issue

**Comment by bearsworth** [comment]
> @bearsworth did you close this because you found a solution? I'm experiencing the same issue

I wasn't able to determine if it's a bug or a network issue. It does still happen sometimes when I'm testing. I would re-open the issue -> something leads me to believe they should move away from polling architecture. 

I closed it mostly because manually terminating the SDK seemed to have helped overcome the issue.  Now the issue happens that you'll get "waiting" sometimes to infinity in the mobile app...

If they have a chance, they should follow the Coinbase mobile sdk. It works effortlessly -> except right now they block send transactions for certain cases.
