### ISSUE TITLE
why sign client not redirect me to the dapp when i trigger the transaction through wallet

### ISSUE THREAD

**Issue by arbaz-meo** [MetaMask/metamask-sdk#267]
i have one doubt or maybe i m missing something

when i connect wallet by signclient its open the wallet automatically by using deep link  ### https://metamask.app.link/wc?uri=encode wcuri .
i have wc uri so i genrate deep link on connection its redirect me to dapp after connect the wallet  but when i go to trigger the transaction i have this deep link ### **https://metamask.app.link/** so its take me to the wallet but when i trigger transaction its not bring me back on dapp.

is i am missing something ???

**Comment by christopherferreira9** [comment]
Hi @arbaz-meo ! Are you able to share with us the code you're using so that we can try to help you with more context?

**Comment by christopherferreira9** [comment]
Can you please open a bug report in the [MetaMask mobile repository](https://github.com/MetaMask/metamask-mobile)?

**Comment by arbaz-meo** [comment]
new issue open here https://github.com/MetaMask/metamask-mobile/issues/6995
