### ISSUE TITLE
Expo not fully supported

### ISSUE THREAD

**Issue by EdwardHashbangGames** [MetaMask/metamask-sdk#268]
Expo not fully supported

Steps to reproduce the behaviour:
1. Create a new project with Expo
2. Follow the installation process of the metamask sdk for React Native
3. Run the project

- Latest version of Expo
- Latest version of the metamask sdk

**Comment by abretonc7s** [comment]
Hi @EdwardHashbangGames , it is possible to the use the sdk with expo on a bare project because we need to adjust the react native configuration to be compatible with ethers library.
We will in the future provide an expo plugin but it is not planned for a few weeks.
