### ISSUE TITLE
Dapp Transaction Completed event is showing in-app browser data when filtering MetaMask SDK

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#269]
### Description: 
We added "request_source" information into multiple mobile app events including "Dapp Transaction Completed" 
However when we filter request_source= SDK, we see transactions done via in-app browser from dapps that are not actually using the MetaMask SDK for connection. Somehow when we filter the SDK as request_source we see in-app browser transactions. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEFHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0e30c368619ac096976b3df77e733f2f434f5147/Screenshot%202023-08-15%20at%2012.26.40.png)

**Comment by abretonc7s** [comment]
This should have been fixed on 7.8 https://github.com/MetaMask/metamask-mobile/pull/7102
