### ISSUE TITLE
[Unity SDK] Invalid argument

### ISSUE THREAD

**Issue by haling79** [MetaMask/metamask-sdk#270]
**Describe the bug**
We are getting a TransactionHash when we make a TransactionRequest, and we are using the receipt to get the status of the transaction.

The role of the **MetaMaskEthereumRequestResultEventArgs** that your team has created is for that purpose.

However, I think passing the wrong argument when creating MetaMaskEthereumRequestResultEventArgs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Call the request function of the MetaMaskWallet by Unity SDK
2. I can't get the TransactionHash value inside the function registered as EthereumRequestResultReceivedHandler.

**Expected behaviour**
/Assets/MetaMask/Runtim/MataMaskWallet.cs : Line 842
`EthereumRequestResultReceivedHandler?.Invoke(this, new MetaMaskEthereumRequestResultEventArgs(request, data));` --> I think it should be **result** instead of **data**.

supposed to pass the result extracted from the data, which is what you think it should do, but it's passing the data itself as an argument, so the MetaMaskEthereumRequestResultEventArgs is working incorrectly.

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): Unity
- MetaMask SDK Version: 1.1.3
- MetaMask Mobile Version:
- Browser (if relevant):

**Additional context**

**Comment by christopherferreira9** [comment]
Hi @haling79 ! We are currently testing a new version of the MetaMask Unity SDK that should be ready at any time in which this will be fixed. I'll keep this issue posted

**Comment by christopherferreira9** [comment]
Hi @haling79 ! Can you please try to update the MetaMask asset to the most recent one that we just published (v1.2)?

**Comment by haling79** [comment]
@christopherferreira9 I updated to v1.2. I think this issue is completely irrelevant in this version.

**Comment by christopherferreira9** [comment]
Hi @haling79 , can you elaborate more?

**Comment by haling79** [comment]
@christopherferreira9 Sorry, updating to v1.2 fixed the issue.

**Comment by christopherferreira9** [comment]
Awesome!! I'm glad to know that!
