### ISSUE TITLE
Unity Metamask SDK V1.1.3 initialization failed On Webgl

### ISSUE THREAD

**Issue by OmarVector** [MetaMask/metamask-sdk#279]
How to produce:
Tested on unity version 2021.3.8

1. Make new unity project and set target platform to Webgl
2. Import lastest SDK and demo
3. Open the demo scene
4. Observe

The following error output are in order
<img width="846" alt="Screenshot 2023-08-18 at 15 36 48" src="https://github.com/MetaMask/metamask-sdk/assets/11194934/c8da48eb-00a3-4cc5-9f03-c271c0b76447">

1.
`MetaMask: MetaMaskUnity initialization failed
UnityEngine.Logger:LogError (string,object)
MetaMask.Logging.MetaMaskUnityLogger:LogError (object) (at Assets/MetaMask/Scripts/Logging/MetaMaskUnityLogger.cs:62)
MetaMask.Logging.MetaMaskDebug:LogError (object) (at Assets/MetaMask/Runtime/Logging/MetaMaskDebug.cs:41)
MetaMask.Unity.MetaMaskUnity:Initialize (MetaMask.Unity.MetaMaskConfig,MetaMask.Transports.IMetaMaskTransport,MetaMask.Sockets.IMetaMaskSocketWrapper) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:249)
MetaMask.Unity.MetaMaskUnity:Initialize (MetaMask.Unity.MetaMaskConfig) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:179)
MetaMask.Unity.MetaMaskUnity:Awake () (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:146)`

2.
`EntryPointNotFoundException: LSExists assembly:<unknown assembly> type:<unknown type> member:(null)
MetaMask.IO.MetaMaskWebLocalStorage.Exists (System.String key) (at Assets/MetaMask/Scripts/IO/MetaMaskWebLocalStorage.cs:72)
MetaMask.MetaMaskDataManager.LoadInto[T] (System.String key, T instance) (at Assets/MetaMask/Runtime/MetaMaskDataManager.cs:236)
MetaMask.MetaMaskWallet.LoadOrCreateSession (System.String appName, System.String appUrl, MetaMask.Cryptography.IEciesProvider eciesProvider) (at Assets/MetaMask/Runtime/MetaMaskWallet.cs:287)
MetaMask.MetaMaskWallet..ctor (MetaMask.MetaMaskDataManager dataManager, System.String appName, System.String appUrl, System.String sessionId, MetaMask.Cryptography.IEciesProvider eciesProvider, MetaMask.Transports.IMetaMaskTransport transport, MetaMask.Sockets.IMetaMaskSocketWrapper socket, System.String socketUrl) (at Assets/MetaMask/Runtime/MetaMaskWallet.cs:249)
MetaMask.Unity.MetaMaskUnity.Initialize (MetaMask.Unity.MetaMaskConfig config, MetaMask.Transports.IMetaMaskTransport transport, MetaMask.Sockets.IMetaMaskSocketWrapper socket) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:232)
UnityEngine.Logger:LogException(Exception)
MetaMask.Logging.MetaMaskUnityLogger:LogException(Exception) (at Assets/MetaMask/Scripts/Logging/MetaMaskUnityLogger.cs:69)
MetaMask.Logging.MetaMaskDebug:LogException(Exception) (at Assets/MetaMask/Runtime/Logging/MetaMaskDebug.cs:50)
MetaMask.Unity.MetaMaskUnity:Initialize(MetaMaskConfig, IMetaMaskTransport, IMetaMaskSocketWrapper) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:250)
MetaMask.Unity.MetaMaskUnity:Initialize(MetaMaskConfig) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:179)
MetaMask.Unity.MetaMaskUnity:Awake() (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:146)
`

3.
`MetaMask: MetaMaskUnity initialization failed
UnityEngine.Logger:LogError (string,object)
MetaMask.Logging.MetaMaskUnityLogger:LogError (object) (at Assets/MetaMask/Scripts/Logging/MetaMaskUnityLogger.cs:62)
MetaMask.Logging.MetaMaskDebug:LogError (object) (at Assets/MetaMask/Runtime/Logging/MetaMaskDebug.cs:41)
MetaMask.Unity.MetaMaskUnity:Initialize (MetaMask.Unity.MetaMaskConfig,MetaMask.Transports.IMetaMaskTransport,MetaMask.Sockets.IMetaMaskSocketWrapper) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:249)
MetaMask.Unity.MetaMaskUnity:Initialize () (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:170)
MetaMask.Unity.Samples.MetaMaskDemo:Awake () (at Assets/MetaMask/Samples/Main/Scripts/MetaMaskDemo.cs:46)`

4.
`EntryPointNotFoundException: LSExists assembly:<unknown assembly> type:<unknown type> member:(null)
MetaMask.IO.MetaMaskWebLocalStorage.Exists (System.String key) (at Assets/MetaMask/Scripts/IO/MetaMaskWebLocalStorage.cs:72)
MetaMask.MetaMaskDataManager.LoadInto[T] (System.String key, T instance) (at Assets/MetaMask/Runtime/MetaMaskDataManager.cs:236)
MetaMask.MetaMaskWallet.LoadOrCreateSession (System.String appName, System.String appUrl, MetaMask.Cryptography.IEciesProvider eciesProvider) (at Assets/MetaMask/Runtime/MetaMaskWallet.cs:287)
MetaMask.MetaMaskWallet..ctor (MetaMask.MetaMaskDataManager dataManager, System.String appName, System.String appUrl, System.String sessionId, MetaMask.Cryptography.IEciesProvider eciesProvider, MetaMask.Transports.IMetaMaskTransport transport, MetaMask.Sockets.IMetaMaskSocketWrapper socket, System.String socketUrl) (at Assets/MetaMask/Runtime/MetaMaskWallet.cs:249)
MetaMask.Unity.MetaMaskUnity.Initialize (MetaMask.Unity.MetaMaskConfig config, MetaMask.Transports.IMetaMaskTransport transport, MetaMask.Sockets.IMetaMaskSocketWrapper socket) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:232)
UnityEngine.Logger:LogException(Exception)
MetaMask.Logging.MetaMaskUnityLogger:LogException(Exception) (at Assets/MetaMask/Scripts/Logging/MetaMaskUnityLogger.cs:69)
MetaMask.Logging.MetaMaskDebug:LogException(Exception) (at Assets/MetaMask/Runtime/Logging/MetaMaskDebug.cs:50)
MetaMask.Unity.MetaMaskUnity:Initialize(MetaMaskConfig, IMetaMaskTransport, IMetaMaskSocketWrapper) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:250)
MetaMask.Unity.MetaMaskUnity:Initialize() (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:170)
MetaMask.Unity.Samples.MetaMaskDemo:Awake() (at Assets/MetaMask/Samples/Main/Scripts/MetaMaskDemo.cs:46)`

5.
`NullReferenceException: Object reference not set to an instance of an object
MetaMask.Unity.MetaMaskUnityEventHandler.<SetupEvents>b__61_0 () (at Assets/MetaMask/Scripts/MetaMaskUnityEventHandler.cs:62)
MetaMask.Unity.MetaMaskUnityEventHandler.SetupEvent (UnityEngine.Events.UnityEvent event, System.Func`1[TResult] sourceGetter, System.Func`1[TResult] targetGetter, System.Action`1[T] setter) (at Assets/MetaMask/Scripts/MetaMaskUnityEventHandler.cs:119)
MetaMask.Unity.MetaMaskUnityEventHandler.<SetupEvents>b__61_24 (System.ValueTuple`4[T1,T2,T3,T4] e) (at Assets/MetaMask/Scripts/MetaMaskUnityEventHandler.cs:72)
System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].ToList () (at <f72cfcff6d0f43459e18ab5c7fd30578>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <f72cfcff6d0f43459e18ab5c7fd30578>:0)
MetaMask.Unity.MetaMaskUnityEventHandler.SetupEvents () (at Assets/MetaMask/Scripts/MetaMaskUnityEventHandler.cs:72)
MetaMask.Unity.MetaMaskUnityEventHandler.Start () (at Assets/MetaMask/Scripts/MetaMaskUnityEventHandler.cs:46)
`

The lastest update is not useable on Webgl at any level.

**Comment by denistuzlak1993** [comment]
Did you find resolve for this ? I'm experiencing same issue?

**Comment by OmarVector** [comment]
> Did you find resolve for this ? I'm experiencing same issue?

Unfortunately not.

**Comment by christopherferreira9** [comment]
HI @OmarVector, @denistuzlak1993 . Can you share the player settings you're using to build?
Also we have a new version right around the corner 🚀

**Comment by OmarVector** [comment]
> HI @OmarVector, @denistuzlak1993 . Can you share the player settings you're using to build? Also we have a new version right around the corner 🚀

Hi @christopherferreira9 

No build is required. this happen inside editor when the target platform is set to Webgl

**Comment by christopherferreira9** [comment]
Hi @OmarVector ! 
Can you please try to use min version `2021.3.22` of the Unity Editor as recommended?
We are aware of the prefabs missing scripts, they are missing because they're no longer needed and we missed to remove them from the prefab itself.

**Comment by OmarVector** [comment]
> Hi @OmarVector ! Can you please try to use min version `2021.3.22` of the Unity Editor as recommended? We are aware of the prefabs missing scripts, they are missing because they're no longer needed and we missed to remove them from the prefab itself.

Its very difficult to update to this version atm. however, I by passed those errors by editing the following scripts:

\Assets\MetaMask\Scripts\IO\MetaMaskUnityStorage.cs:24 --> #if UNITY_WEBGL && !UNITY_EDITOR

\Assets\MetaMask\Scripts\Transports\Unity\MetaMaskUnityScriptableObjectTransport.cs:56 --> #if UNITY_WEBGL && !UNITY_EDITOR

The fix is from discord.

I know you guys doing terrific work.... its just take too much time to figure out whats going on.

**Comment by christopherferreira9** [comment]
Hi @OmarVector ! 
We understand that upgrading the Unity Editor version might cause issues. 
The changes you suggested are already implemented on the version we just released (`v1.2`), can you please try that version out?

**Comment by OmarVector** [comment]
> Hi @OmarVector ! We understand that upgrading the Unity Editor version might cause issues. The changes you suggested are already implemented on the version we just released (`v1.2`), can you please try that version out?

I will and report to you tomorrow max:))

Thank you:)

**Comment by OmarVector** [comment]
> Hi @OmarVector , any news about it? In the meantime a new version (1.2.0) is out. Please test it and let us know if your issue is solved. Thanks

Hi Andrea, Yes the update worked fine, sorry for late reply, I think I may replied in another thread that all good but I just forgot to reply to this thread.

thanks for follow up

**Comment by andreahaku** [comment]
@OmarVector no problem. Glad that it worked. I close this then.
