### ISSUE TITLE
[JS] On tap RPC call prevents deeplink

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-sdk#318]
**Describe the bug**
When a button has the following actions the user is not deeplinked to MM Mobile:
1. rpc call that is not supposed to deeplink like `eth_chainId`
2. rpc call for eth_sendTransaction

**To Reproduce**
1. Go to this [branch](https://github.com/MetaMask/metamask-sdk/tree/bug/deeplink-prevention)
2. spin up the nextJs example and test the two sendTransaction buttons

**Expected behaviour**
Both should deeplink to MM

**Comment by deeeed** [comment]
This should be fixed from 0.6.0

**Comment by christopherferreira9** [comment]
This needs more investigation as it is not solved in 0.6.0.

**Comment by christopherferreira9** [comment]
This has been solved with `0.7.1`.
