### ISSUE TITLE
[JS] OTP not showing in modal

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-sdk#327]
**Describe the bug**
OTP cause by mobile reconnection is not displayed in the modal

**To Reproduce**
1. Connect to dapp via QR Code
2. Kill MetaMask -> Open again
3. See issue in the OTP modal

**Expected behaviour**
OTP value is displayed

**Screenshots**

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity):
- MetaMask SDK Version:
- MetaMask Mobile Version:
- Browser (if relevant):

**Additional context**

**Comment by abretonc7s** [comment]
Fixed with https://github.com/MetaMask/metamask-sdk/pull/402
