### ISSUE TITLE
Unity SDK ExecutionEngineException

### ISSUE THREAD

**Issue by A-Feder** [MetaMask/metamask-sdk#330]
**Describe the bug**

I have a few issues with the Metamask Unity SDK in the latest version available on the Unity Asset Store.
When attempting to connect I get the log in attachment where we can see two errors :

1. Missing sprites in the MetamaskUnityUIQRImage object. In fact all UI prefabs in the Resources folder seems to be broken. This doesn't seem to be blocking and I can change the animation but I also see missing scripts in these prefabs so other elements might be missing.

2. I am getting an ExecutionEngineException that I am unable to fix.

I have followed https://docs.metamask.io/wallet/how-to/use-sdk/unity/ 

To fix these issues we tried using the SDK in this demo (https://assetstore.unity.com/packages/decentralization/demo-game-dragon-crasher-with-metamask-sdk-infura-and-truffle-249789), but with it we're still getting the same error on iOS

**To Reproduce**

1. Initialize the Metamask SDK.
2. Call MetaMask.MetaMaskWallet.Connect()
3. Check the logs joined.

**Additional context**

[IDLogExtract.txt](https://github.com/MetaMask/metamask-sdk/files/12534306/IDLogExtract.txt)

**Comment by andreahaku** [comment]
1. This should be fix with version 1.2.0. If it's not, then try a clean install please.
2. Please, make sure they are setting this from the docs "set IL2CPP Code Generation in Build Settings to Faster (smaller) builds."

Let us know. Thanks
