### ISSUE TITLE
[JS] Implement Infura API into SDK for "Read-only" Calls

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#347]
**Description:** Currently we wake MM wallet for every RPC method dapp is using through our SDK. 
This is not ideal and inflates our connect request volume. 

**Task:** Separate "Read-only" calls that don't require user confirmation from other RPC methods and add Infura API key. This will give ability to dapps to connect to network without needing the wallet. 

**Requirement:** We would like to monetise dapps using Infura via SDK differently. To be able to do this we need to add 
the header :
`Metamask-Sdk-Info: SdkVersion/1.0.2 SdkBuild/abc1234 Node/14.15.0 macOS/10.15.7
`12:20
`SdkVersion/1.0.2: `The version of the SDK (Easy for analytics purposes to have this)
`SdkBuild/abc1234:` The SDK build as a Git short hash (Useful to debug)
`Node/14.15.0: `The runtime details and its version.
`macOS/10.15.7: `The operating system details and its version
to every SDK call to Infura API. 
Every time the SDK uses the Infura API, will add this header so that they can recognise dapps using Infura API via SDK and we can create a different monetisation strategy accordingly. 

We should also track Infura API users via SDK by adding a flag to our SDK events. 
https://app.zenhub.com/workspaces/metamask-sdk-6359297a36f20292c13feca0/issues/gh/metamask/metamask-sdk/273

**Comment by abretonc7s** [comment]
Done in 7.0.0+
