### ISSUE TITLE
Metamask SDK CDN Load Problem on Pure js

### ISSUE THREAD

**Issue by kmlcnclk** [MetaMask/metamask-sdk#349]
When I try to load Metamask SDK with pure js, I am getting an error like that. Is it happening because of the metmask api or me ?

<img width="1430" alt="Screenshot 2023-09-16 at 10 37 10" src="https://github.com/MetaMask/metamask-sdk/assets/56474929/01114552-67f9-4dba-88bf-26969c7ed199">

**Comment by andreahaku** [comment]
Hi @kmlcnclk, I'll update the SDK version and make sure the link works. Thanks for reporting.

**Comment by andreahaku** [comment]
Hi @kmlcnclk, I've just updated the CDN version to 0.6.2 (latest).
It should be available at: [https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/cdn/metamask-sdk.js](https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/cdn/metamask-sdk.js)

Let us know if you still have issues. Thanks
