### ISSUE TITLE
Error: SDK state invalid -- undefined provider

### ISSUE THREAD

**Issue by glitch-txs** [MetaMask/metamask-sdk#350]
**Describe the bug**
When `getProvider` function is called inmediately it throws an error

**To Reproduce**
```ts
const MMSDK = new (await import('@metamask/sdk')).MetaMaskSDK()

const provider = MMSDK .getProvider()
```
maybe you can make it async?

**Provide environment information**
- Next.js
- "@metamask/sdk": "^0.6.2"

**Comment by christopherferreira9** [comment]
Hi @glitch-txs . Can you please add the following line between those two lines and try again?
`await MMSDK.init()`

Also, as a reference, here's our nextjs example:
https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/nextjs-demo

**Comment by ngvcanh** [comment]
Same problem

> CHÀO@glitch-txs. Bạn có thể vui lòng thêm dòng sau vào giữa hai dòng đó và thử lại không? `await MMSDK.init()`
> 
> Ngoài ra, để tham khảo, đây là ví dụ nextjs của chúng tôi: https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/nextjs-demo

Thank, working for me, I use`.then` and move `.getProvider()` inside `.then` callback. One more time, thank you.
