### ISSUE TITLE
[Bug]: On environments with reactStrictMode:active, if Metamask is not installed, it throws error instead of showing Modal

### ISSUE THREAD

**Issue by dms120** [MetaMask/metamask-sdk#370]
### SDK

Web

### Provide environment information

Local Next.JS deployment.

### MetaMask SDK Version

0.5.6

### MetaMask Mobile app Version

N/A

### Describe the Bug

Hello guys, I’m having an issue with local environments where reactStrictMode is active. (in deployed environment, it don't happen).

What happens is, when Metamask is not installed, i get the error: Error: Ethereum instance not intiialized - call Ethereum.factory first. instead of getting the modal to appear.

This is probably happening because on strictMode components are rendered twice (so SDK is also initialized twice), but since SDK works when Metamask is detected, it should also work when it's not.

I'm on version 0.5.6 but it's the same behaviour on 0.6.2.
I was able to reproduce on Next.JS example if i activate reactStrictMode.

This is not a major issue but can impact developers experience.

### Expected Behavior

Modal should open

### To Reproduce

- Go to Next.JS example and add `reactStrictMode: true` on next.config.js
- Try to connect

**Comment by christopherferreira9** [comment]
Hi @dms120 ! Can you please try with version `0.7.1`? I wasn't able to reproduce it using that version.

**Comment by christopherferreira9** [comment]
Hi @dms120 I'm closing this one assuming it has been solved. Please feel free to open it again if it still happens.

**Comment by dms120** [comment]
It seems to be fixed, thanks @christopherferreira9 and sorry for the delay.
