### ISSUE TITLE
[Bug]: Crash on Unity iOS when used with Google Admob

### ISSUE THREAD

**Issue by A-Feder** [MetaMask/metamask-sdk#373]
### SDK

Unity

### Provide environment information

Crash on Unity iOS when used with Google Admob.

Unity: 2023.1.12f1

Device information:

iPhone is 12 Pro max
OS version is 16.6.1

### MetaMask SDK Version

1.2.0

### MetaMask Mobile app Version

7.6.0

### Describe the Bug

If you create a new project, import metamask sdk and admob sdk, and proceed with iOS build, you may not be able to log in or a crash will occur.

Just remove admob sdk and it will run fine.

### Expected Behavior

Use of Google Admob in conjunction with MM Unity SDK

### To Reproduce

No exception occurs, and when testing on iPhone, a crash occurs.
The order in which the error occurs is as follows.

1. Create a new project. (Unity 2023.1.12f1)
2. import Metamask sdk .
3. Metamask sdk install, and Demo install
4. Google Admob sdk import, and AD ID settings.
5. iOS Build And Run On iPhone.
6. Crash occurs.

**Comment by christopherferreira9** [comment]
HI @A-Feder ! Can you please ask the user to try again with the last version we have released as this should be fixed there?
