### ISSUE TITLE
[JS] Integrate EIP-6963 

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#379]
### Description: 

Integrate EIP-6963, "Multi Injected Provider Discovery", into the MetaMask SDK to facilitate dapps in discovering and connecting to the MetaMask wallet when multiple EIP-1193 providers are present. EIP-6963 introduces a mechanism to discover multiple injected Wallet Providers, which is crucial when dapps aim to connect to the MetaMask wallet in an environment with multiple EIP-1193 providers.

https://eips.ethereum.org/EIPS/eip-6963

### Tasks: 
**Task 1**
1. Modify the MetaMask SDK to listen for the `eip6963:announceProvider` event and recognize the MetaMask wallet.
2. Implement the capability in the SDK to dispatch the `eip6963:requestProvider` event, prompting the MetaMask wallet to announce its presence.
3. Update the SDK to handle scenarios where multiple Wallet Providers respond to the discovery request.
4. Test the SDK to ensure dapp can discover and connect to the MetaMask wallet amidst multiple providers.
5. Update the MetaMask SDK documentation to guide dapp developers on leveraging this enhanced discovery mechanism.

**Task 2**
1. When user connects with extension to a dapp that uses the SDK, we cache this information so that after user selects the extension for the first time, user's selection persists. 
2. Add a new event that is fired whenever SDK checks user's cached info about selecting extension to connect. 
3. event name should be sdk_extension_utilized which is fired whenever extension is selected from cached choice.

**Comment by omridan159** [comment]
Added on this PR:
https://github.com/MetaMask/metamask-sdk/pull/423
