### ISSUE TITLE
[Bug]: IOS 17.0.2 can not back to Dapp automatically

### ISSUE THREAD

**Issue by wendychaung** [MetaMask/metamask-sdk#381]
### SDK

Web

### Provide environment information

IOS 17.0.2
MetaMask v7.0.1(1126)
Chrome Mobile 117.0.5938.117

### MetaMask SDK Version

"@metamask/sdk": "^0.7.1",

### MetaMask Mobile app Version

MetaMask v7.0.1(1126)

### Describe the Bug

When my iPhone's system updated to iOS 17.0.2, I used [metamask-sdk] to connect Metamask. It successfully launched my Metamask app, but I had to manually switch back to the website. In iOS 16, the app would automatically return to the website without requiring manual switching.

### Expected Behavior

After connected the wallet, it should automatically return to the website.

### To Reproduce

When using the Metamask SDK to launch the Metamask app and retrieve the account address in a mobile browser, it doesn't automatically return to the browser.

**Comment by xrdavies** [comment]
> Hi @wendychaung, yes we are aware of that and we are working on a fix on the MM mobile app side. iOS 17 broke the code the MM mobile app uses to "hide" itself and get back to the app originating the connection. Unfortunately there's no workaround for now.

Met the same issue. Is there any plan to update metamask sdk to solve this issue?

**Comment by andreahaku** [comment]
@wendychaung @xrdavies the fix has to be made on the MetaMask mobile app and we are working on it. The MM SDK is working properly.

**Comment by xrdavies** [comment]
> @wendychaung @xrdavies the fix has to be made on the MetaMask mobile app and we are working on it. The MM SDK is working properly.
> 
> You can check the issue here: [MetaMask/metamask-mobile#7165](https://github.com/MetaMask/metamask-mobile/issues/7165)

@andreahaku  That's really cool! Wait for the update! Thank you so much!

**Comment by christopherferreira9** [comment]
Closed this issue in favour of the [mobile issue](https://github.com/MetaMask/metamask-mobile/issues/7165)
