### ISSUE TITLE
[Bug]: Unity Connection issue and Unable to retrieve var balance = await nft.BalanceOf(account)

### ISSUE THREAD

**Issue by A-Feder** [MetaMask/metamask-sdk#394]
### SDK

Unity

### Provide environment information

- Unity 2022.3.9f1
- MetaMask for Unity v1.2.0
- Android MetaMask App 7.7.0

For the tests, I build the .apk and install it directly into my phone (Huawei P30 Pro). I don't go through the store.

Here is the code I am using:

```
#region ERC721
private IEnumerator LoadData(ScriptableERC721 token)
{
    yield return new WaitForTask<bool>(LoadNFT(token));
}

private async Task<bool> LoadNFT(ScriptableERC721 nft)
{
    var account = MetaMaskUnity.Instance.Wallet.SelectedAddress;
    var balance = await nft.BalanceOf(account);

    this.OwnedNFTs.Clear();

    this.addFakeHeroes();
    for (int i = 1; i <= balance; i++)
    {
        var tokenId = await nft.TokenOfOwnerByIndex(account, i);

        SpawnToken(nft, tokenId);
    }

    return true;
}

private void addFakeHeroes()
{
    this.OwnedNFTs.AddRange(HeroNFTData.GetAllBaseHeroes);
}

private void SpawnToken(ERC721PresetMinterPauserAutoId nft, BigInteger id)
{
    var tokenData = new HeroNFTData(nft, id);

    this.OwnedNFTs.Add(tokenData);
}
#endregion
```

### MetaMask SDK Version

1.2.0

### MetaMask Mobile app Version

7.7.0

### Describe the Bug

- Connecting to MetaMask inside the Unity's app works 1 time out of 5 (Android). I always need to try to connect multiple times before succeeding and even when looking at the logs I can't understand why. This problem occurs in editor when scanning the QRCode, and with deepling when on mobile.

- When testing in Unity Editor, I'm able to retrieve the NFTs but when building the game and launching it with my phone, it's still stuck at the var balance = await nft.BalanceOf(account); and using logcat won't give me any clue. There is no "wallet paused" as before, and I can't find any solution about it. 
**EDIT: this is fixed after the Minimum API Level was set to 7.0, previously set to 8.0 Oreo. But the connection issue persists**

[log_metamask_success_but_no_nfts_try1.txt](https://github.com/MetaMask/metamask-sdk/files/12829188/log_metamask_success_but_no_nfts_try1.txt)
[log_metamask_success_but_no_nfts_try2.txt](https://github.com/MetaMask/metamask-sdk/files/12829189/log_metamask_success_but_no_nfts_try2.txt)

### Expected Behavior

I expect MM to connect on the first try and the code to continue after `var balance = await nft.BalanceOf(account)` so I can retrieve NFTs owned by the linked account.

### To Reproduce

Quick video explaining the problem : https://youtu.be/8JOxNGqBcxYg

**Comment by christopherferreira9** [comment]
Hi @A-Feder  ! We are closing this issue since there hasn't been activity in it. Please feel free to open a new issue if needed.
