### ISSUE TITLE
[Bug]: TypeError: Cannot set property Headers of #<Object> which has only a getter

### ISSUE THREAD

**Issue by Maltstar** [MetaMask/metamask-sdk#419]
### SDK

Web

### Provide environment information

Firefox 118.0.1 (64-bit)
    "@metamask/sdk-react": "^0.10.0",
    "next": "13.5.6",
    "react": "^18",
    "react-dom": "^18"
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",

### MetaMask SDK Version

0.10.0

### MetaMask Mobile app Version

n/a

### How are you deploying your application? (if relevant)

Firefox 118.0.1 (64-bit)

### Describe the Bug

After creating a new next project and installing the metamask sdk and integrating the example provided in [https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/javascript/react/](url) and starting a server I get the error

```
  ⨯ node_modules/@metamask/sdk-react/dist/esm/index.js (1:741994) @ eval    

⨯ TypeError: Cannot set property Headers of #<Object> which has only a getter
```

Detailled error
```
 ✓ Compiled /page in 5.8s (451 modules)
 ⨯ node_modules/@metamask/sdk-react/dist/esm/index.js (1:741994) @ eval
 ⨯ TypeError: Cannot set property Headers of #<Object> which has only a getter
    at __webpack_require__ (/home/johnson/used/learning/NFT Talents/Dapp/github/metamask_sdk/.next/server/webpack-runtime.js:33:42)
    at eval (./app/App.tsx:7:77)
    at Object.(ssr)/./app/App.tsx (/home/johnson/used/learning/NFT Talents/Dapp/github/metamask_sdk/.next/server/app/page.js:151:1)
    at __webpack_require__ (/home/johnson/used/learning/NFT Talents/Dapp/github/metamask_sdk/.next/server/webpack-runtime.js:33:42)
    at eval (./app/page.tsx:7:62)
    at Object.(ssr)/./app/page.tsx (/home/johnson/used/learning/NFT Talents/Dapp/github/metamask_sdk/.next/server/app/page.js:162:1)
    at __webpack_require__ (/home/johnson/used/learning/NFT Talents/Dapp/github/metamask_sdk/.next/server/webpack-runtime.js:33:42)
null
```

### Expected Behavior

The frontend is connected to metamask and the metamask account is displayed

### To Reproduce

1. create a next app: `npx create-next-app@latest --typescript .` and accept all default configuration options when prompted
2. install the metamask sdk: `npm i @metamask/sdk-react`
3. replace the content of page.tsx with the example `Wrap your project with MetaMaskProvider` provided on [https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/javascript/react/](url)
4. create a file App.tsx in the app folder and copy the content of the example `Use the SDK` provided on [https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/javascript/react/](url)
5. start the server with the command `npm run dev`

**Comment by Nochao** [comment]
Hi @Maltstar sorry for the inconvenience, are you still having the same errors?

**Comment by christopherferreira9** [comment]
Hi @Maltstar ! Have you looked at the examples we provide in our repo, specifically the react example?

**Comment by christopherferreira9** [comment]
Hi @Maltstar ! We also have an example that uses nextjs, you can check it out [here](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/nextjs-demo).

**Comment by christopherferreira9** [comment]
Hi @Maltstar ! We're closing this issue but feel free to open a new one at any time.

**Comment by Maadhav** [comment]
Facing the same issue on one of my devices during the EthIndia Hackathon.

`@metamask/sdk-react` version `0.14.1`

For a very wierd reason I am not able to recreate the issue with any other device, and yet not able to fix it on my device after a lot of trying to reset the project files and all as well. It would be best if a solution can be found to fix this asap.

**Comment by Maltstar** [comment]
I switched to web3modal and I got rid of the problem.
