### ISSUE TITLE
Make it possible to connect a browser wallet in SDK-Unity-Metamask (this is especially important for desktop games)

### ISSUE THREAD

**Issue by italiano1** [MetaMask/metamask-sdk#424]
#  Feature Request - Make it possible to connect a browser wallet in SDK-Unity-Metamask (this is especially important for desktop games)

## Why it is needed - It is very inconvenient to use Metamask-SDK-Unity on a computer for desktop games, many users do not have a Metamask wallet on their phone, but there is a browser extension, it is necessary that the user can immediately connect the browser extension out of the box - this is very important for games - game brings a paid user - for example, a user costs $10 and due to the fact that he does not have a wallet, he simply cannot connect - and the user needs simplicity - if he cannot connect right away, he simply will not further figure out how to do it
If he doesn’t have a wallet on his phone, he needs to install it, then copy the phrase and write it down
If there is, he needs to remember the wallet password
And many users simply use only a computer - and for desktop games - a wallet on the phone is not needed

### Code sample - Such implementations already exist and automatically determine where the user is coming from.

This is very important for us as game developers and those who use SDK-Unity from Metamask! We want to give users the opportunity to easily register and connect their wallet. We will wait for the implementation of this function. Thank you!

**Comment by MartyMari** [comment]
Hello @italiano1,
Thanks for this suggestion, it will be taken up for consideration

**Comment by A-Feder** [comment]
Hey @italiano1 , is this feature request for MM extension?

**Comment by italiano1** [comment]
Hi, @A-Feder we want SDK-Unity-Metamask to immediately allow the desktop version to connect a wallet in the extension

Those. the user clicked Connect Skale blockchain and the Connection Extension should open to him - not the QR code

if from a computer - then the extension
if from the phone - then the QR code

or so that he can manually select

this functionality needs to be added to the SDK

because the SDK cannot work with the browser extension - you need to add this

**Comment by christopherferreira9** [comment]
Hi @italiano1 ! We are working on this new feature and we expect to have it released by mid December.

**Comment by italiano1** [comment]
Cool!

**Comment by italiano1** [comment]
Hi @christopherferreira9 maybe the task has already been implemented and you can connect the wallet for Unity-Metamask-SDK via a browser? We are looking forward to the implementation of this task

**Comment by yanis-falaki** [comment]
Any update/eta on when this would be implemented?

**Comment by christopherferreira9** [comment]
Hi all! Version `1.3.0` is now available in the asset store and it already includes the extension support for WebGL :D

**Comment by italiano1** [comment]
Thank you very much for these wallet improvements!
