### ISSUE TITLE
[MOBILE] Implement Additional Pop-Up Screen on Mobile App

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#438]
### Description:
iOS 17 update prevents navigating user back and forth between two apps. Until we find a better solution, we should add an additional UI to the userflow asking user to manually go back to the dapp.

### Design: 
https://www.figma.com/file/piME5CaTYUz07Gc7Ye7c22/Deeplinking--SDK?type=design&node-id=1762-35444&mode=design&t=fmRJ3O2bHINLME1a-0

**Comment by omridan159** [comment]
Implemented on this PR:
https://github.com/MetaMask/metamask-mobile/pull/7754
