### ISSUE TITLE
[Bug]: deepLink not working at all and universalLink opens MetaMask app but never asks for permission

### ISSUE THREAD

**Issue by Vingator** [MetaMask/metamask-sdk#439]
### SDK

Unity

### Provide environment information

Unity 2022.3.10f1
Platforms: iOS/Android
Unity ThirdWeb SDK: v3.3.1
MetaMask version provided by the ThirdWebSDK 

### MetaMask SDK Version

Latest (as stated by ThirdWeb team)

### MetaMask Mobile app Version

Latest (as stated by ThirdWeb team)

### Describe the Bug

Connecting via the `universalLink` generated in `OnMetaMaskConnectRequest(string universalLink, string deepLink)`, it opens the Metamask app but never prompts for user's permission to connect (the same behavior happens when trying to scan the QR Code).
When I use the `deepLink` nothing happens, it won't even open the app. 

### Expected Behavior

Redirecting to  the  `deepLink` or `universalLink`  should open the Metamask app and ask for permission to link the wallet.

### To Reproduce

The setup basically consists of MonoBehaviour script that implements IMetaMaskUnityTransportListener

```
public void OnMetaMaskConnectRequest(string universalLink, string deepLink) {
    Application.OpenURL(universalLink); //Opens MM but never asks for permission
//    Application.OpenURL(deepLink); // Nothing happens 
}
```

Here you  can see the code in details https://github.com/thirdweb-dev/unity-sdk/blob/main/Assets/Thirdweb/Core/Scripts/WalletsUI/MetamaskUI.cs

I asked ThirdWeb guys which version of Metamask SDK they were using, they only said, the latest one.

Here is a link for a simple project that reproduces the mentioned behavior:

https://github.com/Vingator/MetamaskThirdWebAuth

**Comment by christopherferreira9** [comment]
Hi @Vingator ! We're about to release a new version of the Unity SDK (`v1.2.2`) where this should be fixed. Can you please try with the new version?
