### ISSUE TITLE
[Bug]: Can not connect using MetaMask SDK on iOS 

### ISSUE THREAD

**Issue by MananTank** [MetaMask/metamask-sdk#456]
### SDK

Web

### Provide environment information

iOS 17, iPhone 13, any browser

### MetaMask SDK Version

@metamask/sdk-react@0.10.1

### MetaMask Mobile app Version

7.9.1

### What browser are you using? (if relevant)

Safari

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Can not connect to MetaMask app on iOS (iPhone) in any browserthe 

### Expected Behavior

wallet should be connected the wallet

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://mm-sdk-cra.vercel.app/

### To Reproduce

This issue can be replicated on the official [create-react-app demo](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/create-) as well

I've cloned the above demo and deployed it here -> https://mm-sdk-cra.vercel.app/ 

## Steps to replicate the issue

* Visit https://mm-sdk-cra.vercel.app/  on iPhone in any browser 
* click on connect button

**Comment by christopherferreira9** [comment]
Hi @MananTank ! 
We just [merged](https://github.com/MetaMask/metamask-mobile/pull/7714) a lot of stability issues on the wallet side that will be available on version `7.11.0`. I will let you know once it is published so that you can try on your side. 
Thank you for reporting.

**Comment by christopherferreira9** [comment]
I'm closing this for now but feel free to reopen a new issue if it still persists.
