### ISSUE TITLE
[JS] - Connection delay on JS SDK

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#49]
## **User story**

As a user, I want to be able to connect to a desktop dapp using my mobile wallet app. 

When developers test to connect to MetaMask mobile app from their desktop dapp they see delays on connection. On Android connection takes even longer than iOS. 

## User insights

This has been reported by dapps testing the JS SDK. The behaviour happens both on iOS and Android. After user clicks on "connect" button on the dapp and is being redirected to the MetaMask app, the connect button on the MM app doesn't appear for a long time. There is a very visible delay, which we should work on resolving as soon as possible. Fandom (tiktok NFT marketplace) removed our SDK and reverted back to WalletConnect until we resolve this issue.

## **Steps to reproduce**

1. Click on “Connect” on your desktop dapp.
2. Scan the QR code via your mobile app. 
3. Wait for connection modal to be displayed on mobile app. 
4. It takes long time on both iOS and Android to display connect modal on MM mobile app. 

## **Screenshots**

Video links - https://www.notion.so/Connection-delay-on-JS-SDK-6f27ead403f34dd5972338f2e2d2f1c0#949c05aacf65418b8657518c3f17b6be

## **Task/Expected Behavior**

We should investigate the root cause of this delay on our JS SDK. 

- Does it happen due to our communication layer?
- Is there anything we can update with our [socket.io](http://socket.io) servers that could prevent this delay?
- Why is Android having a longer connection time than iOS?
- Can we isolate this behaviour for certain OS version/App version/Device/Location?

## Acceptance **criteria**

JS SDK to provide a fast and successful connection for desktop dapps on both iOS and Android MM mobile app. (less than 3 seconds)

**Comment by abretonc7s** [comment]
Fixed with session persistence and loading UX.
