### ISSUE TITLE
[Docs] Update node.js docs to include .init() or .connect()

### ISSUE THREAD

**Issue by BrettCleary** [MetaMask/metamask-sdk#492]
The docs for node.js integration are missing this info

> the issue happens because you are not initializing the sdk correctly.
> Please check the examples folder or initialize the connection with the following:
> 
> const sdk = new MetaMaskSDK(options);
> const accounts = await sdk.connect(); // or await sdk.init() then you can call eth_requestAccounts or any other methods.
> The error you receive is because you are requesting an rpc method before the sdk has time to initialize and set the provider.

Reference
https://github.com/MetaMask/metamask-sdk/issues/409#issuecomment-1767965927
https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/javascript/nodejs/

**Comment by christopherferreira9** [comment]
Hi @BrettCleary ! Docs are currently being updated and these instructions will be added.
