### ISSUE TITLE
[Bug]: undefined chainId

### ISSUE THREAD

**Issue by DanielTech21** [MetaMask/metamask-sdk#515]
### SDK

React-Native

### Provide environment information

1. MetaMask App Version - 11.3.0

2. What browser and browser version are you using? - Chrome V 118.0.5993.117

3. Link to GH repository with the code to reproduce the issue - https://github.com/jimCCW/metamask-sdk-test. Due to some privacy issues, I can't show the actual project code, but I created this using the same env setup, and the code samples are also getting from the example.

4. Exact steps to reproduce the issue - Run the code and press the connect button to connect your metamask. Once you connect, you will see the chainId is undefined. But when you change the network, it will show the correct chainId

5. Expected Behaviour - Should show chainId when wallet connected.

6. Attach any relevant screenshots and Logs - Attached the screenshot

7. Your GitHub handle - jimCCW

### MetaMask SDK Version

0.10.1

### MetaMask Mobile app Version

11.3.0

### What browser are you using? (if relevant)

Chrome V 118.0.5993.117

### Describe the Bug

Run the code and press the connect button to connect your metamask. Once you connect, you will see the chainId is undefined. But when you change the network, it will show the correct chainId

### Expected Behavior

Once run the code and press the connect button to connect MetaMask wallet then the chainID should show.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/jimCCW/metamask-sdk-test

### To Reproduce

![MetamaskSDK_ChainId_Undefined_Issue](https://github.com/MetaMask/metamask-sdk/assets/145437274/9bb30f6e-82ad-4f36-ab85-be338c516e28)

**Comment by christopherferreira9** [comment]
Hi @DanielTech21 .
This should be fixed by now. Can you please try using the latest SDK version.
Please feel free to open a new issue if it still persists.
