### ISSUE TITLE
[Bug]: Metamask SDK always creates two (conflicting) instances on instantiation

### ISSUE THREAD

**Issue by Sap333** [MetaMask/metamask-sdk#538]
### SDK

Web

### Provide environment information

NodeJS v20.9.0
webpack 5.89.0
@metamask/providers 10.2.1
@metamask/sdk 0.4.2

### MetaMask SDK Version

0.4.2

### MetaMask Mobile app Version

Doesn't matter

### What browser are you using? (if relevant)

Chrome 119.0.6045.159

### Describe the Bug

If not injected Metamask wallet is detected and the extension is absent, then SDK creates two conflicting instances of itself.
There are TWO modal windows (with CSS class "css-1h80o1p"), two internal connections, two of everything.
And there are some internal conflicts (probably even serious because I see that some resources are not created as the result) in the SDK as well. I see them in the debugger, but I didn't dig there.
And once again - the SDK's constructor is called once, but somehow it creates two copies of internal objects.

### Expected Behavior

There must be one instance.

### To Reproduce

Call the next code in Chrome when no Metamask extension is installed (or the extension is installed but is not enabled for the page):
```
        this.MMSDK = new MetaMaskSDK({
            dappMetadata:{ name:"MyApp", url:document.location.origin},
            injectProvider:true,
            forceRestartWalletConnect:true,
            checkInstallationImmediately:true,
            enableDebug:false,
            openDeeplink:(originalDeepLink:string)=>{ document.location.href = originalDeepLink; }
        });
```
Wait until the dialogue window is displayed (the one that offers to install an extension). Look are DOM, there will be two modal windows (two DIV-elements with CSS-class "css-1h80o1p"). Also look into the debugging console and see messages regarding conflicts with some SDK's internal resource allocation.

**Comment by christopherferreira9** [comment]
Hi @Sap333 ! Can you please try using the latest version of the SDK `0.12.3`? In the meantime, as a reference, can you try our [nextJs example dapp](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/nextjs-demo) and confirm if it also happens there?

**Comment by christopherferreira9** [comment]
Can you also clarify which package manager you're using?

**Comment by christopherferreira9** [comment]
Hi @Sap333 we're going to close this issue due to inactivity. Please feel free to open a new issue if it still persists.
