### ISSUE TITLE
[Bug]: There is no way to know that the SDK instantiated a link with a mobile application on a mobile platform

### ISSUE THREAD

**Issue by Sap333** [MetaMask/metamask-sdk#539]
### SDK

Web

### Provide environment information

NodeJS v20.9.0
webpack 5.89.0
@metamask/providers 10.2.1
@metamask/sdk 0.4.2

### MetaMask SDK Version

0.4.2

### MetaMask Mobile app Version

7.10.0 (1187)

### What browser are you using? (if relevant)

Android / Chrome

### Describe the Bug

Once you instantiated an SDK object on mobile (Android) browser, and it created and opened a deep link to the application, the received provider object stuck on a first command forever.

### Expected Behavior

Seems that it must complete the requests once a connection to wallet is created. Or, and that better, it must reject/fail any calls if connection is not created yet. 

### To Reproduce

Let's say we do something like this:
```
const MMSDK = new MetaMaskSDK({
    dappMetadata:{ name:"MyApp", url:document.location.origin},
    injectProvider:true,
    forceRestartWalletConnect:true,
    checkInstallationImmediately:true,
    enableDebug:false,
    openDeeplink:(originalDeepLink:string)=>{ document.location.href = originalDeepLink; }
});
let resolve:((v:any)=>void)|undefined;
setTimeout( ()=>resolve!(undefined), 0 );
await new Promise( (_resolve)=>{resolve=_resolve;} );
const web3Provider = const MMSDK!.getProvider(); // << HOW TO KNOW WHEN THIS MUST BE CALLED?!!
await web3Provider.request({ method: 'eth_requestAccounts' }); // << OR HOW TO KNOW WHEN THIS MUST BE CALLED?
```

By the way, that's the way [recommended](https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/javascript/pure-js/) by the documentation.
Then the mobile application (on the same device)  pops up and asks if you really want to connect the wallet to the web page. Agree and switch back to the web browser. You "web3Provider.request" call hugs forever, even if I see that internally SDK set up a connection to the wallet application.

How may a web DApp developer know when they can get/use a provider and/or use it after they instantiated an SDK object?

**Comment by christopherferreira9** [comment]
Hi @Sap333 ! Can you please try using the latest version of the SDK 0.12.3? In the meantime, as a reference, can you try our [NodeJS example dapp](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/nodejs) and confirm if it also happens there?

**Comment by Sap333** [comment]
For some reason 0.4.2 is the version that is been installed by a package manager by default but I'll try 0.12.3 ASAP.

**Comment by christopherferreira9** [comment]
Hi @Sap333 we're about to release version `v0.14.0` of the sdk. Can you please try with that one instead?

**Comment by christopherferreira9** [comment]
Hi @Sap333 we're going to close this issue due to inactivity. Please feel free to open a new issue if it still persists.
