### ISSUE TITLE
[JS] - React Native connection delays on Android

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#54]

**Comment by prtk418** [comment]
I am facing this problem rn, check out recorded video here - https://drive.google.com/file/d/1JTqmMt7-SpFjXrl8XIRMR9ztIejPZhDq/view?usp=share_link

**Comment by abretonc7s** [comment]
Android issues were due to extremely slow encryption on RN < 0.71 .
Should now be fixed with latest examples.
