### ISSUE TITLE
[Bug]: MetaMask SDK keeps trying to post to /debug even with enableDebug: false

### ISSUE THREAD

**Issue by ale-ben** [MetaMask/metamask-sdk#574]
### SDK

Web

### Provide environment information

- Node v20.8.0
- next 14.0.3  
- react 18.2.0
- @metamask/sdk 0.14.1

### MetaMask SDK Version

@metamask/sdk 0.14.1

### MetaMask Mobile app Version

-

### How are you deploying your application? (if relevant)

Developing with default next configuration

### Describe the Bug

After instantiating MetaMaskSDK the extension tries to post on "http://localhost:3000/debug" and throws a POST error (see attached images).
Note that enableDebug is set to false in  MetaMaskSDK options.

I tried both `@metamask/sdk` and `@metamask/sdk-react` and the problem persists.

```
import MetaMaskSDK from '@metamask/sdk';

const MMSDK = new MetaMaskSDK({
		enableDebug: false,
		dappMetadata: {
			name: 'Teal Owl'
		}
	});
```
![Screenshot 2023-11-30 at 12 48 48](https://github.com/MetaMask/metamask-sdk/assets/17771264/cae54da3-7c92-4005-9dd5-d2a802313de6)
![Screenshot 2023-11-30 at 12 49 44](https://github.com/MetaMask/metamask-sdk/assets/17771264/c83d58de-a947-47bb-bfbd-23bb7ce37a62)

### Expected Behavior

if enableDebug is set to false, the extension should not try to post to /debug

### To Reproduce

1. Generate a react/next template app
2. install `@metamask/sdk`
3. Generate a component as follows:
```
'use client';

import MetaMaskSDK from '@metamask/sdk';

const MetamaskComponent = () => {
	const MMSDK = new MetaMaskSDK({
		enableDebug: false,
		dappMetadata: {
			name: 'Teal Owl'
		}
	});

	const connect = async () => {
		console.log('connect');
		// MMSDK.connect().then((accounts) => {
		// 	WagmiConnect();
		// });
	};

	return (
		<div>
			Hello world
		</div>
	);
};
``` 
4. Check browser console, after each reload two POST errors appear. Trying to implement `connect` would generate a lot more of POST errors.

**Comment by ale-ben** [comment]
Forgo to mention, the browser is chrome

**Comment by ruslanmsq** [comment]
Just fount that even If I sett debug false in MMProvider *see code below*

When I take a look at config - `const { debug } = useSDKConfig()` I see `debug: true`



`@metamask/sdk-react": "^0.14.1"`


```tsx
 <MetaMaskProvider
        debug={false}
        sdkOptions={{
          enableDebug: false,
          dappMetadata: {
            name: metadata.name,
            url: metadata.url,
          },
          // Other options
        }}
      >
        <WagmiConfig client={client}>{children}</WagmiConfig>;
      </MetaMaskProvider>
```

**Comment by andreahaku** [comment]
> Hi @christopherferreira9
> 
> Just found that even If I disabled debug in `MetaMaskProvider`, and I take a look at config by `const { debug } = useSDKConfig()` There is still `debug: true`
> 
> `@metamask/sdk-react": "^0.14.1"`
> 
> ```tsx
>  <MetaMaskProvider
>         debug={false}
>         sdkOptions={{
>           enableDebug: false,
>           dappMetadata: {
>             name: metadata.name,
>             url: metadata.url,
>           },
>           // Other options
>         }}
>       >
>         <WagmiConfig client={client}>{children}</WagmiConfig>;
>       </MetaMaskProvider>
> ```

Thanks a lot. Sorry for the slow reply but the team has been on holiday. We are just back and working on replicating the issue.

**Comment by christopherferreira9** [comment]
This is fixed by https://github.com/MetaMask/metamask-sdk/pull/604 and will be available on the next release.
