### ISSUE TITLE
[Bug]: Balance only shows in MetaMask Button (not in Active Networks)

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-sdk#578]
### SDK

Web

### Provide environment information

This issue is happening in a React application being viewed in Chrome browser, I assume it also would show up in any browser the same.

### MetaMask SDK Version

0.14.1

### MetaMask Mobile app Version

N/A

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

When using the Provider + MetaMask Button as instructed in the docs. 

The Balance does show up in the MetaMask Button:
<img width="1042" alt="Screenshot 2023-12-01 at 12 05 07 PM" src="https://github.com/MetaMask/metamask-sdk/assets/4899480/fda93d44-665b-4ca4-81d3-68e72b979675">

### Expected Behavior

The Balance should be visible in both of those components (Button and Active Networks)

### To Reproduce

Follow regular docs instructions to setup the MetaMask Button and check the Active Networks balance

**Comment by omridan159** [comment]
Hey @httpJunkie,

This has been fixed in this PR [https://github.com/MetaMask/metamask-sdk/pull/593](url).
 It'll be in the next release
