### ISSUE TITLE
[Bug]: build for iOS does not start

### ISSUE THREAD

**Issue by AwsomeSauci** [MetaMask/metamask-sdk#579]
### SDK

Unity

### Provide environment information

Unity 2022.3.14

### MetaMask SDK Version

1.2.2

### MetaMask Mobile app Version

1.2.2

### Describe the Bug

I installed the latest version of MetaMask SDK into an empty Unity project. I made all project settings and built a build for IOS. After installing it on an iPhone, the application doesn't launch. IOS version 17.

### Expected Behavior

I need the application to open and connect to MetaMask

### To Reproduce

Create a Unity project
Install Metamask SDK and sample
Build for iOS

**Comment by andreahaku** [comment]
@AwsomeSauci @tovchenyk we have a fix and it'll be part of 1.3.0 that's going to be released in the coming days.
