### ISSUE TITLE
[JS] - SDK React Native Kit

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#58]
Description
We are creating React Native Kit which will contain libraries and UI designs for developers to integrate and use JS SDK easier.

Task/Expected Behavior
Add wagmi library to the React Native Kit
Add ethers.js library to the React Native Kit
Add UI designs to the React Native  Kit. - https://www.figma.com/file/piME5CaTYUz07Gc7Ye7c22/Deeplinking--SDK?node-id=0%3A1&t=TmfRvbS967COX40L-0
Deadline - 30th March

**Comment by m1heng** [comment]
Any progress yet? The all in one SDK doesn't work so well in RN project
