### ISSUE TITLE
[Bug]: DeepLink not connet to metamask App IOS 

### ISSUE THREAD

**Issue by AwsomeSauci** [MetaMask/metamask-sdk#580]
### SDK

Unity

### Provide environment information

Unity 2022.3.14

### MetaMask SDK Version

1.2.2

### MetaMask Mobile app Version

1.2.2

### Describe the Bug

when you click on the connection button, the deeplink window is displayed, but then nothing happens. IOS 16

### Expected Behavior

After click connect, open Metamask App

### To Reproduce

Build Unity metamask demo for IOS.
Launch app on IOS 16
CLick connect button

**Comment by andreahaku** [comment]
@AwsomeSauci we close this as we didn't have any feedback and additional info from you. Feel free to re-open it if the issue still persist. Thanks
