### ISSUE TITLE
[Bug]: Unable to restore the last wallet connection when refresh the page in mobile chrome browser

### ISSUE THREAD

**Issue by waynechan-bw** [MetaMask/metamask-sdk#583]
### SDK

Web

### Provide environment information

Platform: NextJS
MetaMask SDK Version: "@metamask/sdk-react": "^0.12.2"
MetaMask Mobile Version: v7.12.2(1224)

### MetaMask SDK Version

0.12.2

### MetaMask Mobile app Version

v7.12.2(1224)

### What browser are you using? (if relevant)

Android Chrome 119.0.6045.194

### Describe the Bug

We are using the latest version of nextjs-demo in example packages, the example using `@metamask/sdk-react version ^0.12.2`.
Once we started the nextjs app with `next run dev`, the app is started in port 3334. 
If we open the app in desktop chrome browser and connect our wallet with metamask, we can get the wallet detail like this
![image](https://github.com/MetaMask/metamask-sdk/assets/116139537/15fd2acf-7ab9-4760-96e6-aa646a836da4)

![289733361-0b92f229-dacc-4566-85b2-45b83205c909](https://github.com/MetaMask/metamask-sdk/assets/116139537/6df67f5d-2bac-42e9-a159-dde313a5200a)
Now if we refresh the page, we can still restore from the last wallet connect without need to ask the client to connect again. 

However, when we do the same thing in mobile chrome browser. After we connect the wallet with MetaMask app and refresh the page. The connection lost and user need to click the connect button again the restore the last connection.
![WhatsApp Image 2023-12-12 at 11 17 58](https://github.com/MetaMask/metamask-sdk/assets/116139537/e578b38f-4aff-49c7-b5f7-d11fd7b6d381)

After we refresh the page:
![WhatsApp Image 2023-12-12 at 11 17 58 (1)](https://github.com/MetaMask/metamask-sdk/assets/116139537/64abbc63-cb73-4ddf-a9b5-3094fb184e74)

### Expected Behavior

the last wallet connection should be restore when user refresh the page in mobile too

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/nextjs-demo

### To Reproduce

Run the nextjs-demo app
Click connect button, the wallet connection is established. 
Refresh the page, the last wallet connection is lost.

**Comment by christopherferreira9** [comment]
Hi @waynechan-bw ! This is how it Is supposed to work. To fully disconnect and reset the SDK state you should tap the "terminate" button.
On the desktop browser it works as you stated since it saves the preference to use the MetaMask extension and so it is able to resume the current session. Because on mobile you need to go through the socket itself you're not able to resume the session unless you actively want to.
Let us know if you have any other questions we might be able to answer.
