### ISSUE TITLE
[Bug]: "@metamask/sdk-react": "^0.14.1" connectivity error in react native

### ISSUE THREAD

**Issue by pratul-mindfire** [MetaMask/metamask-sdk#596]
### SDK

React-Native

### Provide environment information

 "@metamask/sdk-react": "^0.14.1",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "eciesjs": "^0.4.6",
    "ethers": "^5.7.2",
    "node-libs-react-native": "^1.2.1",
    "react": "18.2.0",
    "react-native": "0.73.1",
    "react-native-background-timer": "^2.4.1",
    "react-native-get-random-values": "^1.10.0",
    "react-native-randombytes": "^3.6.1",
    "react-native-url-polyfill": "^2.0.0"

### MetaMask SDK Version

 "@metamask/sdk-react": "^0.14.1",

### MetaMask Mobile app Version

7.12.2

### Describe the Bug

I am trying to use  "@metamask/sdk-react": "^0.14.1", lib in react native cli 
![1703074264105](https://github.com/MetaMask/metamask-sdk/assets/104986454/9bc1e630-445e-4e3e-9573-89ef049359bd)
but i am getting this error - 

Error: While trying to resolve module `@metamask/sdk-react` from file `/Users/pratul/Desktop/MyProject/App.tsx`, the package `/Users/pratul/Desktop/MyProject/node_modules/@metamask/sdk-react/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/pratul/Desktop/MyProject/node_modules/@metamask/sdk-react/index`. Indeed, none of these files exist:

  * /Users/pratul/Desktop/MyProject/node_modules/@metamask/sdk-react/index(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /Users/pratul/Desktop/MyProject/node_modules/@metamask/sdk-react/index/index(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/Users/pratul/Desktop/MyProject/node_modules/metro/src/node-haste/DependencyGraph.js:294:17)
    at Object.resolve (/Users/pratul/Desktop/MyProject/node_modules/metro/src/lib/transformHelpers.js:176:21)
    at Graph._resolveDependencies (/Users/pratul/Desktop/MyProject/node_modules/metro/src/DeltaBundler/Graph.js:476:35)
    at Graph._processModule (/Users/pratul/Desktop/MyProject/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/Users/pratul/Desktop/MyProject/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 5)
    at async Graph._processModule (/Users/pratul/Desktop/MyProject/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/pratul/Desktop/MyProject/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
    at async Promise.all

### Expected Behavior

I should work in react native cli and user can connect to metamask.

Note - i also tried to run your demo example app - https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeDemo , but i also get same error
![1703074264105](https://github.com/MetaMask/metamask-sdk/assets/104986454/13c4d09a-55c4-47fc-91f8-32bc9db65e5e)

### To Reproduce

interate "@metamask/sdk-react": "^0.14.1", lib in react native cli and run the app

**Comment by Cognacy** [comment]
Hi @pratul-mindfire are you able to resolve this error?

**Comment by sheepmiee** [comment]
Copying the file "index.js" from sdk-react -> dist -> esm directory to the sdk-react folder can temporarily solve this issue

**Comment by pratul-mindfire** [comment]
@sheepmiee  thanks for your response, i got rid of this error but there is an issue that web socket connection breaks automatically and the application behave in random manners(e.g.- sometime we send the transaction but it will not open confirm bottomsheet in metamask app and somtime it works). Some time we call the connect method it open the metamask app but it does not show the connect button and sometime it works
![IMG-20231221-WA0010](https://github.com/MetaMask/metamask-sdk/assets/104986454/60aaa30b-5187-4794-9565-4d254450c65f)

**Comment by sheepmiee** [comment]
> @sheepmiee thanks for your response, i got rid of this error but there is an issue that web socket connection breaks automatically and the application behave in random manners(e.g.- sometime we send the transaction but it will not open confirm bottomsheet in metamask app and somtime it works). Some time we call the connect method it open the metamask app but it does not show the connect button and sometime it works ![IMG-20231221-WA0010](https://private-user-images.githubusercontent.com/104986454/292173520-60aaa30b-5187-4794-9565-4d254450c65f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzAzNDMsIm5iZiI6MTcwMzIzMDA0MywicGF0aCI6Ii8xMDQ5ODY0NTQvMjkyMTczNTIwLTYwYWFhMzBiLTUxODctNDc5NC05NTY1LTRkMjU0NDUwYzY1Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwNzI3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDg2YmNhZjBjOTkxYWMxZTRjMDY5ZjgwNGM1ZDRlZjViYjE4ZmZiMTgwOTI2N2ViYzdmNGJiNWRjZmU1YmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9Hrbq5TAkiXi-JCTqyxJ1jSgrllz1DYqgqbOzhY4JXU)

Yes, the performance of MetaMask's SDK on mobile is very unstable right now. I don't know how to handle it, and I'm considering giving up

**Comment by pratul-mindfire** [comment]
@sheepmiee How could I get information when this will be resolved from Metamask team? Can you please drop a message here in this issue as it will be open?

**Comment by andreahaku** [comment]
@pratul-mindfire @sheepmiee this should be solved with the next update as there's already a fix for it. In the meantime, can you please try with the Expo example [here]( https://github.com/MetaMask/metamask-sdk/blob/main/packages/examples/expo-demo/package.json) as it should be fixed there.

**Comment by NoisyBoyII** [comment]
@andreahaku @pratul-mindfire  I am trying the expo example but its not running getting error "Bundle URL not present" .. try to run device iPhone 11.. may be some issue ... will check again

**Comment by omridan159** [comment]
The issue has been addressed and resolved in the following Pull Request:
https://github.com/MetaMask/metamask-sdk/pull/614.

Please attempt to run it again now, as it should now be functioning correctly.

**Comment by christopherferreira9** [comment]
Closing this issue as it was already fixed in https://github.com/MetaMask/metamask-sdk/pull/614
