### ISSUE TITLE
[Bug]: SDK::connectWithExtensionProvider() can't request accounts error RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by david-dacruz** [MetaMask/metamask-sdk#607]
### SDK

Web

### Provide environment information

Localhost with vue: "^3.2.13"

### MetaMask SDK Version

^0.14.1

### MetaMask Mobile app Version

none

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

localhost

### Describe the Bug

When I click connect from the package examples with vue I get and error
`SDK::connectWithExtensionProvider() can't request accounts error RangeError: Maximum call stack size exceeded`

### Expected Behavior

I would expect to log in successfully

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

none

### To Reproduce

cd into packages/examples and then in the vue app
npm run serve and try to connect

**Comment by christopherferreira9** [comment]
Hi @david-dacruz ! I just tried to replicate this issue but was unsuccessful. I've tried connecting with both MetaMask Extension and MetaMask mobile wallet. Can you please check if it also happens on our [deployed version of the vuejs dapp](https://metamask.github.io/metamask-sdk/deployments/45.0.0/packages/examples/vuejs/dist/)?

**Comment by david-dacruz** [comment]
Thanks for checking it out @christopherferreira9 I just tried and I do get the same error 

<img width="834" alt="Screenshot 2024-01-10 at 14 06 16" src="https://github.com/MetaMask/metamask-sdk/assets/10786611/6ac9c3ca-1646-47b7-b068-7a4e237861dc">

**Comment by christopherferreira9** [comment]
That is very weird. I don't seem to get any issues when connecting. Can you please check your MetaMask extension version? 
![Screenshot 2024-01-10 at 14 27 00](https://github.com/MetaMask/metamask-sdk/assets/104831203/2f979bae-5343-4cf1-a26b-c19bbe803c75)

**Comment by david-dacruz** [comment]
Ok i installed metamask in a profile with no other extensions on this profile it worked so it seems there's a conflict with one of my extensions.

**Comment by christopherferreira9** [comment]
Hi @david-dacruz ! Thank you for testing! I'm curious as to which extension was causing the incompatibility. Would you mind sharing some of the extensions you have installed in your browser to try on my side?

**Comment by andreahaku** [comment]
@david-dacruz we close this for inactivity. Feel free to re-open it if you are still having issues. Thanks
