### ISSUE TITLE
Enable Sticky Sessions

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#623]

**Comment by abretonc7s** [comment]
https://consensyssoftware.atlassian.net/jira/software/c/projects/INFRA/boards/528?selectedIssue=INFRA-1666

**Comment by abretonc7s** [comment]
https://consensyssoftware.atlassian.net/jira/software/c/projects/INFRA/boards/528?selectedIssue=INFRA-1666
