### ISSUE TITLE
[Bug]: Closing / clicking outside of MetaMask modal doesn't throw an error

### ISSUE THREAD

**Issue by androidsixteen** [MetaMask/metamask-sdk#651]
### SDK

Web

### Provide environment information

N/A

### MetaMask SDK Version

0.14.1 via Wagmi 2.3.1

### MetaMask Mobile app Version

N/A

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

See [Wagmi issue](https://github.com/wevm/wagmi/issues/3500) which they suggested flagging here

when I don't have the MetaMask desktop app enabled, upon connect(), the MetaMask connector shows a modal similar to Coinbase Wallet that has the option to scan a QR code using their mobile app

if I click out of this however, Wagmi doesn't throw an error the same way it does for Coinbase Wallet. This is because the MetaMask SDK [doesn't expose any info](https://github.com/MetaMask/metamask-sdk/blob/b725cfc3dd3edb196685f326f7a935d5b09b4092/packages/sdk/src/ui/InstallModal/InstallModal-web.ts#L86) when the modal is closed

### Expected Behavior

When the modal is closed, MM SDK should throw an error that Wagmi can pick up / devs can use to update state in applications (eg. show an error saying "You rejected the connection, please try again")

### To Reproduce

- do not have MetaMask browser extension installed/enabled
- connect to MetaMask from application
- at this point, you should see the modal to scan and connect with MM mobile
- click outside or close the modal
- Metamask doesn't throw an error

**Comment by andreahaku** [comment]
Hi @androidsixteen, we are looking on supporting this update of the UX and add an error when the first connection modal is dismissed. Thanks for reporting.

**Comment by androidsixteen** [comment]
Thanks for circling back on this @andreahaku - I appreciate the quick fix!

**Comment by andreahaku** [comment]
@androidsixteen  it's now in our to do list and will most likely be part of next release
