### ISSUE TITLE
[Wagmi] Recommendation on using direct RPC method instead of Wagmi's on iOS due to iOS limitation

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#655]
Wagmi repo: https://github.com/wevm/wagmi/blob/main/docs/shared/connectors/metaMask.md?plain=1#L14
500ms timeout limit on Safari with deeplink connections. Safari cancel deeplinks if it doesn't happen in 500ms.

**Comment by omridan159** [comment]
Updated on this PR:
https://github.com/wevm/wagmi/pull/3543
