### ISSUE TITLE
[Wagmi] Create a Wagmi test dapp optimised for both mobile and desktop

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#659]
Use Infura API for read-only calls

**Comment by omridan159** [comment]
There were some issues with Wagmi's implementation of the metaMask connector during this task, which are now being investigated in order to resolve them

**Comment by omridan159** [comment]
This task is **blocked** until this PR is merged on Wagmi:
https://github.com/wevm/wagmi/pull/3602

**Comment by omridan159** [comment]
TODO:
Add Smart Contract Interaction to the Example
