### ISSUE TITLE
[Bug]: emotion/react should be marked as peer dependencies

### ISSUE THREAD

**Issue by toniocodo** [MetaMask/metamask-sdk#699]
### SDK

Web

### Provide environment information

Using `metamask/sdk` as a transitive dependency of `@rainbow-me/rainbowkit` and `@wagmi/connector` 

### MetaMask SDK Version

0.14.3

### MetaMask Mobile app Version

na

### Describe the Bug

When using metamask sdk in an application that already brings `@emotion/core` in its dependencies (using MUI), browser emits the following warning
![image](https://github.com/MetaMask/metamask-sdk/assets/13216617/567de54b-749f-4b82-9e7a-9a59d3c861dc)

A quick `pnpm why @emotion/react` shows that this package is brought by `@metamask/sdk-install-modal-web`
![image](https://github.com/MetaMask/metamask-sdk/assets/13216617/fc34bff9-51fc-4c2e-9cc1-e11b97738016)

The package is referenced as dependency in the [package.json](https://github.com/MetaMask/metamask-sdk/blob/872c3de30e208728838f3f211fbaadb859bd2a42/packages/sdk-install-modal-web/package.json#L48)

### Expected Behavior

The package `@metamask/sdk-install-modal-web` should mark `@emotion/react` as peer dependency in order to use the same version than the host application and thus remove the warning.

### To Reproduce

- Install `@metamask/sdk-install-modal-web` and `@emotion/react`
- Use the sdk within the app

**Comment by andreahaku** [comment]
@toniocodo did you try the latest version of the SDK 0.17.1 and check if you still have this dependency issue? This should be fixed in this last version. Thanks

**Comment by toniocodo** [comment]
I'm not directly using the sdk, it's been pulled by rainbow-kit through the MM connector, I guess I'll have to wait until they actually update to your fixed version.
In the meantime, I tried to force the use of version 0.17.1, it doesn't seem to exist on npm, are you sure about the version?
![image](https://github.com/MetaMask/metamask-sdk/assets/13216617/b2d5f5c0-b206-4507-a046-11407da9fc9e)

**Comment by andreahaku** [comment]
> I'm not directly using the sdk, it's been pulled by rainbow-kit through the MM connector, I guess I'll have to wait until they actually update to your fixed version. In the meantime, I tried to force the use of version 0.17.1, it doesn't seem to exist on npm, are you sure about the version?

I suggested you to use 0.17.1 but now there's also 0.17.2.

**Comment by toniocodo** [comment]
I can't find `0.17.1` or `0.17.2`, latest published version on npm is `0.17.0`, am I missing something?

**Comment by andreahaku** [comment]
> I can't find `0.17.1` or `0.17.2`, latest published version on npm is `0.17.0`, am I missing something?

which version gets installed if you do a `yarn add @metamask/sdk` or `npm install @metamask/sdk`?
