### ISSUE TITLE
Notify Developer of connection modal status change

### ISSUE THREAD

**Issue by abretonc7s** [MetaMask/metamask-sdk#705]

**Comment by abretonc7s** [comment]
There are different modal status to connect to mobile wallet:
- Initial connection
- <img width="463" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDJMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e16e05dce9d870be9989ca34a9dfa84964ce77e/image.png" alt="image.png" />

- Reconnection modal
<img width="494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--733774548dcbbaa0250951c0657dd53f9a5dd5cb/image.png" alt="image.png" />

Currently the initial connection modal, when a user closes it or click outside, it will fully reset the connection and create connection to a new channelId next time it opens.

The issue is with closing (or clicking outside) of the re-connection modal. It currently doesn't disconnect the connection and doesn't inform the user that a connection task is still pending.

Solution:
Disconnect the active connection on the reconnection modal but keep the channelId (different than terminate which destroys the channelId).

**Comment by christopherferreira9** [comment]
Not applicable as of Nov 4th.
