### ISSUE TITLE
Not redirecting back to app after successful connect

### ISSUE THREAD

**Issue by miroosama** [MetaMask/metamask-sdk#71]
After successfully linking to metamask and establishing a connection `MetaMask: Connected to chain with ID "0x1".` I am no longer redirected back to my app

**To Reproduce**
Steps to reproduce the behaviour:
- Create instance of MetaMaskSDK, getProvider, and request accounts
- Metamask deeplink prompted on request account -> click connect
- Successfully connected account but are not redirected back to app 

**Expected behaviour**
Redirected back to app after successful connection

- React Native
- MetaMask SDK Version: 0.1.0
- MetaMask Mobile Version: 6.3.0

**Comment by andreahaku** [comment]
Hi, @miroosama,
we are aware of that and we already have a fix in place for the MM mobile app here: https://github.com/MetaMask/metamask-mobile/pull/6201

That hopefully should be part of v6.5 release.
Thanks for reporting.

**Comment by miroosama** [comment]
> Hi, @miroosama, we are aware of that and we already have a fix in place for the MM mobile app here: [MetaMask/metamask-mobile#6201](https://github.com/MetaMask/metamask-mobile/pull/6201)
> 
> That hopefully should be part of v6.5 release. Thanks for reporting.

Awesome! thank you for the prompt reply

**Comment by andreahaku** [comment]
This should be fixed with updated version of MM mobile app.
Thanks for reporting.
