### ISSUE TITLE
configure Socket server Dashboard 

### ISSUE THREAD

**Issue by abretonc7s** [MetaMask/metamask-sdk#711]

**Comment by abretonc7s** [comment]
SDK prod is deployed with new metrics https://metamask-sdk-socket.metafi.codefi.network/metrics

Definition of Ready:
Pending https://consensyssoftware.atlassian.net/browse/INFRA-1681

**Comment by Dejavu0709** [comment]
> SDK prod is deployed with new metrics https://metamask-sdk-socket.metafi.codefi.network/metrics
> 
> Definition of Ready: Pending https://consensyssoftware.atlassian.net/browse/INFRA-1681

Is there a version for China that can access the https://metamask-sdk-socket.metafi.codefi.network/ ？

**Comment by abretonc7s** [comment]
We currently don't have any China specific endpoints

**Comment by christopherferreira9** [comment]
Done and it's currently undergoing refactoring.
