### ISSUE TITLE
bundle size optimization

### ISSUE THREAD

**Issue by abretonc7s** [MetaMask/metamask-sdk#721]
For a complete reference see https://www.notion.so/metamask-consensys/e3cb7482a492445fb0665334e53a1795?v=34d0d322d99f493aaf7b1ac58ed1c87b&p=2ad5c5b5b4fb48139490ff3e446a7859&pm=s

**acceptance criteria:**

- sdk size reduced by at least 30%
- github pipeline configured to automatically check bundle size
    - emit warning if it exceeds a certain size

**Comment by omridan159** [comment]
Available on version `0.16.0` of the SDK
