### ISSUE TITLE
[Bug]: metamask app is not opening on release mode ANDROID

### ISSUE THREAD

**Issue by goldenmoon67** [MetaMask/metamask-sdk#729]
### SDK

React-Native

### Provide environment information

Android 13
Metamask app v7.16.0

### MetaMask SDK Version

metamask-android-sdk:0.2.1

### MetaMask Mobile app Version

v7.16.0

### Describe the Bug

In the debug mode everything is ok. I can connect my app to metamask and I can get the user wallet address but In the release mode it goes to metamask app and metamask close suddenly go back to my app. I cant request to connect metamask. I cant solve it.

### Expected Behavior

When I click to connect metamask button from my app => it should open the metamask app and it ask to connect to my app. If user click to connect it should go back to my app automatically and I should able to get user wallet address

### To Reproduce

    try {
        val ethereum = Ethereum(this)
        val dapp = Dapp("myApp", "https://my.net")

        ethereum.connect(dapp) { connectResult ->
            when (connectResult) {
                is RequestError -> {
                    result.error("ERROR", "Ethereum connection error: ${connectResult.message}", null)
                }
                else -> {
                    val chainId = ethereum.chainId
                    result.success(mapOf("walletAddress" to connectResult.toString(), "chainId" to chainId))
                }
            }
        }
    } catch (e: Exception) {
        result.error("UNEXPECTED_ERROR", "An unexpected error occurred: ${e.localizedMessage}", null)
    }

**Comment by andreahaku** [comment]
@goldenmoon67 Please open the issue on `metamask-android-sdk` repo [here](https://github.com/MetaMask/metamask-android-sdk/issues) but in the meantime we suggest you to update to the latest version of the Android SDK that is 0.5.2. Thanks

**Comment by embCrypto** [comment]
I am facing this issue with @web3-onboard/metamask version 2.1.2
