### ISSUE TITLE
[JS] Reduce the bundle size of the JS SDK

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#737]
### Tasks

- prevent duplicate imports of packages
- leverage peer dependencies
- check if we can rewrite `sdk-install-modal-web`  without `react/react-dom`  dependencies
    - pure DOM manipulation since ui can be overwritten by user.
- Replace package by direct implementation
    - identify package imported for a single utility call that could be implemented directly.

### Acceptance Criteria

- sdk size reduced by at least 30% —> Goal is < 100KB
- github pipeline configured to automatically check bundle size
    - emit warning if it exceeds a certain size
   
https://www.notion.so/metamask-consensys/SDK-Bundle-Size-optimization-2ad5c5b5b4fb48139490ff3e446a7859

**Comment by ian-os** [comment]
Is this complete? We're still seeing massive bundle sizes when using wagmi + metamask SDK connector. gzip size is close to 500KB.

![CleanShot 2024-11-01 at 08 45 08@2x](https://github.com/user-attachments/assets/f38f02cc-86d6-4d89-bc88-46c3a5411bfa)
