### ISSUE TITLE
[Mobile] Enable deeplink connection support in MetaMask mobile app

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#741]
### Description: 
Upgrade the MetaMask Mobile app to handle deep link communications from iOS dapps. Enable the iOS MetaMask app to accept connections, exchange public keys, and communicate securely with dapps using deep link-based messages, enhancing the overall speed and reliability of transactions and interactions.

### Task: 

- Support for the `mmsdk` action forwarding everything to the sdk deeplinking communication service
- Create the `sdk deeplinking communication` service that will replicate the same feature of the other two communication layer that the MM mobile app already supports: socket.io and Android IPC
- Add to MM mobile app the ability to parse deep link URLs for connection requests and extract necessary parameters.
- Handle incoming encrypted messages from dapps and decrypting them using the exchanged public keys.
- Prompt the user the confirmation screen to accept or deny the connection request from the Dapp.
- Encrypt responses and sending them back to the dapp via deep links, completing the secure communication loop.

**Comment by bearsworth** [comment]
It would be hugely better if you guys move in the direction of deep links alone. I am a bit new but I new to looking at the beta SDK, but the previous SDK had a lot of connection issues which were probably unnecessary. The app would sporadically lose connection and you'd have to keep restarting it.

**Comment by andreahaku** [comment]
> It would be hugely better if you guys move in the direction of deep links alone. I am a bit new to looking at the beta SDK, but the previous SDK had a lot of connection issues which were probably unnecessary. The app would sporadically lose connection and you'd have to keep restarting it.

I suggest you to take a look at the latest version as a lot of improvements have been made lately in terms of stability. A deep link based communication is under development for iOS SDK and should be out soon. On Android iOS we already have a direct connection between the mobile dapp using it and the MM mobile app using IPC AIDL.

**Comment by bearsworth** [comment]
> > It would be hugely better if you guys move in the direction of deep links alone. I am a bit new to looking at the beta SDK, but the previous SDK had a lot of connection issues which were probably unnecessary. The app would sporadically lose connection and you'd have to keep restarting it.
> 
> I suggest you to take a look at the latest version as a lot of improvements have been made lately in terms of stability. A deep link based communication is under development for iOS SDK and should be out soon. On Android iOS we already have a direct connection between the mobile dapp using it and the MM mobile app using IPC AIDL.

Thanks for the response, you replied to one of my threads before, but I'm having a bit of issue with Metamask Demo with expo, there is an error it keeps throwing about storage. Could you help me out with that by chance?

**Comment by bearsworth** [comment]
> > > > It would be hugely better if you guys move in the direction of deep links alone. I am a bit new to looking at the beta SDK, but the previous SDK had a lot of connection issues which were probably unnecessary. The app would sporadically lose connection and you'd have to keep restarting it.
> > > 
> > > 
> > > I suggest you to take a look at the latest version as a lot of improvements have been made lately in terms of stability. A deep link based communication is under development for iOS SDK and should be out soon. On Android iOS we already have a direct connection between the mobile dapp using it and the MM mobile app using IPC AIDL.
> > 
> > 
> > Thanks for the response, I'm developing in react native so hoping iOS support comes fast please! You replied to one of my threads before, but I'm having a bit of issue with Metamask Demo with Expo React Native, there is an error it keeps throwing about storage. Could you help me out with that by chance? It's in your project as an expo demo example. I don't understand why it throws this error despite working in the background on a clean install.
> 
> Please open an issue so that we can follow you better. In any case we have an [expo demo](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/expo-demo) in the `examples` folder that I suggest you to try first. Thanks

I opened an issue and you actually responded to it.
[Bug]: Expo react native demo throw storage error with DEMO example and no changes #771

It's #771 using the most recent expo demo which you linked. There is an issue I get where storage error is thrown.
You replied once but never got back.

**Comment by andreahaku** [comment]
> I opened an issue and you actually responded to it. [Bug]: Expo react native demo throw storage error with DEMO example and no changes #771
> 
> It's #771 using the most recent expo demo which you linked. There is an issue I get where storage error is thrown. You replied once but never got back.

Ok added back to our bug triage and we'll review this Monday and have someone work on it :) Thanks
