### ISSUE TITLE
When library "metamask-react-native-sdk" is ready for use? 

### ISSUE THREAD

**Issue by minhDaiVatek** [MetaMask/metamask-sdk#749]
i want to use the library for sign-in for react native and Flutter framework.

i tried to run my project as flowing like this link, but it's not working
Link: https://docs.metamask.io/wallet/how-to/use-sdk/react-native

And then i tried the example, but it still not working
Link: https://docs.metamask.io/wallet/how-to/use-sdk/react-native#:~:text=React%20Native%20example

**Comment by bearsworth** [comment]
The new beta sdk and this older one are different. You are looking at the older sdk I think.

**Comment by christopherferreira9** [comment]
Hi all! We've recently developed a new react native SDK and you can find it [here](https://github.com/MetaMask/metamask-sdk/tree/main/packages/sdk-react-native). Documentation is not yet ready but you can already follow the readme to get started.
