### ISSUE TITLE
[Bug]: Can’t keep the connection betweeen metamask and the app

### ISSUE THREAD

**Issue by mtr1012** [MetaMask/metamask-sdk#762]
### SDK

React-Native

### Provide environment information

The bug happened with the latest react native dapp example.

### MetaMask SDK Version

"@metamask/sdk-react": "^0.14.2"

### MetaMask Mobile app Version

Latest

### Describe the Bug

I'm running the react native dapp example and see the app can't keep the connection between the metamask wallet and the app. I need to connect the wallet everytime I have a new session on the app (restart the app, open from quit state...) 

### Expected Behavior

The app can keep the connection with metamask wallet until I disconnect it.

### To Reproduce

- Buid and run the react native dapp example.
- Connect to metamask wallet.
- Restart the app and you will see the previous connection disappeared.

**Comment by andreahaku** [comment]
@mtr1012 we just updated the react [native example demo](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeDemo) but if you are trying to do direct calls (RPC calls that don't need an interaction with the MM mobile wallet) you also need to provide an Infura API key. More information can be found [here](https://docs.metamask.io/wallet/how-to/make-read-only-requests/).

**Comment by christopherferreira9** [comment]
Hi @mtr1012 ! We haven't heard back from you so we're closing this issue but please feel free to open a new issue on this repository.
