### ISSUE TITLE
react-native ReferenceError: Property 'MessageEvent' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by ugened47** [MetaMask/metamask-sdk#77]
**Describe the bug**

Hi! I'm having a problem while connecting my RN dapp to metamask-mobile stoped working with sdk `0.1.0` after client has automatically updated to `6.3.0` from store and I believe upgrade sdk to `0.2.0` can help me in this situation. However, upgrading sdk version from `0.1.0` to `0.2.0` react native crashes with message: `ReferenceError: Property 'MessageEvent' doesn't exist, js engine: hermes`

**To Reproduce**
Steps to reproduce the behaviour:
1. Upgrade `@metamask/sdk` from 0.1.0 to 0.2.0

**Expected behaviour**
Works without problems

**Screenshots**
![telegram-cloud-photo-size-2-5337172846343999719-y](https://user-images.githubusercontent.com/9214135/233456857-cb44f075-0368-488c-b13d-b7701ef8cd8d.jpg)

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): React-Native
- MetaMask SDK Version: 0.2.0
- MetaMask Mobile Version: 6.3.0

**Comment by abretonc7s** [comment]
Hi @ugened47 ,  could you please try to update sdk to 0.2.0 ?
We have an example of integration in https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeTSApp and a new PR will soon be merged with more updated examples.

**Comment by ugened47** [comment]
> Hi @ugened47 ,  could you please try to update sdk to 0.2.0 ?
> We have an example of integration in https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeTSApp and a new PR will soon be merged with more updated examples.

Sorry, I could be misleading. The above error occurs with @metamask/sdk 0.2.0.

**Comment by abretonc7s** [comment]
Could you provide an example of how you instantiate the sdk?

**Comment by ardasatata** [comment]
any news?

**Comment by prtk418** [comment]
Facing the same issue

**Comment by andreahaku** [comment]
we should be able to update the SDK to fix those RN related issues later today or tomorrow. We'll let you know when the updated version will be available on npm. Thanks

**Comment by abretonc7s** [comment]
Hi @ugened47 , sdk version 0.2.2 has been published as well as the examples dapp to work with latest RN version.

**Comment by prtk418** [comment]
@abretonc7s Just to confirm - Is this the updated doc for integration - https://docs.metamask.io/wallet/how-to/use-sdk/react-native/

**Comment by ardasatata** [comment]
> @abretonc7s Just to confirm - Is this the updated doc for integration - https://docs.metamask.io/wallet/how-to/use-sdk/react-native/

It's still the old `0.1.0` example tho, 
you can find the new example in the repo itself here: https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeDemo

**Comment by prtk418** [comment]
> > @abretonc7s Just to confirm - Is this the updated doc for integration - https://docs.metamask.io/wallet/how-to/use-sdk/react-native/
> 
> It's still the old `0.1.0` example tho, you can find the new example in the repo itself here: https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeDemo

Thanks for sharing this, is there a document where I can check about integration to already running app

**Comment by ugened47** [comment]
@abretonc7s Thank you. This error is gone. However started facing other bugs after upgrading to 0.2.2.

i.e. this piece of code stopped working:

```
  await ethereum.request({ method: 'eth_requestAccounts' });

  const signer = provider.getSigner();

  const { chainId } = await provider.getNetwork();
  
    if (chainId === EthereumChainId) {
     const ObjectERC20 = new ethers.Contract(
       Config.ERC20_ADDRESS_OBJECT,
       ABI_ERC20_GOERLI,
       signer
    );
    return ObjectERC20;
    ...
```

Interaction stops on getNetwork() call. Nothing returned back, neither value nor error, so now not able to process any interactions with contracts.
