### ISSUE TITLE
[Bug]: checkInstallationImmediately not properly working

### ISSUE THREAD

**Issue by ammirator-administrator** [MetaMask/metamask-sdk#770]
### SDK

Web

### Provide environment information

browser, local environment, with react @metamask/sdk-react: 0.16.0

### MetaMask SDK Version

0.16.0

### MetaMask Mobile app Version

latest

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

local

### Describe the Bug

If checkInstallationImmediately: false is marked as FALSE it should not open the browser popup till the connect call is triggered
What happens in the last version of this extension is once the <MetaMaskProvider /> React provider is mounted even with checkInstallationImmediately: false It oppens the connect modal which is not correct it should open only when connect is called
This is not user friendly at the moment

### Expected Behavior

Connect popup should appear only when connect is called

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

none

### To Reproduce

<MetaMaskProvider
      sdkOptions={{
        // For some reason it opens the popup instantly even tho it should not
        checkInstallationImmediately: false,
      }}
    >

**Comment by andreahaku** [comment]
@ammirator-administrator we are not able to reproduce this issue. Can you please try in a "clean" environment like an incognito tab and see if it still happens? Also we have updated the SDK version to 0.17.1 and we suggest you to get the latest version for more bug fixes and features.

**Comment by ammirator-administrator** [comment]
@andreahaku 
Seems that after updating the version the bug is gone
Thanks
