### ISSUE TITLE
[Bug]: Expo react native demo throw storage error with DEMO example  and no changes

### ISSUE THREAD

**Issue by bearsworth** [MetaMask/metamask-sdk#771]
### SDK

React-Native

### Provide environment information

Mac os / ios testing. 

### MetaMask SDK Version

0.17.1

### MetaMask Mobile app Version

Latest

### Describe the Bug

If you simply install the demo, the demo will throw an error that says:

[StorageManagerWeb: getPersistedChannelConfig()] Can't find existing channel config [ReferenceError: Property 'localStorage' doesn't exist] once you try to 'connect'. 

### Expected Behavior

Something is wrong with your async storage or possibly files used. 

### To Reproduce

Simply download the example and click 'connect' and there will show an error for the storage manager.
[StorageManagerWeb: getPersistedChannelConfig()] Can't find existing channel config [ReferenceError: Property 'localStorage' doesn't exist]

I think there is something wrong with async storage or its usage in the sdk.

**Comment by bearsworth** [comment]
Also in the react-native and expo examples, why is there a file called storage manager under 'src'. What is the point of this file if nothing points to it?

**Comment by andreahaku** [comment]
@bearsworth can you please check again with the latest updated version of the example Expo app in the repo. Thanks

**Comment by bearsworth** [comment]
> @bearsworth can you please check again with the latest updated version of the example Expo app in the repo. Thanks

Yeah it is the current one I'm using and for some reason that issue occurs. I currently use a downgraded version of metamask since I cannot understand what is causing the issue. 

Can you explain what the StorageManagerRN.ts file is under src for?

**Comment by bearsworth** [comment]
It also throws this error:
Possible Unhandled Promise Rejection (id: 3):
ReferenceError: Property 'localStorage' doesn't exist
ReferenceError: Property 'localStorage' doesn't exist

**Comment by Hamzakhann** [comment]
I am also getting same error in my react native app

**Comment by bearsworth** [comment]
> I am also getting same error in my react native app

Yeah had a feeling something is wrong here. Example shouldn't throw storage errors.

**Comment by SongJiha** [comment]
I think the next line needs to be added in DEMO example at App.tsx 

```
storage: {
                    enabled: true,
                    storageManager: new StorageManagerRN()
                }
```

**Comment by ram4444** [comment]
Same error here. Mine is on the android. 

Besides, after clicking the connect button, it can switch to the Metamask app. But after entering the password, it is not able to switch back. 
When I check the logcat, I found the await sdk?.connect() has never returned

**Comment by christopherferreira9** [comment]
Solved by https://github.com/MetaMask/metamask-sdk/pull/824

**Comment by DrFemzy** [comment]
Having the same issue with Nextjs 14![Image](https://github.com/user-attachments/assets/cc626745-e948-4078-90ca-f5d2a6f7f014)
