### ISSUE TITLE
[Bug]: Unable to connect to wallet 

### ISSUE THREAD

**Issue by Dejavu0709** [MetaMask/metamask-sdk#772]
### SDK

Unity

### Provide environment information

Unity Sdk
Internet in China(use vpn)
Android Game 

### MetaMask SDK Version

1.3.1

### MetaMask Mobile app Version

7.16.0

### Describe the Bug

Use the latest unity metamask sdk to build a unity game to connect. you can jump to metamask, but it is always connecting and cannot be connected. It has always been like this
![20240318-145006](https://github.com/MetaMask/metamask-sdk/assets/71498147/cde2df60-a4f0-4a6e-a4a6-98513a959d67)

I think maybe the vpn cause the problem？
But our massive Chinese users must use vpn to open metamask,  but if the sdk cannot use vpn, how to resolve it....

### Expected Behavior

Connect to metamask

### To Reproduce

Use the latest unity metamask sdk to build a unity game to connect
The internet is in China, and use the vpn

**Comment by christopherferreira9** [comment]
Hi @Dejavu0709 ! We are aware of this issue and we are currently exploring a solution that will unblock all connectivity issues coming from China.

**Comment by christopherferreira9** [comment]
Hi! I'm closing this issue for the time being as we don't currently have an estimate deadline for the delivery of a workaround.
