### ISSUE TITLE
[Bug]: metamask-sdk can't detect EIP-6369 correctly

### ISSUE THREAD

**Issue by Chi-AnTai** [MetaMask/metamask-sdk#777]
### SDK

Web

### Provide environment information

metamask browser extension
trust wallet browser extension
metamask sdk

### MetaMask SDK Version

0.17.2

### MetaMask Mobile app Version

web browser extension 11.12.2

### What browser are you using? (if relevant)

Chrome 122.0.6261.129

### Describe the Bug

When I try to use metamask SDK to solve multi browser wallet (Metamask + trust wallet) issue, the metamask SDK MMSDK.getProvider() will return the trust wallet as provider instead of metamask wallet.

I think the problem is the EIP-6963 info is not match.
1. [the name is `MetaMask Main` in SDK](https://github.com/MetaMask/metamask-sdk/blob/58324d0ccd2f4b4e29c0dee110c04b373e3346e5/packages/sdk/src/constants.ts#L16)
2. the EIP-6963 event shows `MetaMask` 
<img width="409" alt="image" src="https://github.com/MetaMask/metamask-sdk/assets/28552580/05b40b28-38df-47e8-9f8c-e39b9986696f">

3.[and SDK require the two name are equal](https://github.com/MetaMask/metamask-sdk/blob/58324d0ccd2f4b4e29c0dee110c04b373e3346e5/packages/sdk/src/utils/eip6963RequestProvider.ts#L43)
4. [after step 3 fail, the SDK will use isMetaMask to check the provider is metamask or not, and the trust wallet provier's property isMetaMask=true](https://github.com/MetaMask/metamask-sdk/blob/58324d0ccd2f4b4e29c0dee110c04b373e3346e5/packages/sdk/src/utils/get-browser-extension.ts#L35)

### Expected Behavior

I expect the metamask SDK can return the metamask provider when I call MMSDK.getProvider() when I have multiple browerse wallet

### To Reproduce

1. Install metamask browser extension
2. install trust wallet browser extension
3. check the provider return by MMSDK.getProvider()

**Comment by christopherferreira9** [comment]
Hi @Chi-AnTai ! We are now releasing a [patch](https://github.com/MetaMask/metamask-sdk/pull/788) to update the name properly. Thank you for letting us know!
