### ISSUE TITLE
[Bug]: Metamask SDK cannot find metamask browser extension

### ISSUE THREAD

**Issue by GustavoRSSilva** [MetaMask/metamask-sdk#778]
### SDK

Web

### Provide environment information

"@metamask/sdk-react": "0.14.2"
"react": "18.2.0"
"next": "13.5.6"
Metamask browser extension version 11.12.2

### MetaMask SDK Version

0.14.2

### MetaMask Mobile app Version

7.16.0

### What browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

AWS, k8s, argocd

### Describe the Bug

Metamask sdk cannot find the metamask broswer extension even though it is installed and default to the mobile version.

![Screenshot 2024-03-20 at 15 05 27](https://github.com/MetaMask/metamask-sdk/assets/8384988/d6719cfa-6546-448a-b85d-c27aae0b1420)
![Screenshot 2024-03-20 at 15 06 07](https://github.com/MetaMask/metamask-sdk/assets/8384988/8e45672a-1a88-426f-ba0a-64bcfb401fe5)

### Expected Behavior

If metamask browser extendion is installed, use that extension instead of the mobile.extension

### To Reproduce

Start a nextJs version 13.5.6, install the metamask react-sdk 0.14.2

On the _app.ts  import metamask , create the following SDK options, and set the provider
`import { MetaMaskProvider } from '@metamask/sdk-react';
`

`const sdkOptions = {
  useDeeplink: false,
  autoConnect: {
    enable: false,
  },
  checkInstallationImmediately: false,
  dappMetadata: {
    name: 'MetaMask Activity',
    url: typeof window !== 'undefined' && window.location.origin,
  },
  logging: {
    developerMode: false,
  },
  storage: {
    enabled: true,
  },
  i18nOptions: {
    enabled: true,
  },
};`

Return the provider
`
<MetaMaskProvider debug={false} sdkOptions={sdkOptions}>
            <Component {...pageProps} />
      </MetaMaskProvider>
 `
    
    
   Now create a hook using metamask SDK and called the SDK in the Home.ts

`
   import { useSDK } from '@metamask/sdk-react';

export const useMetaMaskSDK = () => {
  const { provider } = useSDK();

  const getCurrentChainId = async (): Promise<string> => {
    return (await provider.request({ method: 'eth_chainId' })) as string;
  };

  const switchNetwork = async (chainId: string) =>
    await provider.request({
      method: 'wallet_switchEthereumChain',
      params: [{ chainId }],
    });

  const requestAccounts = async (): Promise<string[]> => {
    console.info('Calling eth_requestAccounts...');
    return await provider.request({ method: 'eth_requestAccounts' });
  };

  const requestWalletPermissions = async () => {
    console.info('Calling wallet_requestPermissions...');
    return await provider.request({
      method: 'wallet_requestPermissions',
      params: [{ eth_accounts: {} }],
    });
  };

  return {
    provider,
    getCurrentChainId,
    switchNetwork,
    requestAccounts,
    requestWalletPermissions,
  };
};
`

**Comment by christopherferreira9** [comment]
Hi @GustavoRSSilva !
The screenshots attached show that the SDK is detecting the extension as the button you see on the SDK dialog says `Connect With MetaMask Extension`. If the SDK would fail to detect the extension it would say `Install MetaMask Extension`. 
For the time being we always display the QRCode to connect with MetaMask mobile first. Will discuss internally the possibility of making this adaptable.
