### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ZengJun-cloud** [MetaMask/metamask-sdk#78]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/52198079/233535998-305ad703-b38a-46ad-8e83-127745499cde.png">

**Comment by abretonc7s** [comment]
Please provide additional information on the steps that lead you to this error?

**Comment by ZengJun-cloud** [comment]
Hi @abretonc7s 
- MetaMask SDK Version: 0.2.0
- Node Version: 12.22.12

**Comment by ZengJun-cloud** [comment]
> @ZengJun-cloud you need to update to at least node 14 to build it. Let us know if this fixes. Thanks

The same error  with node 16.20.0

**Comment by abretonc7s** [comment]
Hi @ZengJun-cloud , we have updated the sdk to 0.2.2 as well as the examples dapp.
Please try with the latest version or provide us with the exact reproductible steps.

**Comment by ZengJun-cloud** [comment]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/52198079/235046465-480bcfdf-f070-428f-bec4-9219c797bcab.png">
updated the sdk to 0.2.2 , and use node 16.20.0

**Comment by abretonc7s** [comment]
Unfortunately, we are unable to help if you don't provide us with a repository to reproduce the issue.

**Comment by ehsaneona** [comment]
any update?

**Comment by ehsaneona** [comment]
Any Update?

**Comment by ZengJun-cloud** [comment]
I'm sorry for not replying in time. I will continue to try when I have time and close this issue first.
