### ISSUE TITLE
[Bug]: sdk is not initialized after MetaMaskSDK.init() call

### ISSUE THREAD

**Issue by Flammae** [MetaMask/metamask-sdk#784]
### SDK

Web

### Provide environment information

MacOS 14.3.1 (23D60)

### MetaMask SDK Version

^0.18.1

### MetaMask Mobile app Version

NA

### Describe the Bug

sdk is not initialized after MetaMaskSDK.init() call. After checking the code, I believe the problem is the missing `await` before initializeMetaMask() call at: https://github.com/MetaMask/metamask-sdk/blob/b0117b371f5c029e07efe1bf46dcd5f4f90b67bf/packages/sdk/src/sdk.ts#L271

### Expected Behavior

sdk should be initialized by the time alert is fired

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vitejs-vite-tnwrvm?file=src%2Fmain.ts%3AL2&terminal=dev

### To Reproduce

Please check the main.ts file in the provided demo

**Comment by christopherferreira9** [comment]
Hi @Flammae ! You shouldn't need to call `sdk.init()` as it it initialised automatically when creating an SDK instance but doing so should not cause any issue.
To fix your example all you need to do is to get the initial accounts with:
```
document.querySelector('button')!.addEventListener('click', () => {
  import('@metamask/sdk')
    .then(({ MetaMaskSDK }) => {
      return new MetaMaskSDK({
        dappMetadata: {
          name: 'Hello world',
          url: window.location.href,
        },
      });
    })
    .then((sdk) => {
      return sdk.connect();
    })
    .then((accounts) => {
      // after accepting the connection this should contain a list of Accounts
      console.log(accounts);
    })
    .catch((e) => {
      console.log(e.error);
    });
});
```

Hopefully this solves your issue.
