### ISSUE TITLE
[Bug]: deeplink connection already joined

### ISSUE THREAD

**Issue by abretonc7s** [MetaMask/metamask-sdk#787]
### SDK

Web

### Provide environment information

Local env using devnext but can be reproduced on any other js based env.

### MetaMask SDK Version

0.18.2

### MetaMask Mobile app Version

7.19.0

### Describe the Bug

dapp tries to reconnect to socket server while a previous connection exists
![image](https://github.com/MetaMask/metamask-sdk/assets/107169956/d7f66b4a-4181-4dbb-ac83-aca5228b3a1a)
![image](https://github.com/MetaMask/metamask-sdk/assets/107169956/be9da9c5-1f10-4072-a305-fe12c16f0da2)

### Expected Behavior

Properly reconnect when coming back from the wallet after a deeplink

### To Reproduce

Steps to reproduce:
- connect via deeplink (not universal links!)
- wait for at least 30sec on the wallet before to come back to the dapp
- dapp seems to re-create a connection while it is already joined

**Comment by christopherferreira9** [comment]
Non-applicable with the next version of the SDK.
