### ISSUE TITLE
[Bug]: connectAndSign is not available in pure JavaScript.

### ISSUE THREAD

**Issue by HGZ-20** [MetaMask/metamask-sdk#793]
### SDK

Web

### Provide environment information

windows and Android

### MetaMask SDK Version

0.17.2

### MetaMask Mobile app Version

Latest

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

no

### Describe the Bug

```html

<head>
    ...
    <script src="https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/cdn/metamask-sdk.js"></script>
    <script>
        async function connect() {
    const sdk = await new MetaMaskSDK.MetaMaskSDK({
      useDeepLink: false,
      dappMetadata: {
        name: "Pure JS example",
        url: window.location.host,
      },
      enableAnalytics: true,
      checkInstallationImmediately: false,
    });

    await sdk?.init()

    const sig = await sdk?.connectAndSign({msg: "hello"});
    </script>
    ...
</head>

```
It was found to be unusable, showing the following error
![image](https://github.com/MetaMask/metamask-sdk/assets/46803939/4cb72144-f74e-4ca9-b919-641371672f71)

```
{code: -32601, message: 'The method "metamask_connectSign" does not exist / is not available.', data: {…}}
```

### Expected Behavior

I hope to complete the connection and return the signature using connectAndSign. This is because when I separate the account request and the signature request, I find that on mobile, the connection request completes and then returns to the browser without the signature being completed. Therefore, I want to use connectAndSign to redirect users to the browser only after the connection and signature are completed. However, I discovered that connectAndSign is not available when importing metamask-sdk.js via CDN.

### To Reproduce

After clicking the button to call the connect() function, a description error related to connectAndSign appears. When using React, I can normally call connectAndSign, but when I try to import metamask-sdk.js via CDN, I find that connectAndSign is not available.

**Comment by christopherferreira9** [comment]
Hi @HGZ-20 ! I've investigated this issue and it seems that it only works on the first try and after that you get the issue before even getting the SDK dialog to select extension or mobile. I'll escalate this with the team, thank you for reporting!

https://github.com/MetaMask/metamask-sdk/assets/104831203/391796eb-8ea0-49a0-9088-85760d30af9a

**Comment by HGZ-20** [comment]
Hi @christopherferreira9 , thank you very much for taking the time to replicate this issue. In my code, even the first attempt throws the error "The method 'metamask_connectSign' does not exist." Would you mind sharing the key parts of the code you used for replication? It seems I am facing a more severe problem than you did during your replication.

**Comment by christopherferreira9** [comment]
@HGZ-20 I pretty much used the same code you provided :)  
Here's the code I've used:
```javascript
<html>
    <head>
        <script src="https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/cdn/metamask-sdk.js"></script>
        <script>
            async function connect() {
                const sdk = new MetaMaskSDK.MetaMaskSDK({
                    useDeepLink: false,
                    dappMetadata: {
                        name: "Pure JS example",
                        url: 'https://metamask.io',
                    },
                    enableAnalytics: true,
                    checkInstallationImmediately: false,
                });
    
            await sdk?.init();
    
            const sig = await sdk?.connectAndSign({msg: "hello"});
            console.log(sig);
        }
        </script>
    </head>
    <body>
        <h1>MMSDK</h1> 
        <button onclick="connect()">Connect</button>   
    </body>
</html>


```

**Comment by HGZ-20** [comment]
@christopherferreira9 Thank you for your response. After clearing all the browser data, I found that indeed the first connection can be made normally, but subsequent connections all result in an error. Additionally, each time in incognito mode, it's possible to successfully connect on the first try, with subsequent attempts failing. I wonder if it's related to specific browser cache data. I look forward to your solution, and thank you once again.

**Comment by jarethuk** [comment]
Encountering the same issue. Has this been looked at now?

**Comment by DevidChhaya** [comment]
Same issue happen for me
