### ISSUE TITLE
[Bug]: Creating an instance of SDK triggers extension connection

### ISSUE THREAD

**Issue by vlakam** [MetaMask/metamask-sdk#796]
### SDK

Web

### Provide environment information

Vue.js example in repo

### MetaMask SDK Version

0.18.2

### MetaMask Mobile app Version

any, not related

### What browser are you using? (if relevant)

any

### How are you deploying your application? (if relevant)

vite

### Describe the Bug

The moment SDK instance is created it gonna trigger wallet connection, if extension is present.

### Expected Behavior

Wallet connection triggered by connect or connectAndSign methods

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/MetaMask/metamask-sdk/blob/main/packages/examples/vuejs/README.md

### To Reproduce

Have extension installed in browser
Deploy or start example
Enter the page

**Comment by christopherferreira9** [comment]
Hi! Can you please try to make sure all localStorage and cache is clean on the browser before trying to connect?

**Comment by vlakam** [comment]
The bug somehow not reproducible anymore
