### ISSUE TITLE
[Bug]: USDT transfer fee on Ethereum chain is too much high

### ISSUE THREAD

**Issue by sagarrudani302** [MetaMask/metamask-sdk#798]
### SDK

Unity

### Provide environment information

I am using Unity version 2021.3.14f1 with the Android platform. 

### MetaMask SDK Version

1.3.1

### MetaMask Mobile app Version

7.19.0

### Describe the Bug

Currently, I am working on an Android build. I have already downloaded the metamask sample project and opened it in my Unity.

so in my app, there is an add balance functionality with the usdt coin option so I want to use a meta mask for transferring usdt token coins on the Ethereum chain.

So in your meta mask demo when I click on transaction with Ethereum chain then it’s working fine with the normal gas fees. 
![image (1)](https://github.com/MetaMask/metamask-sdk/assets/72374560/399bfa28-e834-4863-b136-1c27591261f3)
![IMG_7204](https://github.com/MetaMask/metamask-sdk/assets/72374560/f81cd276-f75f-419d-bca5-995eff0f5b8b)

But when I try to view tokens in the demo and click on the transfer usdt option then add the wallet address and 10 usdt amount then the gas fees I around 3 Eth so how can I manage gas fees of usdt token transfer?
![image](https://github.com/MetaMask/metamask-sdk/assets/72374560/076ca16e-d2e3-44f1-9b55-636e5103463a)
![2d05c6d8-a3a6-4d72-bddc-77698b8446b5](https://github.com/MetaMask/metamask-sdk/assets/72374560/be5cd588-8896-456f-9c44-8edf6e3dc853)
![42d86b93-dd84-4e21-acd8-d6c4de773cf8](https://github.com/MetaMask/metamask-sdk/assets/72374560/a73a0ac8-5e89-4962-a1d3-a1657597edc5)

so, in general, I want to add functionality in my game like Connect Wallet -> transfer USDT token in my metamask wallet. so please help me to solve this problem.

### Expected Behavior

When I try to transfer USDT token over the Ethereum chain ID then the usdt transfer is low but not like in the attached images. so please help me to solve this this is the metamask demo project I have not changed anything in this.

### To Reproduce

Download MetaMask Sample Project => Run project in editor => click on view tokens => click on usdt => enter address and amount and click on transfer.

**Comment by christopherferreira9** [comment]
Hi @sagarrudani302 ! We will be looking at this issue and get a fix for it if we're able to confirm it in the coming days. Thank you for responding!

**Comment by sagarrudani302** [comment]
Please do it fast I am stuck only on this issue. PLease solve it as soon as possible.

**Comment by christopherferreira9** [comment]
Hi @sagarrudani302 ! We've checked this and we don't currently provide any explicit amount of gas when making a new transaction for ERC20 tokens. Can you please open a new issue within the [MetaMask Mobile repo](https://github.com/MetaMask/metamask-mobile) in the meantime?
