### ISSUE TITLE
[Bug]: Get initialization error when using MetaMaskProvider in a react project

### ISSUE THREAD

**Issue by zhaoyi0113** [MetaMask/metamask-sdk#813]
### SDK

Web

### Provide environment information

Chrom, React, Mac

### MetaMask SDK Version

"@metamask/sdk-react": "^0.18.0",

### MetaMask Mobile app Version

na

### What browser are you using? (if relevant)

chrome

### Describe the Bug

I have below code in a react project. When running the UI on chrome, I got initialization error:

```
TypeError: Cannot assign to read only property 'ethereum' of object '#<Window>'

app-index.js:35 [MetaMaskSDK: constructor()] error during initialization TypeError: Cannot assign to read only property 'ethereum' of object

```

```
import { MetaMaskProvider } from '@metamask/sdk-react';


...

<MetaMaskProvider
          debug={true}
          sdkOptions={{
            dappMetadata: { name: 'Example' },
          }}
        >
...
```

### Expected Behavior

Expect it initialize all needed libraries

### To Reproduce

Use this code in any react project:

```
<MetaMaskProvider
          debug={true}
          sdkOptions={{
            dappMetadata: { name: 'Example' },
          }}
        >
```

**Comment by christopherferreira9** [comment]
Hi @zhaoyi0113 ! Please refer to our [React example](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/create-react-app). These examples were recently updated and you should not experience this issue with them.
