### ISSUE TITLE
[Bug]: sdk?.connect() halts when connect inside a useEffect()

### ISSUE THREAD

**Issue by andremfaria** [MetaMask/metamask-sdk#825]
### SDK

Web

### Provide environment information

Android: 14
Chrome Android: 123.0.6312.100
MetaMask mobile app: 7.19.1 (1306)

### MetaMask SDK Version
@metamask/sdk-react: 0.18.6

### MetaMask Mobile app Version

7.19.1 (1306)

### What browser are you using? (if relevant)

Chrome Android: 123.0.6312.100

### Describe the Bug

When using Chrome on Android and attempting to execute `sdk?.connect()` within a `useEffect`, the call halts and never returns. The issue only occurs on mobile.

### Expected Behavior

It should connect to the user wallet. 

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/andremfaria/mm-use-effect-connect

### To Reproduce

1. Run the application in the example repository.
2. Access `https://<your-local-ip>/5174` from the Chrome browser on an Android device.
3. Check the logs; you will notice that the `.connect()` call never returns.

**Comment by christopherferreira9** [comment]
Hi @andremfaria ! We'll be looking at this during next week. In the meantime, it is advised that the mobile to mobile interaction (meaning mobile chrome to MetaMask mobile) should always be tied to a deeplink and for that to happen if needs user input like a tap on a button instead of being programatically called as mobile OS's will prevent such events.

**Comment by christopherferreira9** [comment]
Hi @andremfaria ! Are you still experiencing the same issue taking into consideration the tip provided above?

**Comment by andremfaria** [comment]
Hi @christopherferreira9, I followed your tip and added a button to explicitly connect and respect the OS's restrictions for the mobile version. Thanks for your help!

**Comment by ram4444** [comment]
Hi,
I got the same problem in react-native android

**Comment by christopherferreira9** [comment]
@ram4444 please take a look at https://github.com/MetaMask/metamask-sdk/issues/825#issuecomment-2096053815 . Will be closing this in the meantime.
