### ISSUE TITLE
[Bug]: ABI Converter Fails uint8 Output

### ISSUE THREAD

**Issue by WoodsFiend** [MetaMask/metamask-sdk#826]
### SDK

Unity

### Provide environment information

Unity Editor

### MetaMask SDK Version

1.3.1

### MetaMask Mobile app Version

N/A

### Describe the Bug

When using the **Contract ABI Converter** tool. ABI functions with a uint8 output value fails to generate with error:

`Exception: Unsupported evm type uint8
evm.net.Generator.ContractInterfaceGenerator.WriteABIFunction (evm.net.Models.ABI.ABIFunction def) (at <3ea4c17b949e4afa9d9473ad519f1930>:0)
evm.net.Generator.ContractInterfaceGenerator.WriteFunction (evm.net.Models.ABI.ABIDef def) (at <3ea4c17b949e4afa9d9473ad519f1930>:0)
evm.net.Generator.ContractInterfaceGenerator.DoWrite () (at <3ea4c17b949e4afa9d9473ad519f1930>:0)
evm.net.Generator.CodeGenerator.Write (System.Boolean force) (at <3ea4c17b949e4afa9d9473ad519f1930>:0)
evm.net.Generator.CodeGenerator.GenerateString () (at <3ea4c17b949e4afa9d9473ad519f1930>:0)
evm.net.Generator.CodeGenerator.GenerateAll () (at <3ea4c17b949e4afa9d9473ad519f1930>:0)
ContractGeneratorEditor.OnGUI () (at Assets/MetaMask/Plugins/Libraries/evm.net/Editor/ContractGeneratorEditor.cs:86)`

### Expected Behavior

I expected the **Contract ABI Converter** to successfully generate Unity scripts for an ABI that has a function with uint8 output values.

### To Reproduce

Attempt to convert this ABI with the **Contract ABI Converter** tool.

`{
  "contractName": "Test",
  "sourceName": "contracts/Test.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "name": "tokenMetadata",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "gel",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "tokensHeld",
          "type": "uint256"
        },
        {
          "internalType": "uint32",
          "name": "morph",
          "type": "uint32"
        },
        {
          "internalType": "string",
          "name": "name",
          "type": "string"
        },
        {
          "internalType": "string",
          "name": "token",
          "type": "string"
        },
        {
          "internalType": "uint8",
          "name": "level",
          "type": "uint8"
        },
        {
          "internalType": "uint8",
          "name": "health",
          "type": "uint8"
        },
        {
          "internalType": "uint8",
          "name": "speed",
          "type": "uint8"
        },
        {
          "internalType": "uint8",
          "name": "power",
          "type": "uint8"
        },
        {
          "internalType": "uint8",
          "name": "resistance",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
]
}`

**Comment by Sungyong-Sanchez-Lee** [comment]
MetaMask SDK Version 2.0.0  same issue

**Comment by christopherferreira9** [comment]
This will be fixed in the upcoming release version 2.1.0 that should be released by the end of this week/beginning of next week.
