### ISSUE TITLE
[Unity] WebGL build ios deeplink not work

### ISSUE THREAD

**Issue by haling79** [MetaMask/metamask-sdk#83]
**Describe the bug**
WebGL build is on ios, deeplink does not work properly.

IOS Chrome -- I can navigate through the popup, but it only takes me to the app store, even when Metamask is already installed.
IOS Safari -- No response.

Android Chrome -- Works well

**Expected behaviour**
If MetaMask is not installed, it should point to the app store and if it is already installed, it should be ConnectWallet.

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): Unity Webgl
- MetaMask SDK Version: 1.1.1
- MetaMask Mobile Version:  v6.3.0(1095)
- Browser (if relevant): Chrome, Safari

**Comment by christopherferreira9** [comment]
Hi @haling79 ! This is currently being fixed and we're close to launching a fix for these issues.

Closing this as it doesn't relate to this repo
