### ISSUE TITLE
[Bug]: Unable to install @metamask/sdk with npm

### ISSUE THREAD

**Issue by hiendaovinh** [MetaMask/metamask-sdk#833]
### SDK

Web

### Provide environment information

node: v20.11.0
npm: 10.7.0

### MetaMask SDK Version

0.19.0

### MetaMask Mobile app Version

Not related

### Describe the Bug

Trying to install metamask with npm but it fails because the package specifies dependencies with "workspace:"
https://github.com/MetaMask/metamask-sdk/blob/main/packages/sdk/package.json#L49-L50

### Expected Behavior

Be able to install the package without using pnpm/yarn. According to the docs, we could use npm: https://docs.metamask.io/wallet/how-to/use-sdk/javascript/

### To Reproduce

```sh
npm i @metamask/sdk@0.19.0
```

```
npm verbose node v20.11.0
npm verbose npm  v10.7.0
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
npm verbose exit 1
npm verbose code 1
```

**Comment by mahirfatihunal** [comment]
When i visit issues page to report this bug, I saw that it had already been reported. 
Unfortunately, there is the problem mentioned in v0.19.0.

**Comment by cihanbas** [comment]
i have same issue

**Comment by cihanbas** [comment]
but when i downgrade version of metamsk it is working for me, 
`npx expo install expo-crypto @metamask/sdk-react@0.18.6 ethers@5.7.2 @react-n
ative-async-storage/async-storage node-libs-expo react-native-background-timer react-native-randomb
ytes react-native-url-polyfill react-native-get-random-values@1.8.0`

**Comment by christopherferreira9** [comment]
Hi all! This has been fixed the latest version we published a few minutes ago 🚀

**Comment by mahirfatihunal** [comment]
> but when i downgrade version of metamsk it is working for me,
> 
> `npx expo install expo-crypto @metamask/sdk-react@0.18.6 ethers@5.7.2 @react-n ative-async-storage/async-storage node-libs-expo react-native-background-timer react-native-randomb ytes react-native-url-polyfill react-native-get-random-values@1.8.0`

The bug is already in the current version (v0.19.0). Not in previous version. Fortunately, they will fix it.
