### ISSUE TITLE
[Bug]: Module @react-native-async-storage/async-storage not found

### ISSUE THREAD

**Issue by ammirator-administrator** [MetaMask/metamask-sdk#857]
### SDK

Web

### Provide environment information

browser, react JS application, Not react-native, not sure why a react native at all package is needed in a browser package
Below more info

### MetaMask SDK Version

0.20.2

### MetaMask Mobile app Version

latest

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

local

### Describe the Bug

When installing version 0.20.2 @metamask/sdk-react and opening the browser with some integration of metamask
it says that Module @react-native-async-storage/async-storage not found
I guess you guys forgot to add it to dependencies in pkg.json

Also why is there a react-native package used in browser package? is it for react js not react-native

### Expected Behavior

not failing)

### To Reproduce

Just install version 0.20.2 @metamask/sdk-react, add that to a react application and open the app in browser and see the problem

**Comment by tomohiro-n** [comment]
I observed the same problem, and it's gone when I downgrade to 0.18.6.

**Comment by ammirator-administrator** [comment]
yes, same I did
But definitelly this needs investigation from their side
My guess, they just forgot to add it in dependencies in pkg.json)

**Comment by christopherferreira9** [comment]
Hi all! This will be fixed today with a new release. Will be updating this issue once we've finished.

**Comment by christopherferreira9** [comment]
Hi all! We've released a new version of the `sdk-react` package last week. Can you please give it a go as it should fix the reported issue? I'm closing this issue in the meantime, please feel free to open a new issue at any time.
