### ISSUE TITLE
showQRCode option for MetaMaskSDK ignored

### ISSUE THREAD

**Issue by muscleman** [MetaMask/metamask-sdk#86]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
` 
    const sdk = new MetaMaskSDK({ shouldShimWeb3: false, showQRCode: false })
    const provider = sdk.getProvider()
    if (provider) {
      const accounts = await provider.request({ method: "eth_requestAccounts", params: [] })
      console.log(">>>>", accounts[0], "<<<<")
    } else {
      console.log("Please install MetaMask!")
    }
`

**Expected behaviour**
I do not expect to see the qrcode in the console output

**Screenshots**
![Screenshot from 2023-04-28 11-00-13](https://user-images.githubusercontent.com/4632339/235197108-6248d657-03ac-4f4d-b973-22ed0f039ec6.png)

** Provide environment information**
- MetaMask SDK Version:
0.2.1

**Comment by abretonc7s** [comment]
Hi muscleman,

That option is not available is that version of the sdk but this is a good feature request and will be added for next release.
