### ISSUE TITLE
[Bug]: When confirming transactions, wrong url is displayed to MM mobile app user

### ISSUE THREAD

**Issue by Nk185** [MetaMask/metamask-sdk#862]
### SDK

Web

### Provide environment information

MacBook Pro (NOV2023, Apple M3 Pro, Sonoma 14.5), chromium extension, react, typescript, vite. Build inside Alpine-based docker container.

### MetaMask SDK Version

0.20.3

### MetaMask Mobile app Version

7.22.0 (1325)

### What browser are you using? (if relevant)

Chrome (arm64) version 125.0.6422.142 (Official Build)

### Describe the Bug

When establishing a connection b\w chromium extension and MM mobile (via sockets.io) using MM SDK, the "Connect account" dialog shows the correct app URL, specified in the `dappMetadata` object (✅):
<img src="https://github.com/MetaMask/metamask-sdk/assets/17277797/80226a01-861b-4f80-b351-cf20dcc45509" width="300">
 
But when attempting to send a transaction, the confirmation dialog shows some gibberish, likely related to sockets.io room (❌):
<img src="https://github.com/MetaMask/metamask-sdk/assets/17277797/5715c8cc-d696-42aa-bc1f-3137e9c75022" width="300">

### Expected Behavior

The confirmation dialog in MM mobile shows the correct origin, just as in the connection dialog.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/Nk185/mm_sdk-bug

### To Reproduce

1. Build extension as described in the repository — either using npm or inside docker via shell script.
2. Load the extension into your Google Chrome (or another Chromium-based browser).
3. Open the extension and click "Connect".
4. Initiate the connection to your MM mobile app.
4.1 Observe the correct URL shown in your mobile app.
5. Return back to the extension, optionally enter an Ethereum address in the input, and click "Request" transfer.
6. In your MM mobile app, observe the incorrect URL.
7. Finally, reject the transaction and unload the extension from your browser.

**Comment by christopherferreira9** [comment]
Hi @Nk185. We are aware of this issue and we're currently finishing the work around it on the mobile wallet side. I'll update this ticket once it is merged and ready to be shipped.
