### ISSUE TITLE
unable to obtain the string from getUniversalLink

### ISSUE THREAD

**Issue by muscleman** [MetaMask/metamask-sdk#87]
**Describe the bug**
currently is not possible to get the universallink to a variable.

**To Reproduce**
`      const sdk = new MetaMaskSDK({
        shouldShimWeb3: false,
        shouldSetOnWindow: false,
        showQRCode: false,
        logging: {
          developerMode: true,
          sdk: true
        }
      })
      const ethereum = sdk.getProvider()
      sdk.getUniversalLink()
      await ethereum.request({ method: "eth_requestAccounts", params: [] })`

**Expected Behavor**
i should be able to obtain the string in nodejs

**Comment by joeynorkin** [comment]
Two things to note:
1. shouldSetOnWindow and showQRCode don't seem to be acceptable fields for the [MetaMaskSDK constructor](https://github.com/MetaMask/metamask-sdk/blob/bc83f421c43b511b04e1af01dc779717ee582edd/packages/sdk/src/sdk.ts#L27)
2. [This error message](https://github.com/MetaMask/metamask-sdk/blob/bc83f421c43b511b04e1af01dc779717ee582edd/packages/sdk/src/sdk.ts#L354) suggests you need to first call eth_requestAccounts

**Comment by muscleman** [comment]
not sure you understand my issue.
unlike other javascript frameworks, electron is difficult to work with because of the ipcmain, and renderer model.

so... what i am trying to do is get the universalLink, send this to my implementation of the html renderer and render a qrcode in a dialog. just like your react version does. just my version.
meantime the call to eth_requestAccounts which blocks while the user scans my qrcode

**Comment by abretonc7s** [comment]
Hi Muscleman,

Thank you for reporting this feature request, we will see to add an option to expose the qrcode url instead of printing the qrcode.

**Comment by abretonc7s** [comment]
Hi @muscleman ,

The latest sdk version allows you to customize the modal interaction on the sdk.
Please see example in https://github.com/MetaMask/metamask-sdk/blob/main/packages/examples/nodejs/index.js .
