### ISSUE TITLE
[Bug]: Connection Issue

### ISSUE THREAD

**Issue by Mehulkmar** [MetaMask/metamask-sdk#881]
### SDK

Unity

### Provide environment information

 have integrated the SDK for unity and when I am trying to authenticate and connect my wallet with metamask mobile app, after authentication is successful, redirection to my app does not happen 90% of the time and it just stays in the metamask app.

Looking for someone's help around this asap.

### MetaMask SDK Version

2.0.0

### MetaMask Mobile app Version

7.23.0

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Over telegram

### Describe the Bug

 have integrated the SDK for unity and when I am trying to authenticate and connect my wallet with metamask mobile app, after authentication is successful, redirection to my app does not happen 90% of the time and it just stays in the metamask app.

Looking for someone's help around this asap.

### Expected Behavior

Get connection request whenever i goes over metamask using dapp url.

### To Reproduce

i am connect my application with metamask and it goes over the metamask but connection request is not show me

**Comment by christopherferreira9** [comment]
Hi @Mehulkmar ! What's the platform target you're using on Unity? Does this happen for both Android and iOS or is it OS specific?

**Comment by Mehulkmar** [comment]
Hi, I am working on a WebGL platform. It connects sometimes only with
Android, but it doesn't connect with iOS.

**Comment by christopherferreira9** [comment]
Do you have a dapp we can try on our side or a repo that we can build ourselves? 
The original issue referred to the redirection back, this only happens on Android since iOS started blocking that operation since the launch of iOS 17.
Are you experiencing issues with establishing a connection itself or just the redirect part?

**Comment by Mehulkmar** [comment]
I am facing issues of redirect back in iPhone and connectivity issue in both iPhone and Android.

**Comment by christopherferreira9** [comment]
Hi all!  We're still working on this release and currently bumping into a few issues but it should be released soon.

**Comment by christopherferreira9** [comment]
Hi all! This should be fixed with the latest release `2.0.1`.
