### ISSUE TITLE
[Bug]: Contract ABI EvmAddress[] Fails Encoding 

### ISSUE THREAD

**Issue by WoodsFiend** [MetaMask/metamask-sdk#895]
### SDK

Unity

### Provide environment information

Unity 2022.3
Editor
Windows OS

### MetaMask SDK Version

2.0.0

### MetaMask Mobile app Version

N/A

### Describe the Bug

When using a contract that has an EvmAddress[] parameter the Nethereum Encoding fails. This causes the contract function to not work.

### Expected Behavior

The encoding succeeds when calling a function with an EvmAddress[];

An alternative workaround is to use string[] instead. If this is the preferred solution the MetaMask Contract ABI Converter should generate ABI address[] variables as string[]

### To Reproduce

Call a contract function that has an EvmAddress[] as a parameter.

**Comment by christopherferreira9** [comment]
Hi @WoodsFiend this has been fixed on the upcoming release that should be released soon.
