### ISSUE TITLE
[Bug]: The Pure JS example doesn't work, fail to detect Metamask extension

### ISSUE THREAD

**Issue by jimgreen2013** [MetaMask/metamask-sdk#916]
### SDK

Web

### Provide environment information

I've tried firefox, chromium and Braver browser, my os is Linux/Fedora

### MetaMask SDK Version

0.18.5

### MetaMask Mobile app Version

Just web

### Describe the Bug

![image](https://github.com/MetaMask/metamask-sdk/assets/15890793/5aaa7294-13a3-49c5-ba15-eb0ee2f4e35b)

### Expected Behavior

![image](https://github.com/MetaMask/metamask-sdk/assets/15890793/708aece8-d8e5-4e19-8b3f-d0a043b3305d)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/pure-javascript

### To Reproduce

open the index.html and click `connect`

**Comment by christopherferreira9** [comment]
Hi @jimgreen2013 !  I wasn't able to reproduce this using OSX. Will try to give this one a go using Linux. I'll get back to this issue as soon as possible.

**Comment by jimgreen2013** [comment]
> Hi @jimgreen2013 ! I wasn't able to reproduce this using OSX. Will try to give this one a go using Linux. I'll get back to this issue as soon as possible.

I try my best to do some investigation, here is my findings: 1. the vue example run as expected; 2. The key difference is that the vue example successfully inject `window.etherum` and `window.extension` while the pureJs example only inject `window.etherum`.

**Comment by jimgreen2013** [comment]
@christopherferreira9  Finally, I find out the reason, it's not a bug but due to opening the index.html directly in the browser instead of serving it through a http server.

I have updated the README file and add more information, here is  the pull request #930

**Comment by christopherferreira9** [comment]
awesome @jimgreen2013 ! We'll be addressing your PR soon. I'm closing this issue in the meantime.
