### ISSUE TITLE
[Bug]: Unsupported evm type bytes[] or bytes32[]

### ISSUE THREAD

**Issue by qanh10x10** [MetaMask/metamask-sdk#931]
### SDK

Unity

### Provide environment information

Cannot convert contract ABI json dues to error

### MetaMask SDK Version

2.0.0

### MetaMask Mobile app Version

2.0.0

### Describe the Bug

Exception: Unsupported evm type bytes[]
evm.net.Generator.ContractInterfaceGenerator.BuildParameter (evm.net.Models.ABI.ABIParameter parameter) (at <4d5d29ec07e94c2fbac6ecd780578817>:0)
System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () (at <f37d63bf724b4debb9eecb3c7c2abb7e>:0)
System.Linq.Enumerable+AppendPrependIterator`1[TSource].LoadFromEnumerator () (at <f37d63bf724b4debb9eecb3c7c2abb7e>:0)
System.Linq.Enumerable+AppendPrepend1Iterator`1[TSource].MoveNext () (at <f37d63bf724b4debb9eecb3c7c2abb7e>:0)
System.String.Join (System.String separator, System.Collections.Generic.IEnumerable`1[T] values) (at <4b234520e36749be9cf6b053d911690f>:0)
evm.net.Generator.ContractInterfaceGenerator.BuildParameters (evm.net.Models.ABI.ABIParameter[] parameters) (at <4d5d29ec07e94c2fbac6ecd780578817>:0)
evm.net.Generator.ContractInterfaceGenerator.WriteABIFunction (evm.net.Models.ABI.ABIFunction def) (at <4d5d29ec07e94c2fbac6ecd780578817>:0)
evm.net.Generator.ContractInterfaceGenerator.WriteFunction (evm.net.Models.ABI.ABIDef def) (at <4d5d29ec07e94c2fbac6ecd780578817>:0)
evm.net.Generator.ContractInterfaceGenerator.DoWrite () (at <4d5d29ec07e94c2fbac6ecd780578817>:0)
evm.net.Generator.CodeGenerator.Write (System.Boolean force) (at <4d5d29ec07e94c2fbac6ecd780578817>:0)
evm.net.Generator.CodeGenerator.GenerateString () (at <4d5d29ec07e94c2fbac6ecd780578817>:0)
evm.net.Generator.CodeGenerator.GenerateAll () (at <4d5d29ec07e94c2fbac6ecd780578817>:0)
ContractGeneratorEditor.OnGUI () (at Assets/MetaMask/Plugins/Libraries/evm.net/Editor/ContractGeneratorEditor.cs:86)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at <24e1ed8728684ea3ae446f80787d18de>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) (at <24e1ed8728684ea3ae446f80787d18de>:0)
UnityEditor.DockArea.OldOnGUI () (at <24e1ed8728684ea3ae446f80787d18de>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.IMGUIContainer.ProcessEvent (UnityEngine.UIElements.EventBase evt) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase evt) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <05f2afe6185f419bbdba66c4cec39481>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <fe08c3ba433e444c9b1917db1ad827bb>:0)

### Expected Behavior

it should support bytes[] and bytes32[]

### To Reproduce

evm.net.models.generator should support bytes[] and bytes32[]

**Comment by QuipHop** [comment]
Please also notice 
Exception: Unsupported evm type tuple[]

**Comment by christopherferreira9** [comment]
Hi all! This should be fixes with the latest release `2.0.1`.

**Comment by nguyenpqdev** [comment]
I am using MetaMask SDK version 2.1.0, which I downloaded from the Unity Asset Store, but I am encountering an issue when trying to convert an ABI contract. Despite using the latest version, the conversion process fails.

Unity version: 2022.3.55f1
Exception: Unsupported evm type bytes32[]
How to fix it?
