### ISSUE TITLE
[Bug]: The pure-javascript sample cannot connect or getProvider in the Android MetaMask APP browser.

### ISSUE THREAD

**Issue by syhuang75** [MetaMask/metamask-sdk#949]
### SDK

Web

### Provide environment information

Springboot + thymeleaf + pure-javascript

### MetaMask SDK Version

0.26.5

### MetaMask Mobile app Version

v7.26.1(1360)

### Describe the Bug

I deployed the example program from https://github.com/MetaMask/metamask-sdk/blob/main/packages/examples/pure-javascript/index.html on my test website. When opened in the browser built into the MetaMask APP, the iOS version can connect and getProvider correctly, but the Android version has consistently failed to connect and getProvider properly.
Additionally, I replaced the line in the code from:
<script src="/node_modules/@metamask/sdk/dist/browser/iife/metamask-sdk.js"></script>
to:
<script src="https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/cdn/metamask-sdk.js"></script>
(I also tried directly importing version 0.26.5 of metamask-sdk.js.)

### Expected Behavior

I expect the behavior of both iOS and Android to be the same, and both should work properly.

### To Reproduce

Step 1. Copy https://github.com/MetaMask/metamask-sdk/blob/main/packages/examples/pure-javascript/index.html.
Step 2. Replaced the line in the code from:
```
<script src="/node_modules/@metamask/sdk/dist/browser/iife/metamask-sdk.js"></script>
```
to:
```
<script src="https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/cdn/metamask-sdk.js"></script>
```
Step 3. Built the webpage through Spring Boot, deployed the bootjar to the test server.
Step 4. Used an Android phone's Chrome browser to open the webpage and perform the Connect.

**Comment by christopherferreira9** [comment]
Hi @syhuang75. We've deployed this example app and we're able to connect using it. In this video example I've added  some info to the app to make it easier to see.

https://github.com/user-attachments/assets/935c8f6f-0b3f-42fd-9b97-093452890b3b

Can you try to launch it locally and serve it via `http-server` or something similar to see if the issue persists? I suspect it might happen due to Spring boot itself.

**Comment by syhuang75** [comment]
We found the cause of the error; it was due to an issue occurring during our web page and API calls. Thank you very much.
