### ISSUE TITLE
[Bug]: preferDesktop option not working

### ISSUE THREAD

**Issue by zhangjing28** [MetaMask/metamask-sdk#954]
### SDK

Web

### Provide environment information

1. Using the examples that you guys provided: https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/create-react-app
2. Add `preferDesktop` in the `index.tsx` like this
```javascript
<MetaMaskProvider debug={false} sdkOptions={{
      logging:{
          developerMode: false,
        },
        communicationServerUrl: process.env.REACT_APP_COMM_SERVER_URL,
        checkInstallationImmediately: false, // This will automatically connect to MetaMask on page load
        i18nOptions: {
          enabled: true,
        },
        dappMetadata: {
          name: "Demo React App",
          url: window.location.protocol + '//' + window.location.host,
          
        },
        preferDesktop: true
    }}>
      <App />
</MetaMaskProvider>
```

### MetaMask SDK Version

^0.26.3

### MetaMask Mobile app Version

No

### What browser are you using? (if relevant)

Chrome 126.0.6478.127

### Describe the Bug

Set `preferDesktop` true, but not display the 'Desktop' tab by default.

### Expected Behavior

 Display the 'Desktop' tab by default

### To Reproduce

1. Using the examples that you guys provided: https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/create-react-app
2. Add `preferDesktop` in the `index.tsx` like this
```javascript
<MetaMaskProvider debug={false} sdkOptions={{
      logging:{
          developerMode: false,
        },
        communicationServerUrl: process.env.REACT_APP_COMM_SERVER_URL,
        checkInstallationImmediately: false, // This will automatically connect to MetaMask on page load
        i18nOptions: {
          enabled: true,
        },
        dappMetadata: {
          name: "Demo React App",
          url: window.location.protocol + '//' + window.location.host,
          
        },
        preferDesktop: true
    }}>
      <App />
</MetaMaskProvider>
```

**Comment by christopherferreira9** [comment]
Hi @zhangjing28 . We've released a new version very recently where this issue is fixed. Can you please bump the SDK version to 0.27.0. We're closing this issue for the time being.
