### ISSUE TITLE
[Bug]: No Option to turn off mobile tab in the widget. 

### ISSUE THREAD

**Issue by Galileo-Tech-Department** [MetaMask/metamask-sdk#982]
### SDK

Web

### Provide environment information

![image](https://github.com/user-attachments/assets/ee82bf99-8a10-4c77-95d8-196e3eb91bc0)
If you want to restrict user to only connect wallet using web there is no option in the modal to disable that 

i have tried
[https://docs.metamask.io/wallet/reference/sdk-j...](https://docs.metamask.io/wallet/reference/sdk-js-options/#ui)

all these booleans in sdk configuration
preferDesktop: true
extensionOnly: true
etc
but nothing works

### MetaMask SDK Version

0.27.0

### MetaMask Mobile app Version

1.0.0

### Describe the Bug

![image](https://github.com/user-attachments/assets/ee82bf99-8a10-4c77-95d8-196e3eb91bc0)
If you want to restrict user to only connect wallet using web there is no option in the modal to disable that 

i have tried
[https://docs.metamask.io/wallet/reference/sdk-j...](https://docs.metamask.io/wallet/reference/sdk-js-options/#ui)

all these booleans in sdk configuration
preferDesktop: true
extensionOnly: true
etc
but nothing works

### Expected Behavior

Should have something like

disableMobileTab: true

### To Reproduce

Just click on the connect button which calls sdk.connect
and disable metamask extension

**Comment by christopherferreira9** [comment]
Hi @Galileo-Tech-Department ! On version `0.27.0` the SDK connects directly to the MetaMask extension if it is detected via EIP-6963. If the extension is not detected we give the user the opportunity to connect via QR Code to the MetaMask mobile wallet. 
Are you attempting to connect to another wallet extension via the MMSDK?

**Comment by Galileo-Tech-Department** [comment]
@christopherferreira9 no we are trying to connect metamask wallet
but there are a couple configuration options available for metamask like extensionOnly: true
What we want is to restrict the user to only use extension and if he has not installed then only show the UI with Desktop tab 
Somehow just hide the mobile option altogether
