### ISSUE TITLE
[Bug]: sdk-react-native version on iOS connections

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-sdk#983]
### SDK

React-Native

### Provide environment information

ReactNative dapp using the sdk-react-native SDK.

Versions used: 
sdk-react-native@3.5.4

### MetaMask SDK Version

sdk-react-native@3.5.4

### MetaMask Mobile app Version

7.28.0

### Describe the Bug

The version displayed in MetaMask when connecting with the sdk-react-native is currently displaying `SDK ios v1.0` which doesn't match any version currently being used.

### Expected Behavior

The version matches the `@metamask/sdk-react-native` package version.

### To Reproduce

1. Lunch a ReactNative dapp that uses the `@metamask/sdk-react-native` package
2. Connect
3. See issue

![SDK react native screenshot July 17](https://github.com/user-attachments/assets/b4fe2ab8-cfd8-43c3-b2e4-6f5b578599e4)

**Comment by omridan159** [comment]
https://github.com/MetaMask/metamask-sdk/pull/1015
